### ISSUE TITLE
Sorbet init crashes when printing symbol table

### ISSUE THREAD

**Issue by Andy-Bell** [sorbet/sorbet#1099]
#### Input
sorbet init crashes on writing to the reflection.json on latest version `Sorbet typechecker 0.4.4334 git 319ec980c4c0b7616fe9b406437b93274ba802b2 built on 2019-06-27 06:56:17 GMT with debug symbols`

#### Observed output

```
Printing /var/folders/m9/9zbts5m541df8z14x3d8_mc40000gn/T/d20190627-50209-n6puh/reflection.rbi's symbol table into /var/folders/m9/9zbts5m541df8z14x3d8_mc40000gn/T/d20190627-50209-n6puh/reflection.json
Traceback (most recent call last):
        5: from /Users/andy/.gem/ruby/2.6.2/gems/sorbet-0.4.4334/bin/srb-rbi:232:in `<main>'
        4: from /Users/andy/.gem/ruby/2.6.2/gems/sorbet-0.4.4334/bin/srb-rbi:101:in `main'
        3: from /Users/andy/.gem/ruby/2.6.2/gems/sorbet-0.4.4334/bin/srb-rbi:227:in `block in make_step'
        2: from /Users/andy/.gem/ruby/2.6.2/gems/sorbet-0.4.4334/lib/hidden-definition-finder.rb:38:in `main'
        1: from /Users/andy/.gem/ruby/2.6.2/gems/sorbet-0.4.4334/lib/hidden-definition-finder.rb:47:in `main'
/Users/andy/.gem/ruby/2.6.2/gems/sorbet-0.4.4334/lib/hidden-definition-finder.rb:145:in `write_constants': /var/folders/m9/9zbts5m541df8z14x3d8_mc40000gn/T/d20190627-50209-n6puh/reflection.rbi had unexpected errors. Check this file for a clue: /var/folders/m9/9zbts5m541df8z14x3d8_mc40000gn/T/d20190627-50209-n6puh/reflection.json.err (RuntimeError)
```

Looking in reflection.json.err, it seems to only be a collection of 5014 errors

#### Expected behavior
Init on `Sorbet typechecker 0.4.4296 git 84ca94bb59b7444a97368ee90aadc20740be43ab built on 2019-06-24 03:03:17 GMT with debug symbols`

```
Printing your code's symbol table into /var/folders/m9/9zbts5m541df8z14x3d8_mc40000gn/T/d20190627-50011-130iq6b/from-source.json
Printing /var/folders/m9/9zbts5m541df8z14x3d8_mc40000gn/T/d20190627-50011-130iq6b/reflection.rbi's symbol table into /var/folders/m9/9zbts5m541df8z14x3d8_mc40000gn/T/d20190627-50011-130iq6b/reflection.json
Reading /var/folders/m9/9zbts5m541df8z14x3d8_mc40000gn/T/d20190627-50011-130iq6b/from-source.json
Reading /var/folders/m9/9zbts5m541df8z14x3d8_mc40000gn/T/d20190627-50011-130iq6b/reflection.json
```

**Comment by Andy-Bell** [comment]
App to reproduce this issue: https://github.com/Andy-Bell/sorbet-issue

**Comment by jaredbeck** [comment]
> Looking in reflection.json.err, it seems to only be a collection of 5014 errors

Can confirm with latest sorbet (`0.4.4400`). **My `reflection.json.err` also contains only `5014` errors.** They look like this:

```
/var/folders/sb/69c3drbd4pl_0j0xydlssh200000gn/T/d20190708-40961-1jitiys/reflection.rbi:38747: Type `Elem` declared by parent `T.class_of(ActiveRecord::Base)` must be re-declared in `T.class_of(ActiveRecord::InternalMetadata)` https://srb.help/5014
       38747 |class ActiveRecord::InternalMetadata < ActiveRecord::Base
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-rails-0.3.0/rbi/activerecord.rbi:144: `Elem` declared in parent here
     144 |  Elem = type_template(fixed: ActiveRecord::Base)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The `0.4.4400` stack trace is basically the same as Andy got from `0.4.4334`.

**Comment by jaredbeck** [comment]
This may be a `sorbet-rails` issue, and may have already been fixed by https://github.com/chanzuckerberg/sorbet-rails/pull/68

> .. we need the generation code to define `Elem` for the class. (Every subclass of ActiveRecord::Base need to redefine this regardless)

Compare the discussion in https://github.com/chanzuckerberg/sorbet-rails/pull/68 to the [description of error 5014](https://sorbet.org/docs/error-reference#5014).

Upgrading `sorbet-rails` from `0.3.0` to `5bafcee6243b` seems to have fixed this issue for me.

**Comment by jasnow** [comment]
@Andy-Bell - Appears that this has been fixed. I forked/cloned and ran "srb init" against it.:
```
Generating /var/folders/lc/72klfq0j6x9dq5hysj5nsc7w0000gn/T/d20190712-81441-f4r7u4/reflection.rbi with 4750 modules and 127 aliases
Printing your code's symbol table into /var/folders/lc/72klfq0j6x9dq5hysj5nsc7w0000gn/T/d20190712-81441-f4r7u4/from-source.json
Printing /var/folders/lc/72klfq0j6x9dq5hysj5nsc7w0000gn/T/d20190712-81441-f4r7u4/reflection.rbi's symbol table into /var/folders/lc/72klfq0j6x9dq5hysj5nsc7w0000gn/T/d20190712-81441-f4r7u4/reflection.json
Reading /var/folders/lc/72klfq0j6x9dq5hysj5nsc7w0000gn/T/d20190712-81441-f4r7u4/from-source.json
Reading /var/folders/lc/72klfq0j6x9dq5hysj5nsc7w0000gn/T/d20190712-81441-f4r7u4/reflection.json
Building rbi id to symbol map
Building source id to symbol map
Writing /var/folders/lc/72klfq0j6x9dq5hysj5nsc7w0000gn/T/d20190712-81441-f4r7u4/hidden.rbi.tmp
```

**Comment by aisamanra** [comment]
This appears to have been an issue with `sorbet-rails` that is now fixed. If similar issues arise in the future, we can always revisit this issue.
