### ISSUE TITLE
(From Fuzzer) Segfault on Error->isCritical

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#1242]
#### Input

[→ View on sorbet.run](https://sorbet.run/#r%20%2A%5B1%5Dg%23typed%3Atrue%0Am%20do)

```ruby
r *[1]g#typed:true
m do
```

#### Observed output

```

newestest_crashers/crash-d1bb001e4d50b6a53e8af540599e92da9305c72f.done:1: Parse Error: unexpected token: syntax error https://srb.help/2001
     1 |r *[1]g#typed:true
              ^

newestest_crashers/crash-d1bb001e4d50b6a53e8af540599e92da9305c72f.done:2: Parse Error: unexpected token: syntax error https://srb.help/2001
     2 |m do
           ^
Segmentation fault: 11
```

Stack trace from fuzzer:

```
    #0 0x1792841 in sorbet::core::Error::isCritical() const /proc/self/cwd/core/Error.cc:44:23
    #1 0x17fa1b2 in sorbet::core::GlobalState::_error(std::__1::unique_ptr<sorbet::core::Error, std::__1::default_delete<sorbet::core::Error> >) const /proc/self/cwd/core/GlobalState.cc:1205:16
    #2 0x107d2c6 in sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_12::operator()(sorbet::cfg::Send*) const /proc/self/cwd/infer/environment.cc:770:35
    #3 0x107d2c6 in bool sorbet::typecaseHelper<sorbet::cfg::Instruction, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_12&>(sorbet::cfg::Instruction*, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_12&) /proc/self/cwd/./common/typecase.h:46
    #4 0x107d2c6 in void sorbet::typecase<sorbet::cfg::Instruction, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_12, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_13, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_14, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_15, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_16, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_17, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_18, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_19, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_20, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_21, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_22, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_23>(sorbet::cfg::Instruction*, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_12&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_13&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_14&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_15&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_16&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_17&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_18&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_19&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_20&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_21&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_22&&, sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&)::$_23&&) /proc/self/cwd/./common/typecase.h:56
    #5 0x10718a2 in sorbet::infer::Environment::processBinding(sorbet::core::Context, sorbet::cfg::Binding&, int, int, sorbet::infer::KnowledgeFilter&, sorbet::core::TypeConstraint&, sorbet::core::TypePtr&) /proc/self/cwd/infer/environment.cc:745:9
    #6 0x103d1a2 in sorbet::infer::Inference::run(sorbet::core::Context, std::__1::unique_ptr<sorbet::cfg::CFG, std::__1::default_delete<sorbet::cfg::CFG> >) /proc/self/cwd/infer/inference.cc:162:42
    #7 0x8d8c77 in sorbet::realmain::pipeline::CFGCollectorAndTyper::preTransformMethodDef(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >) /proc/self/cwd/main/pipeline/pipeline.cc:54:15
    #8 0x8ce2f7 in sorbet::ast::PostPonePreTransform_MethodDef<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context, true>::call(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::realmain::pipeline::CFGCollectorAndTyper&) /proc/self/cwd/./ast/treemap/treemap.h:204:1
    #9 0x8ce2f7 in sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapMethodDef(std::__1::unique_ptr<sorbet::ast::MethodDef, std::__1::default_delete<sorbet::ast::MethodDef> >, sorbet::core::Context) /proc/self/cwd/./ast/treemap/treemap.h:293
    #10 0x8ca733 in sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) /proc/self/cwd/./ast/treemap/treemap.h:666:24
    #11 0x8d0d93 in sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::Context) /proc/self/cwd/./ast/treemap/treemap.h:281:19
    #12 0x8caac9 in sorbet::ast::TreeMapper<sorbet::realmain::pipeline::CFGCollectorAndTyper, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) /proc/self/cwd/./ast/treemap/treemap.h:672:24
    #13 0x89a38a in std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper>(sorbet::core::Context, sorbet::realmain::pipeline::CFGCollectorAndTyper&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) /proc/self/cwd/./ast/treemap/treemap.h:712:27
    #14 0x89802a in sorbet::realmain::pipeline::typecheckOne(sorbet::core::Context, sorbet::ast::ParsedFile, sorbet::realmain::options::Options const&) /proc/self/cwd/main/pipeline/pipeline.cc:697:27
    #15 0x9702da in sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3::operator()() const /proc/self/cwd/main/pipeline/pipeline.cc:943:65
    #16 0x9702da in _ZNSt3__18__invokeIRZN6sorbet8realmain8pipeline9typecheckERNS_10unique_ptrINS1_4core11GlobalStateENS_14default_deleteIS6_EEEENS_6vectorINS1_3ast10ParsedFileENS_9allocatorISD_EEEERKNS2_7options7OptionsERNS1_10WorkerPoolEE3$_3JEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSP_DpOSQ_ /proc/self/cwd/external/llvm_toolchain/bin/../include/c++/v1/type_traits:4353
    #17 0x9702da in void std::__1::__invoke_void_return_wrapper<void>::__call<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&>(sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3&) /proc/self/cwd/external/llvm_toolchain/bin/../include/c++/v1/__functional_base:349
    #18 0x9702da in std::__1::__function::__alloc_func<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3, std::__1::allocator<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3>, void ()>::operator()() /proc/self/cwd/external/llvm_toolchain/bin/../include/c++/v1/functional:1527
    #19 0x9702da in std::__1::__function::__func<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3, std::__1::allocator<sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&)::$_3>, void ()>::operator()() /proc/self/cwd/external/llvm_toolchain/bin/../include/c++/v1/functional:1651
    #20 0x19d99dd in sorbet::WorkerPoolImpl::multiplexJob(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::function<void ()>) /proc/self/cwd/common/concurrency/WorkerPoolImpl.cc
    #21 0x8a6408 in sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&) /proc/self/cwd/main/pipeline/pipeline.cc:932:21
    #22 0x71b6fe in LLVMFuzzerTestOneInput /proc/self/cwd/test/fuzz/fuzz_dash_e.cc:74:15
    #23 0x607c7a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:533:15
    #24 0x607605 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:455:3
    #25 0x60934e in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::Fuzzer::vector<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:745:7
    #26 0x6096b5 in fuzzer::Fuzzer::Loop(std::Fuzzer::vector<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > > > const&) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:768:3
    #27 0x6005eb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:760:6
    #28 0x625f52 in main /tmp/final/llvm.src/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #29 0x7fe60595a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #30 0x5dd028 in _start (/pay/home/jvilk/.cache/bazel/_bazel_jvilk/43032b6fe8f177634e26ef4e054799af/execroot/com_stripe_ruby_typer/bazel-out/k8-opt/bin/test/fuzz/fuzz_dash_e+0x5dd028)
```

#### Expected behavior

Segfault does not occur.

**Comment by jvilk-stripe** [comment]
I believe this bug is caused by Dmitry's recent changes to `calls.cc`. I think there are a few places where errors are `std::move` and later read.

Specifically, this seems buggy; `dispatched.main.errors` are moved into `res.main`, then `dispatched.main` is moved to `res.main`: https://github.com/sorbet/sorbet/blob/master/core/types/calls.cc#L1277-L1285

This part also makes me nervous; we move errors from `dispatched` and then continue passing `dispatched` around:
https://github.com/sorbet/sorbet/blob/master/core/types/calls.cc#L1368-L1371

The fuzzer is rather hung up on this bug, and won't get good coverage until it is fixed.

**Comment by DarkDimius** [comment]
Most likely these `move`s should be followed with `.clear` on original collection.

**Comment by aisamanra** [comment]
`.clear`ing the arrays works, and I've got a branch where I have the fix (along with a few extra `.clear`s for good measure) but entertainingly the program above also fails an assert in `test_corpus.cc`. Should I fix that too, or should I just get the fix in without a test so we can get fuzzing again? Or, alternately, @jvilk-stripe, do you have some other programs that produce this same error on hand which might not cause problems in `test_corpus.cc`?

**Comment by jvilk-stripe** [comment]
@aisamanra What assertion does it fail?

**Comment by aisamanra** [comment]
```
test/helpers/position_assertions.cc:97: Failure
Expected equality of these values:
  range.start->line
    Which is: 1
  range.end->line
    Which is: 2
Multi-line ranges are not supported at this time.
```

**Comment by jvilk-stripe** [comment]
@aisamanra You can remove that assertion. It's in a helper that pretty prints things.

**Comment by aisamanra** [comment]
Oh, actually, I don't need to here—that's just an error that comes up when the test fails, so if the test passes, it'll be okay. (It's worth rethinking in the future, though.)
