### ISSUE TITLE
`srb init` fails out of the box with ruby 2.4.6 / rails

### ISSUE THREAD

**Issue by AnIrishDuck** [sorbet/sorbet#1272]
While trying to reproduce another issue, I ran:

```
docker run -it --rm ruby:2.4.6 bash
gem install rails
apt-get update && apt-get install -y nodejs
cd /tmp
rails new sorbet
cd sorbet/
echo "gem 'sorbet', :group => :development" >> Gemfile
echo "gem 'sorbet-runtime'" >> Gemfile
bundle install
bundle exec srb init
```

This fails with:

```
[...]
Would you like to continue? [Y/n] y
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Cloning into '/root/.cache/sorbet/sorbet-typed'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 306 (delta 28), reused 49 (delta 15), pack-reused 233
Receiving objects: 100% (306/306), 92.95 KiB | 0 bytes/s, done.
Resolving deltas: 100% (109/109), done.
Generating: sorbet/rbi/gems/
/tmp/sorbet/config/application.rb:9:in `<top (required)>': Sorbet is not a module (TypeError)
	from /usr/local/bundle/gems/sorbet-0.4.4426/lib/require_everything.rb:25:in `require'
	from /usr/local/bundle/gems/sorbet-0.4.4426/lib/require_everything.rb:25:in `load_rails'
	from /usr/local/bundle/gems/sorbet-0.4.4426/lib/require_everything.rb:18:in `require_everything'
	from /usr/local/bundle/gems/sorbet-0.4.4426/lib/gem-generator-tracepoint.rb:39:in `block in main'
	from /usr/local/bundle/gems/sorbet-0.4.4426/lib/gem-generator-tracepoint/tracer.rb:70:in `trace'
	from /usr/local/bundle/gems/sorbet-0.4.4426/lib/gem-generator-tracepoint.rb:38:in `main'
	from /usr/local/bundle/gems/sorbet-0.4.4426/bin/srb-rbi:229:in `block in make_step'
	from /usr/local/bundle/gems/sorbet-0.4.4426/bin/srb-rbi:118:in `init'
	from /usr/local/bundle/gems/sorbet-0.4.4426/bin/srb-rbi:196:in `main'
	from /usr/local/bundle/gems/sorbet-0.4.4426/bin/srb-rbi:234:in `<main>'
```

**Comment by jasnow** [comment]
Try **rails new sorbet** with another name. You appear to be reusing **sorbet**.

**Comment by AnIrishDuck** [comment]
Wow ... so obvious in hindsight. Thanks for the quick feedback.
