### ISSUE TITLE
srb init adds `extend T::Sig` to `Object` and `BasicObject` inside `hidden.rbi`

### ISSUE THREAD

**Issue by clarkdave** [sorbet/sorbet#1354]
#### Input

Not reproducible on `sorbet.run`. See here for minimal reproduction: https://github.com/clarkdave/sorbet-play/tree/extend-sig-static-error

On a new project, running `srb init` adds the following entries to `hidden.rbi`:

```ruby
class Object
  extend ::T::Sig
end

class BasicObject
  extend ::T::Sig
end
```

This results in Sorbet not reporting static errors when any class uses `sig` methods without doing `extend T::Sig`. It instead fails at runtime.

#### Observed output

Using the repo above:

```
$ bundle exec srb --version
Sorbet typechecker 0.4.4485 git 889e1bf69bf55e093929cbc427334fb864f7b077 built on 2019-07-19 23:45:51 GMT with debug symbols

$ bundle exec srb tc
No errors! Great job.

$ ruby app.rb
Traceback (most recent call last):
    1: from app.rb:3:in `<main>'
app.rb:4:in `<class:Person>': undefined method `sig' for Person:Class (NoMethodError)
```

#### Expected behavior

```
srb tc                                                                                                                                                            1 ↵
app.rb:4: Method sig does not exist on T.class_of(Person) https://srb.help/7003
     4 |  sig { void }
          ^^^^^^^^^^^^

app.rb:4: Method void does not exist on T.class_of(Person) https://srb.help/7003
     4 |  sig { void }
                ^^^^
    https://github.com/sorbet/sorbet/tree/889e1bf69bf55e093929cbc427334fb864f7b077/rbi/core/kernel.rbi#L647: Did you mean: Kernel#load?
     647 |  def load(filename, arg0=T.unsafe(nil)); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

app.rb:4: This code is untyped https://srb.help/7018
     4 |  sig { void }
                ^^^^
```

The expected behaviour can be produced by either deleting the generated `hidden.rbi` or commenting out the places where `extend T::Sig` is added to `Object` and `BasicObject`

**Comment by clarkdave** [comment]
maybe related? https://github.com/sorbet/sorbet/issues/459
