### ISSUE TITLE
textDocument/hover LSP crash

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#1395]
#### Input

You can _kind of_ see this with sorbet.run with the signature never loading, but it's easier to reproduce with the VS Code extension. Essentially, copy the code below into a file and then try to hover over the parameters in the method at the end of the file. It should trigger the language server to crash. I have the `--experimental-lsp-features` flag enabled, which might be relevant.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20ActiveModel%0A%20%20module%20Validations%0A%20%20%20%20module%20HelperMethods%0A%20%20%20%20%20%20extend%20T%3A%3ASig%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20sig%20do%0A%20%20%20%20%20%20%20%20params(%0A%20%20%20%20%20%20%20%20%20%20message%3A%20T.untyped%2C%0A%20%20%20%20%20%20%20%20%20%20only_integer%3A%20T.untyped%2C%0A%20%20%20%20%20%20%20%20%20%20greater_than%3A%20T.untyped%2C%0A%20%20%20%20%20%20%20%20%20%20greater_than_or_equal_to%3A%20T.untyped%2C%0A%20%20%20%20%20%20%20%20%20%20equal_to%3A%20T.untyped%2C%0A%20%20%20%20%20%20%20%20%20%20less_than%3A%20T.untyped%2C%0A%20%20%20%20%20%20%20%20%20%20less_than_or_equal_to%3A%20T.untyped%2C%0A%20%20%20%20%20%20%20%20%20%20other_than%3A%20T.untyped%0A%20%20%20%20%20%20%20%20).returns(T.untyped)%0A%20%20%20%20%20%20end%0A%20%20%20%20%20%20def%20validates_numericality_of(message%3A%20'is%20not%20a%20number'%2C%20only_integer%3A%20false%2C%20greater_than%3A%20nil%2C%20greater_than_or_equal_to%3A%20nil%2C%20equal_to%3A%20nil%2C%20less_than%3A%20nil%2C%20less_than_or_equal_to%3A%20nil%2C%20other_than%3A%20nil)%3B%20end%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0Amodule%20ActiveModel%3A%3AValidations%3A%3AHelperMethods%20%0A%20%20def%20validates_numericality_of(%0A%20%20%20%20message%3A%20'is%20not%20a%20number'%2C%0A%20%20%20%20only_integer%3A%20false%2C%0A%20%20%20%20greater_than%3A%20nil%2C%0A%20%20%20%20greater_than_or_equal_to%3A%20nil%2C%0A%20%20%20%20equal_to%3A%20nil%2C%0A%20%20%20%20less_than%3A%20nil%2C%0A%20%20%20%20greater_than%3A%20nil%0A%20%20)%3B%20end%0Aend%0A)

```ruby
# typed: true
module ActiveModel
  module Validations
    module HelperMethods
      extend T::Sig
      
      sig do
        params(
          message: T.untyped,
          only_integer: T.untyped,
          greater_than: T.untyped,
          greater_than_or_equal_to: T.untyped,
          equal_to: T.untyped,
          less_than: T.untyped,
          less_than_or_equal_to: T.untyped,
          other_than: T.untyped
        ).returns(T.untyped)
      end
      def validates_numericality_of(message: 'is not a number', only_integer: false, greater_than: nil, greater_than_or_equal_to: nil, equal_to: nil, less_than: nil, less_than_or_equal_to: nil, other_than: nil); end
    end
  end
end

module ActiveModel::Validations::HelperMethods 
  def validates_numericality_of(
    message: 'is not a number',
    only_integer: false,
    greater_than: nil,
    greater_than_or_equal_to: nil,
    equal_to: nil,
    less_than: nil,
    greater_than: nil
  ); end
end
```

It seems to be something to do with a combination of the duplicate parameter (`greater_than` is used more than once in the second method definition) and the differing parameter count between the two method definitions.

#### Observed output

I get this log output in the VS Code Output panel:

```
Running Sorbet with the following command:
bundle exec srb tc --lsp --enable-all-experimental-lsp-features
/Users/connorshea/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4507/bin/srb: line 46:  7981 Segmentation fault: 11  "${sorbet[0]}" "${args[@]}"
[Error - 9:22:15 PM] Connection to server got closed. Server will not be restarted.
[Error - 9:22:15 PM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-jsonrpc/lib/main.js:876:25)
    at Object.dispose (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-languageclient/lib/client.js:57:35)
    at LanguageClient.handleConnectionClosed (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-languageclient/lib/client.js:2036:42)
    at LanguageClient.handleConnectionClosed (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-languageclient/lib/main.js:127:15)
    at closeHandler (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-languageclient/lib/client.js:2023:18)
    at CallbackList.invoke (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at closeHandler (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-jsonrpc/lib/main.js:226:26)
    at CallbackList.invoke (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at StreamMessageReader.fireClose (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at Socket.listen.readable.on (/Users/connorshea/.vscode/extensions/stripe.stripe-vscode-integration-0.2.0/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
    at Socket.emit (events.js:187:15)
    at Pipe.Socket._destroy._handle.close (net.js:606:12)
```

#### Expected behavior

It won't crash the language server.

------

VS Code Sorbet extension: 0.2.0
Sorbet: 0.4.4507 (it also occurred with 0.4.4405, if that's useful info at all)
Ruby: 2.6.2

**Comment by connorshea** [comment]
Here's the smallest reproduction case I can get:

```ruby
# typed: true
module Test
  extend T::Sig
  
  sig { params(bar: T.untyped).returns(T.untyped) }
  def foo(bar: nil); end
end

module Test
  def foo(bar: nil, bar: nil); end
end
```

**Comment by connorshea** [comment]
This might be a dupe of #886?

It actually doesn't seem to even need the first method/sig at all:

```ruby
# typed: true
module Test
  def foo(bar: nil, bar: nil); end
end
```

**Comment by DarkDimius** [comment]
https://github.com/sorbet/sorbet/pull/1326 might be a fix for it

**Comment by jvilk-stripe** [comment]
I confirmed that this is still an issue.

On the line with:

```
response->result =
                make_unique<Hover>(formatRubyCode(clientHoverMarkupKind, resp->getRetType()->showWithMoreInfo(*gs)));
```

`getRetType()` is an invalid `Type *` pointer.

**Comment by antoniodejesusochoasolano** [comment]
Sorry this is a little of topic but does this mean there's a Sorbet VS Code extension we can use? At least a beta one?

>VS Code Sorbet extension: 0.2.0

**Comment by jvilk-stripe** [comment]
This issue is fixed; we now guard against a null `getRetType()`. The above crashers work.

>does this mean there's a Sorbet VS Code extension we can use? At least a beta one?

Not yet! :)
