### ISSUE TITLE
srb rbi gems fails on a Rails app running 6.0.0.rc2

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#1417]
#### Input

I've got my Rails app working fine with Rails 5.2.3, but upon upgrading to Rails 6.0.0.rc2 `srb rbi update` (specifically the `srb rbi gems` stage) fails.

#### Observed output

```
connorshea$ bundle exec srb rbi update

👋 Hey there!

This script will get this project ready to use with Sorbet by creating a
sorbet/ folder for your project. It will contain:

- a config file
- a bunch of 'RBI files'

RBI stands for 'Ruby Interface'; these files define classes, methods, and
constants that exist, but which Sorbet doesn't always know about.

⚠️  Heads up:

To set up your project, this script will take two potentially destructive
actions:

1.  It will require every file in your project. Specifically, every script in
    your project will be run, unless that script checks if __FILE__ == $PROGRAM_NAME
    before running any code, or has the magic comment # typed: ignore in it.

2.  It will add a comment to the top of every file (like # typed: false or
    # typed: true, depending on how many errors were found in that file.)

❔ Would you like to continue? [Y/n] y
Generating: sorbet/config
Reusing existing config file: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
Traceback (most recent call last):
	10: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/bin/srb-rbi:234:in `<main>'
	 9: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/bin/srb-rbi:196:in `main'
	 8: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/bin/srb-rbi:118:in `init'
	 7: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/bin/srb-rbi:229:in `block in make_step'
	 6: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/lib/gem-generator-tracepoint.rb:38:in `main'
	 5: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/lib/gem-generator-tracepoint/tracer.rb:70:in `trace'
	 4: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/lib/gem-generator-tracepoint.rb:39:in `block in main'
	 3: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/lib/require_everything.rb:20:in `require_everything'
	 2: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/lib/require_everything.rb:44:in `require_all_files'
	 1: from /Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4524/lib/require_everything.rb:114:in `excluded_rails_files'
/Users/connorshea/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0.rc2/lib/rails/engine.rb:711:in `_all_load_paths': wrong number of arguments (given 0, expected 1) (ArgumentError)
```

#### Expected behavior

It wouldn't throw an error.

#### Additional information

In 5.2.3, `_all_load_paths` was defined without a parameter: https://github.com/rails/rails/blob/v5.2.3/railties/lib/rails/engine.rb#L701

In 6.0.0.rc2, it has a parameter: https://github.com/rails/rails/blob/v6.0.0.rc2/railties/lib/rails/engine.rb#L711

The change occurred with https://github.com/rails/rails/commit/668673f7793be1ce318a32bb622ed411029d00a9

#1009 should fix this issue.

**Comment by mikker** [comment]
I can confirm this error.

**Comment by edwinthinks** [comment]
@connorshea the PR has been merged :). 🍾

**Comment by jasnow** [comment]
Can this issue be closed now?

**Comment by connorshea** [comment]
Yup, this can be closed now.
