### ISSUE TITLE
srb init fails with ExitCalledError

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [sorbet/sorbet#1476]
This is related to https://github.com/sorbet/sorbet/issues/949#issuecomment-517521488
The error in that ticket was fixed but there is now a new error with the same Gemfile.

#### Input

```
$ cat .ruby-version
2.3.1
$ cat Gemfile
source 'https://rubygems.org'

gem 'rails', '3.2.22.5'
gem 'sorbet'
gem 'sorbet-runtime'
```

Using versions:
1. sorbet (0.4.4564)
2. sorbet-runtime (0.4.4564)
3. sorbet-static (0.4.4564-universal-darwin-14)

#### Observed output

```
$ bundle exec srb init

👋 Hey there!

This script will get this project ready to use with Sorbet by creating a
sorbet/ folder for your project. It will contain:

- a config file
- a bunch of 'RBI files'

RBI stands for 'Ruby Interface'; these files define classes, methods, and
constants that exist, but which Sorbet doesn't always know about.

⚠️  Heads up:

To set up your project, this script will take two potentially destructive
actions:

1.  It will require every file in your project. Specifically, every script in
    your project will be run, unless that script checks if __FILE__ == $PROGRAM_NAME
    before running any code, or has the magic comment # typed: ignore in it.

2.  It will add a comment to the top of every file (like # typed: false or
    # typed: true, depending on how many errors were found in that file.)

❔ Would you like to continue? [Y/n]
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 319 (delta 43), reused 64 (delta 39), pack-reused 249
Receiving objects: 100% (319/319), 76.42 KiB | 2.32 MiB/s, done.
Resolving deltas: 100% (134/134), completed with 10 local objects.
From github.com:sorbet/sorbet-typed
   9280cab..ac27382  master     -> origin/master
Generating: sorbet/rbi/gems/
Generating: sorbet/rbi/hidden-definitions/
Requiring all of your code
Naming all Modules
Naming ObjectGot NameError when trying to get nested name Object::fatal_
Naming ActionDispatchGot LoadError when trying to get nested name ActionDispatch::Integration
Got LoadError when trying to get nested name ActionDispatch::IntegrationTest
Specify ruby-prof as application's dependency in Gemfile to run benchmarks.
Kernel#exit was called while requiring ruby source files
/Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/require_everything.rb:91:in `block in patch_kernel': ExitCalledError (ExitCalledError)
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/testing/performance/ruby.rb:5:in `rescue in <top (required)>'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/testing/performance/ruby.rb:1:in `<top (required)>'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/testing/performance.rb:311:in `<top (required)>'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-3.2.22.5/lib/action_dispatch/testing/performance_test.rb:1:in `<top (required)>'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/real_stdlib.rb:77:in `const_get'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/real_stdlib.rb:77:in `call'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/real_stdlib.rb:77:in `real_const_get'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/constant_cache.rb:137:in `block in dfs_module'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/constant_cache.rb:125:in `each'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/constant_cache.rb:125:in `dfs_module'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/constant_cache.rb:191:in `block in dfs_module'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/constant_cache.rb:190:in `each'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/constant_cache.rb:190:in `dfs_module'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/constant_cache.rb:70:in `initialize'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/hidden-definition-finder.rb:68:in `constant_cache'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/hidden-definition-finder.rb:75:in `all_modules_and_aliases'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/hidden-definition-finder.rb:44:in `main'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/lib/hidden-definition-finder.rb:38:in `main'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/bin/srb-rbi:229:in `block in make_step'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/bin/srb-rbi:121:in `init'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/bin/srb-rbi:196:in `main'
	from /Users/thomas/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sorbet-0.4.4564/bin/srb-rbi:234:in `<main>'
```

#### Expected behavior

`bundle exec srb init` succeeds

**Comment by DarkDimius** [comment]
It means that some of your code calls `Kernel.exit`.
This stops us from fully loading your application to discover all metaprogramming. 
Making it not call `Kernel.exit` on code load is necessary for `srb init` to succeed.
