### ISSUE TITLE
Rspec method expect twice broken

### ISSUE THREAD

**Issue by warhammerkid** [sorbet/sorbet#1481]
#### Input

```ruby
# typed: true

require 'rspec'
require 'sorbet-runtime'

module StaticModule
  extend T::Sig
  sig { void }
  def self.do_it; end
end

describe 'sorbet' do
  it 'handles multiple call expectations' do
    expect(StaticModule).to receive(:do_it).twice.and_call_original
    StaticModule.do_it
    StaticModule.do_it
  end

  it 'resets properly' do
    StaticModule.do_it
  end
end
```

#### Observed output

```
> rspec testcase_spec.rb
...
Failures:

  1) sorbet handles multiple call expectations
     Failure/Error: expect(StaticModule).to receive(:do_it).twice.and_call_original

       (StaticModule).do_it(*(any args))
           expected: 2 times with any arguments
           received: 1 time with any arguments
     # ./testcase_spec.rb:14:in `block (2 levels) in <top (required)>'

  2) sorbet resets properly
     Failure/Error: StaticModule.do_it

     RuntimeError:
       `sig` not present for method `do_it` but you're trying to run it anyways. This should only be executed if you used `alias_method` to grab a handle to a method after `sig`ing it, but that clearly isn't what you are doing. Maybe look to see if an exception was thrown in your `sig` lambda or somehow else your `sig` wasn't actually applied to the method. Contact #dev-productivity if you're really stuck.
     # ./testcase_spec.rb:20:in `block (2 levels) in <top (required)>'
```

#### Environment

**Ruby:** 2.4
**Rspec:** 3.8.2
**Sorbet:** 0.4.4564

#### Expected behavior

The first test should recognize that the method has been called twice and the second test should not be broken because of whatever happened in the first test. If the `sig` is commented out then both tests pass.

**Comment by warhammerkid** [comment]
It appears as though instance methods are working just fine:

```ruby
# typed: true

require 'rspec'
require 'sorbet-runtime'

module StaticModule
  extend T::Sig
  sig { void }
  def self.do_it; end
end

class NormalClass
  extend T::Sig
  sig { void }
  def do_it; end
end

describe 'sorbet' do
  describe StaticModule do
    it 'handles multiple call expectations' do
      expect(StaticModule).to receive(:do_it).twice.and_call_original
      StaticModule.do_it
      StaticModule.do_it
    end

    it 'resets properly' do
      StaticModule.do_it
    end
  end

  describe NormalClass do
    subject { NormalClass.new }

    it 'handles multiple call expectations' do
      expect(subject).to receive(:do_it).twice.and_call_original
      subject.do_it
      subject.do_it
    end

    it 'resets properly' do
      subject.do_it
    end
  end
end
```

In this case neither of the tests for `NormalClass` fail.

**Comment by ric2b** [comment]
Also running into this, multiple `allow()`'s on a static method with Sorbet signatures cause subsequent tests to fail with the message:
> `sig` not present for method `x` but you're trying to run it anyways. (...)

**Comment by jduarte** [comment]
Hey guys was this ever fixed or looked at? We're hitting the same issue as well

**Comment by jduarte** [comment]
Hey @jez @froydnj by any chance have you got through this issue or have a workaround? Thanks in advance 🙏

**Comment by rex-remind101** [comment]
i'm still running into this @jduarte

**Comment by iMacTia** [comment]
Unfortunately I don't have time right now to open a proper PR with test coverage, but I stumbled upon this today as well and I managed to get a fix for this based on [this other fix](https://github.com/sorbet/sorbet/pull/581/files):

```ruby
module T
  module CompatibilityPatches
    module ReceiveExtensions
      def setup_mock_proxy_method_substitute(subject, method, block)
        method_def = begin
          subject.method(@message)
        rescue
          nil
        end
        T::Private::Methods.maybe_run_sig_block_for_method(method_def) if method_def
        super
      end
    end
    ::RSpec::Mocks::Matchers::Receive.prepend(ReceiveExtensions)
  end
end
```

This basically works by calling `T::Private::Methods.maybe_run_sig_block_for_method` on the method targeted by `allow(...).to receive(...)` before RSpec wraps the method into a spy.

@ric2b @jduarte @rex-remind101 could you please give this a try and if it also works for you then maybe open a PR with some test coverage 😄? It would be much appreciated and everyone would benefit.
