### ISSUE TITLE
not compiling on openSUSE-LEAP-15.1

### ISSUE THREAD

**Issue by kolAflash** [sorbet/sorbet#1486]
OS: openSUSE-LEAP-15.1

Compiling didn't worked with bazel-0.22 by openSUSE-15.1 and with the current bazel from here: https://github.com/bazelbuild/bazel/releases/download/0.28.1/bazel-0.28.1-linux-x86_64
I always got this error:
`ERROR: Unrecognized option: --incompatible_package_name_is_a_function=false`
There's a bug report at bazel which says, that this option has been removed in bazel>=0.22.
https://github.com/bazelbuild/bazel/issues/7295

--

So I tried: https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel-0.21.0-linux-x86_64
And I also tried it one more time with bazel-0.22 and bazel-0.28.1, after commenting out this line in `.bazelrc`:
https://github.com/sorbet/sorbet/blob/a67fb84c40af292048272db8c229e5bb2b8cca08/.bazelrc#L7
Commenting out that line or using bazel-0.21 successfully workarounded that error!

--

Sadly I just ran into another error (same for bazel-0.21, bazel-0.22 and bazel-0.28.1).
```
ERROR: /home/user/Sorbet/build/sorbet/main/BUILD:9:1: every rule of type cc_binary implicitly depends upon the target '@llvm_toolchain//:toolchain', but this target could not be found because of: no such package '@llvm_toolchain//': Traceback (most recent call last):
        File "/home/user/.cache/bazel/_bazel_user/cdcf9e782084ebba1bd09c1d7b94d687/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 87
                _download_llvm_preconfigured(rctx)
        File "/home/user/.cache/bazel/_bazel_user/cdcf9e782084ebba1bd09c1d7b94d687/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 78, in _download_llvm_preconfigured
                fail(("Failed to detect host OS versi...)))
Failed to detect host OS version: 

Unsupported linux distribution and version: opensuse-leap, 15.1
ERROR: Analysis of target '//main:sorbet' failed; build aborted: no such package '@llvm_toolchain//': Traceback (most recent call last):
        File "/home/user/.cache/bazel/_bazel_user/cdcf9e782084ebba1bd09c1d7b94d687/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 87
                _download_llvm_preconfigured(rctx)
        File "/home/user/.cache/bazel/_bazel_user/cdcf9e782084ebba1bd09c1d7b94d687/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 78, in _download_llvm_preconfigured
                fail(("Failed to detect host OS versi...)))
Failed to detect host OS version: 

Unsupported linux distribution and version: opensuse-leap, 15.1
INFO: Elapsed time: 69.512s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (18 packages loaded, 96 targets configured)
    Fetching @llvm_toolchain; fetching
```

I got LLVM and Clang installed.
```
$ rpm -qa '*llvm|LLVM|clang*'
llvm7-LTO-devel-7.0.1-lp151.2.3.1.x86_64
llvm7-devel-7.0.1-lp151.2.3.1.x86_64
llvm7-polly-7.0.1-lp151.2.3.1.x86_64
llvm-7.0.1-lp151.1.1.x86_64
llvm7-7.0.1-lp151.2.3.1.x86_64
libLLVM7-7.0.1-lp151.2.3.1.x86_64
clang-checker-7.0.1-lp151.1.1.x86_64
clang7-7.0.1-lp151.2.3.1.x86_64
llvm-devel-7.0.1-lp151.1.1.x86_64
libLLVM7-32bit-7.0.1-lp151.2.3.1.x86_64
llvm7-polly-devel-7.0.1-lp151.2.3.1.x86_64
libclang7-7.0.1-lp151.2.3.1.x86_64
clang7-checker-7.0.1-lp151.2.3.1.x86_64
llvm7-gold-7.0.1-lp151.2.3.1.x86_64
llvm-gold-7.0.1-lp151.1.1.x86_64
```

**Comment by DarkDimius** [comment]
https://stackoverflow.com/questions/57384896/how-to-build-sorbet-on-centos-7-missing-llvm-toolchain/57388212#57388212
