### ISSUE TITLE
sorbet-static has "Illegal instruction" on AMD Phenom II

### ISSUE THREAD

**Issue by kolAflash** [sorbet/sorbet#1487]
CPU: AMD Phenom(tm) II X4 955 Processor (model 4, stepping 2)
OS: openSUSE-LEAP-15.1

```
$ gem install --user sorbet-static
$ ~/.gem/ruby/2.5.0/gems/sorbet-static-0.4.4573-x86_64-linux/libexec/sorbet
Illegal instruction
```

I guess this is somehow caused, by how the binaries for https://rubygems.org/gems/sorbet are being build.

I tried to compile sorbet-static myself, but that failed due to some bazel errors. See: #1486

**Comment by DarkDimius** [comment]
Sorbet by default gets compiled with support for recent CPU instructions.
The following line needs to be modified to make it stop:
https://github.com/sorbet/sorbet/blob/703e91a3ea002ffd7c9a700396449658f8a04209/.bazelrc#L29

**Comment by DarkDimius** [comment]
As this is the only time we've seen it mentioned, we're not going to invest effort into this now.

if you `dmesg` it should tell you what instruction wasn't supported, I'd be curious to know which one you ran into.

**Comment by kolAflash** [comment]
> [...]
> if you `dmesg` it should tell you what instruction wasn't supported, I'd be curious to know which one you ran into.

dmesg output:
`trap invalid opcode ip:459978 sp:7ffd19f5be80 error:0 in sorbet[3a0000+8ff000]`

If there's no other option, could you consider providing builds without `--copt=-march=sandybridge`?

**Comment by fabioperrella** [comment]
Hi! I'm having a similar issue in Ubuntu 16.04:

```
$ bundle exec srb typecheck -e 'puts "Hello, world!"'
/home/fabio/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4761/bin/srb: line 46: 24128 Illegal instruction     (core dumped) "${sorbet[0]}" "${args[@]}"
```

```
$ dmesg | tail -n 1
[ 2729.592603] traps: sorbet[24128] trap invalid opcode ip:504d68 sp:7fff6de8ff80 error:0 in sorbet[44a000+920000]
```

I tried with ruby 2.6.3 and I got the same error.

**Comment by incazteca** [comment]
Hi,

Just wanted to document that I've also been affected by this issue:
```
franco@helper:~/development_zone/box_accounting_utilities (sorbet_add)$ be srb typecheck -e 'puts "Hello"'
/home/franco/.gem/gems/sorbet-0.4.4996/bin/srb: line 46: 29955 Illegal instruction     (core dumped) "${sorbet}" "${args[@]}"
franco@helper:~/development_zone/box_accounting_utilities (sorbet_add)$ dmesg | tail -n 1
[24907.213126] traps: sorbet[29955] trap invalid opcode ip:51dc48 sp:7ffd3da496a0 error:0 in sorbet[464000+941000]
```
Ruby version and hardware info:
```
franco@helper:~/development_zone/box_accounting_utilities (sorbet_add)$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
franco@helper:~/development_zone/box_accounting_utilities (sorbet_add)$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               26
Model name:          Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz
Stepping:            5
CPU MHz:             1652.972
CPU max MHz:         2794.0000
CPU min MHz:         1596.0000
BogoMIPS:            5667.46
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida flush_l1d
```

**Comment by reedlaw** [comment]
I was able to successfully compile and run on an Intel Xeon L5520 using this option:
```
  build --copt=-march=native
```
Now that I have a working binary, I'm not sure if there's a better way to get it running in my project other than dropping it into `~/.gem/ruby/2.6.0/gems/sorbet-static-0.4.5072-x86_64-linux/libexec/sorbet`.

**Comment by L-as** [comment]
This is because sorbet assumes AVX support, which while quite old, isn't actually supported on all new processors. I am using an Intel Atom x5-Z8350 CPU from 2016 with no support for AVX and can as a result not run Sorbet.
The exact instruction that sorbet tries to run for me at least is vxorps xmm0, xmm0, xmm0.

**Comment by L-as** [comment]
Perhaps a fat binary or something could be of use here? While this specific problem is just not supporting AVX, sorbet is assuming that users are using an x86-64 processor, which makes it hard to use on any non-standard desktop hardware, such as ARM or PPC CPUs. I wonder if it could be compiled as a wasm executable trivially.

**Comment by DarkDimius** [comment]
> I wonder if it could be compiled as a wasm executable trivially.

Yes, we do it as part of our CI. The resulting executable doesn't use threads/caches and is ~30% slower in single threaded mode.

**Comment by L-as** [comment]
@DarkDimius is there any documentation on how to use the WASM version?

**Comment by gosukiwi** [comment]
I'm having the same issue on an old MacBook 5,2 running Ubuntu 18.04. The processor is `Intel(R) Core(TM)2 Duo CPU     P7450  @ 2.13GHz`.

**Comment by ekampp** [comment]
I'm getting something similar when running it in docker using the `linux/amd64` platform.

> /usr/local/bundle/gems/sorbet-0.5.10974/bin/srb: line 46:   362 Illegal instruction     "${sorbet}" "${args[@]}"

**Comment by andredriem** [comment]
> I'm getting something similar when running it in docker using the `linux/amd64` platform. It works great when running it natively on my mac.
> 
> > /usr/local/bundle/gems/sorbet-0.5.10974/bin/srb: line 46:   362 Illegal instruction     "${sorbet}" "${args[@]}"

I was having the same issue as you on my project on apple silicon + docker. But when trying to recreate to test it on a clean docker container I couldn't replicate the issue.
Running this command resulted in no errors:
`
docker run --platform linux/amd64 -it ruby:3.2.2 bash
echo "
source 'https://rubygems.org'

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => :development
" > Gemfile

bundle install
bundle exec ruby -e 'puts(require "sorbet-runtime")'
`

After digging up my dockerfile I notice some commands to cleanup some gems artifacts in the directory '/usr/local/bundle/gems/' . I commented them out from the dockerfile and Sorbet started working normally.

**Comment by edgaruriel** [comment]
Hi @andredriem, can you add the commands to cleanup the gems? I have the same error with M2 + docker and platform `linux/adm64`. I following the commands and additional run sorbet init but I get the same error

**Comment by andredriem** [comment]
> Hi @andredriem, can you add the commands to cleanup the gems? I have the same error with M2 + docker and platform `linux/adm64`. I following the commands and additional run sorbet init but I get the same error
Sure, in my situation we did some effort some time ago to reduce our container size image and cleanup any gem artifacts left behind. Turns out sorbet needs some of those artifacts to function proper. 


I had this in my local Dockerfile, i commented them out and sorbet run flawlessly.

```
    # Clean up useless gem stuff 
    find /usr/local/bundle/gems/* | grep -P '\.o$'| xargs -I{} rm {}
    find /usr/local/bundle/gems/* | grep -P '\.c$'| xargs -I{} rm {}
    rm -rf /usr/local/bundle/cache/*.gem
    rm -rf app/tmp/cache/ vendor/assets spec
```

**Comment by evsasse** [comment]
> I was having the same issue as you on my project on apple silicon + docker. But when trying to recreate to test it on a clean docker container I couldn't replicate the issue. Running this command resulted in no errors:
> 
> ```
> docker run --platform linux/amd64 -it ruby:3.2.2 bash
> echo "
> source 'https://rubygems.org'
> 
> gem 'sorbet', :group => :development
> gem 'sorbet-runtime'
> gem 'tapioca', require: false, :group => :development
> " > Gemfile
> 
> bundle install
> bundle exec ruby -e 'puts(require "sorbet-runtime")'
> ```

Trying this here, but replacing `bundle exec ruby -e 'puts(require "sorbet-runtime")'` with `bundle exec srb init`. I still get the same problem. 😕 
> /usr/local/bundle/gems/sorbet-0.5.11068/bin/srb: line 46:   261 Illegal instruction     "${sorbet}" "${args[@]}"

**Comment by andredriem** [comment]
Found the problem, I managed 

> > I was having the same issue as you on my project on apple silicon + docker. But when trying to recreate to test it on a clean docker container I couldn't replicate the issue. Running this command resulted in no errors:
> > ```
> > docker run --platform linux/amd64 -it ruby:3.2.2 bash
> > echo "
> > source 'https://rubygems.org'
> > 
> > gem 'sorbet', :group => :development
> > gem 'sorbet-runtime'
> > gem 'tapioca', require: false, :group => :development
> > " > Gemfile
> > 
> > bundle install
> > bundle exec ruby -e 'puts(require "sorbet-runtime")'
> > ```
> 
> Trying this here, but replacing `bundle exec ruby -e 'puts(require "sorbet-runtime")'` with `bundle exec srb init`. I still get the same problem. 😕
> 
> > /usr/local/bundle/gems/sorbet-0.5.11068/bin/srb: line 46:   261 Illegal instruction     "${sorbet}" "${args[@]}"

I managed to reproduce you problem and the binary is indeed not working.  I managed to get it working by compiling the Linux distribution with the flag  "--copt=-march=x86-64" instead of "--copt=-march=sandybridge". This is concerning because it seems that the gem in it's current state is unusable in MacBooks with Docker containers on x86-64 architecture.

I don't know if this flag is important to this gem performance, but the only solution I see here is compiling the binary ourselves or convincing the repo mainteners to compile the binary with  "--copt=-march=x86-64".

**Comment by notahat** [comment]
Yep, can confirm this. Making the docker image as described in the previous comment, and then running `bundle exec srb init` ends in:

```
/usr/local/bundle/gems/sorbet-0.5.11141/bin/srb: line 46:   255 Illegal instruction     "${sorbet}" "${args[@]}"
/usr/local/lib/ruby/3.2.0/json/common.rb:216:in `parse': unexpected token at '' (JSON::ParserError)
	from /usr/local/lib/ruby/3.2.0/json/common.rb:216:in `parse'
	from /usr/local/bundle/gems/sorbet-0.5.11141/lib/require_everything.rb:134:in `rb_file_paths'
	from /usr/local/bundle/gems/sorbet-0.5.11141/lib/require_everything.rb:46:in `require_all_files'
	from /usr/local/bundle/gems/sorbet-0.5.11141/lib/require_everything.rb:20:in `require_everything'
	from /usr/local/bundle/gems/sorbet-0.5.11141/lib/gem-generator-tracepoint.rb:39:in `block in main'
	from /usr/local/bundle/gems/sorbet-0.5.11141/lib/gem-generator-tracepoint/tracer.rb:80:in `trace'
	from /usr/local/bundle/gems/sorbet-0.5.11141/lib/gem-generator-tracepoint.rb:38:in `main'
	from /usr/local/bundle/gems/sorbet-0.5.11141/bin/srb-rbi:251:in `block in make_step'
	from /usr/local/bundle/gems/sorbet-0.5.11141/bin/srb-rbi:135:in `init'
	from /usr/local/bundle/gems/sorbet-0.5.11141/bin/srb-rbi:215:in `main'
	from /usr/local/bundle/gems/sorbet-0.5.11141/bin/srb-rbi:256:in `<main>'
```

**Comment by TETRA2000** [comment]
I made a small repo for making it easier to build Sorbet binaries which doesn't use AVX instructions.
https://github.com/TETRA2000/sorbet_builder
