### ISSUE TITLE
Missing error: sig params omits block parameter, method def params include it

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#1724]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Arequire%20'sorbet-runtime'%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20self.foo(%26blk)%0A%20%20end%0Aend%0A%0AA.foo)

```ruby
# typed: strict
require 'sorbet-runtime'

class A
  extend T::Sig
  sig {void}
  def self.foo(&blk)
  end
end

A.foo
```

#### Observed output

```
A.foo
No errors! Great job.
```

#### Expected behavior

The runtime raises an exception when this code runs:

```
❯ ruby editor.rb
Traceback (most recent call last):
        8: from editor.rb:11:in `<main>'
        7: from /Users/jez/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4698/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
        6: from /Users/jez/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4698/lib/types/private/methods/_methods.rb:348:in `run_sig_block_for_method'
        5: from /Users/jez/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4698/lib/types/private/methods/_methods.rb:364:in `run_sig_block_for_key'
        4: from /Users/jez/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4698/lib/types/private/methods/_methods.rb:200:in `block in _on_method_added'
        3: from /Users/jez/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4698/lib/types/private/methods/_methods.rb:268:in `run_sig'
        2: from /Users/jez/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4698/lib/types/private/methods/_methods.rb:295:in `build_sig'
        1: from /Users/jez/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4698/lib/types/private/methods/_methods.rb:295:in `new'
/Users/jez/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.4698/lib/types/private/methods/signature.rb:65:in `initialize': The declaration for `foo` is missing parameter(s): blk (RuntimeError)
```

- - -

**Comment by neilparikh** [comment]
Fixed now:
```
editor.rb:7: Malformed sig. Type not specified for argument blk https://srb.help/5003
     7 |  def self.foo(&blk)
                        ^^^
    editor.rb:6: Signature
     6 |  sig {void}
```
