### ISSUE TITLE
NameError (uninitialized constant XTJ::Tags::XMLTag::T) when requiring my newly created ruby gem

### ISSUE THREAD

**Issue by grzegorz-jakubiak** [sorbet/sorbet#1745]
Hi there,
I've created my first ruby gem and wanted to use `sorbet` for type checking. It work as expected when I run the specs but unfortunately it fails to load when I've gem-installed it and want to require it. The error I'm currently getting is:
```
require 'xtj'
Traceback (most recent call last):
       13: from /home/gregg/.rvm/rubies/ruby-2.6.4/bin/irb:23:in `<main>'
       12: from /home/gregg/.rvm/rubies/ruby-2.6.4/bin/irb:23:in `load'
       11: from /home/gregg/.rvm/rubies/ruby-2.6.4/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       10: from (irb):2
        9: from /home/gregg/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        8: from /home/gregg/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        7: from /home/gregg/.rvm/rubies/ruby-2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
        6: from /home/gregg/.rvm/gems/ruby-2.6.4/gems/xtj-0.1.0/lib/xtj.rb:5:in `<top (required)>'
        5: from /home/gregg/.rvm/gems/ruby-2.6.4/gems/xtj-0.1.0/lib/xtj.rb:5:in `require_relative'
        4: from /home/gregg/.rvm/gems/ruby-2.6.4/gems/xtj-0.1.0/lib/xtj/tags/xml_tag.rb:4:in `<top (required)>'
        3: from /home/gregg/.rvm/gems/ruby-2.6.4/gems/xtj-0.1.0/lib/xtj/tags/xml_tag.rb:5:in `<module:XTJ>'
        2: from /home/gregg/.rvm/gems/ruby-2.6.4/gems/xtj-0.1.0/lib/xtj/tags/xml_tag.rb:6:in `<module:Tags>'
        1: from /home/gregg/.rvm/gems/ruby-2.6.4/gems/xtj-0.1.0/lib/xtj/tags/xml_tag.rb:7:in `<class:XMLTag>'
NameError (uninitialized constant XTJ::Tags::XMLTag::T)
```

and this happens when I launch `irb` and call `require 'xtj'`.
Source code here: https://github.com/grzegorz-jakubiak/xtj

Any ideas how I can fix that?

**Comment by jez** [comment]
When publishing a gem, you should never put your dependencies in the `Gemfile` and always put them in the `*.gemspec` file. When you installed your gem, it didn't know to also install the `sorbet-runtime` gem dependency. It would know this if it was listed in your `*.gemspec` as a runtime dependency:

https://guides.rubygems.org/specification-reference/#add_runtime_dependency

**Comment by jez** [comment]
https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

**Comment by grzegorz-jakubiak** [comment]
@jez thanks I tried it locally but it didn't help find updated `gemspec` below:
```
lib = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'xtj/version'

Gem::Specification.new do |spec|
  spec.name          = 'xtj'
  spec.version       = XTJ::VERSION
  spec.authors       = ['Grzegorz Jakubiak']
  spec.email         = ['grzegorz.jakubiak@outlook.com']

  spec.summary       = 'Allows you to parse XML documents into Ruby Hash or JSON'
  spec.description   = spec.summary
  spec.homepage      = 'https://github.com/grzegorz-jakubiak/xtj'
  spec.license       = 'MIT'
  spec.required_ruby_version = '>=2.5'

  spec.files = Dir.chdir(File.expand_path(__dir__)) do
    `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  end
  spec.bindir        = 'exe'
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ['lib']

  spec.add_development_dependency 'bundler', '~> 1.17'
  spec.add_development_dependency 'rake', '~> 10.0'
  spec.add_development_dependency 'rspec', '~> 3.0'
  spec.add_runtime_dependency 'sorbet'
  spec.add_runtime_dependency 'sorbet-runtime'
end
```
I also tried with `development_dependencies` and updated the gem to `0.1.1` with that specify but it keeps giving me:

```
7: from (irb):1:in `require_relative'
        6: from /Users/grzegorz/Documents/xtj/lib/xtj.rb:5:in `<top (required)>'
        5: from /Users/grzegorz/Documents/xtj/lib/xtj.rb:5:in `require_relative'
        4: from /Users/grzegorz/Documents/xtj/lib/xtj/tags/xml_tag.rb:4:in `<top (required)>'
        3: from /Users/grzegorz/Documents/xtj/lib/xtj/tags/xml_tag.rb:5:in `<module:XTJ>'
        2: from /Users/grzegorz/Documents/xtj/lib/xtj/tags/xml_tag.rb:6:in `<module:Tags>'
        1: from /Users/grzegorz/Documents/xtj/lib/xtj/tags/xml_tag.rb:7:in `<class:XMLTag>'
NameError (uninitialized constant XTJ::Tags::XMLTag::T)
```

**Comment by grzegorz-jakubiak** [comment]
fixed it by requiring sorbet-runtime, sorry for the issue
