### ISSUE TITLE
'srb init' getting "undefined method `_all_load_paths' for nil:NilClass" error

### ISSUE THREAD

**Issue by jasnow** [sorbet/sorbet#2066]
#### Input

 1. Run "git clone https://github.com/jasnow/rails_app6edge".
 2. Run "bundle"
 3. Run "srb init" then "y" and you get:

#### Observed output
```
Generating: sorbet/config
Reusing existing config file: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
/Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/lib/require_everything.rb:160:in `rails_load_paths': undefined method `_all_load_paths' for nil:NilClass (NoMethodError)
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/lib/require_everything.rb:142:in `excluded_rails_files'
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/lib/require_everything.rb:44:in `require_all_files'
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/lib/require_everything.rb:20:in `require_everything'
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/lib/gem-generator-tracepoint.rb:39:in `block in main'
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/lib/gem-generator-tracepoint/tracer.rb:70:in `trace'
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/lib/gem-generator-tracepoint.rb:38:in `main'
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/bin/srb-rbi:232:in `block in make_step'
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/bin/srb-rbi:118:in `init'
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/bin/srb-rbi:196:in `main'
	from /Users/macbookpro/.rvm/gems/ruby-2.6.5@ruby2.6-rails6.1/gems/sorbet-0.4.4957/bin/srb-rbi:237:in `<main>'
Generating: sorbet/rbi/gems/
```

#### Expected behavior

"srb init" finish cleanly.

#### Versions

 * Sorbet: 0.4.4957
 * Ruby: 2.6.5
 * Rails: 6.1.0.alpha

**Comment by jasnow** [comment]
Conclusion: Has something to do with autoloading/zeitwerk/recent rails 6.0.x changes

@manhhung741 , @rafaelfranca : Can I add this conditional around lines 142-144 in /Users/USER/.rvm/gems/ruby-2.6.5@ ruby2.6-rails6.1/gems/sorbet-0.4.4969/lib/require_everything.rb as follows:
```
if Gem::Version.new(Object.const_get(:Rails).version) < Gem::Version.new('6.0.0.rc2')
  self.rails_load_paths.each do |path|
    excluded_paths += Dir.glob("#{path}/**/*.rb")
  end
end
```
If I do, the above undefined method goes away.
Also if this is correct, the load_paths method probably needs changes too.
Thanks.

**Comment by jasnow** [comment]
Here is the commit for the above code: https://github.com/sorbet/sorbet/commit/40adde4f0025ddf78148b94201aaa98b87a3c0e5

**Comment by jasnow** [comment]
@edwinthinks - Can you look at this issue? It is related to your commit's code https://github.com/sorbet/sorbet/commit/40adde4f0025ddf78148b94201aaa98b87a3c0e5 ?

**Comment by jasnow** [comment]
Found today:https://github.com/rails/rails/commit/43863bfc5716d8bd2f5be59920239aee1470465a

**Comment by jasnow** [comment]
Guess you are not going to work on this issue, so I'm going to close it.
