### ISSUE TITLE
Race condition in `_methods.rb`

### ISSUE THREAD

**Issue by fzakaria** [sorbet/sorbet#2316]
I encountered race conditions when running in _JRuby_ where the following code would cause `_methods.rb` to raise an exception. The part of the code that replaces / wraps the methods with the **sig** is not thread safe (the action can occur on separate threads)

#### Input

```ruby
# typed: true

require 'sorbet-runtime'

class A
  extend T::Sig

  sig {params(a: Integer).void}
  def initialize(a)
  end

  def hello_world
    puts "Hello world"
  end

end

a = Class.new(A) do

  end.new(1)

a.hello_world


a = Class.new(A) do

  end.new('s')
```

#### Observed output

Without this change the following failure occurs in `run_sig_block_for_key`

```
undefined method `initialize` for `Test::A`

Uncaught exception: A previous invocation of #<UnboundMethod: Test::A#initialize> raised, and the current one succeeded. Please don't do that.
```

**Comment by fzakaria** [comment]
I have previously opened a #2309 with a proposed fix that uses a Mutex to protect the critical section. 

There was also a previous issue #2276 i'm closing in favor of this.

**Comment by will** [comment]
I ran into this on mri 2.6

**Comment by headius** [comment]
Since this also happens in MRI I believe this is purely a Sorbet bug. The relevant code needs a mutex or something.

**Comment by ianks** [comment]
Happening to us as well.

```
RuntimeError: A previous invocation of #<UnboundMethod: #<Class:WebToken>#decode(*args, &blk) /home/tile/app/vendor/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.9363/lib/types/private/methods/call_validation.rb:89> raised, and the current one succeeded. Please don't do that.
  from types/private/methods/_methods.rb:449:in `run_sig_block_for_key'
  from types/private/methods/_methods.rb:423:in `maybe_run_sig_block_for_key'
  from types/private/methods/_methods.rb:255:in `block in _on_method_added'
```
