### ISSUE TITLE
`validate_inheritance` error when running rbi commands with sealed module

### ISSUE THREAD

**Issue by robertjlooby** [sorbet/sorbet#2352]
#### Input

I made a simple repo to reproduce the error [here](https://github.com/robertjlooby/sorbet_monorepo/tree/validate_inheritance_error) since it's a more complex setup than is possible on sorbet.run. I have a gem with a sealed module and a hand written rbi file, so both the source and rbi are like:

```ruby
module Gem1
  module Sealed
    extend T::Helpers
    sealed!

    class Child1
      include Sealed
    end

    class Child2
      include Sealed
    end
  end
end
```

#### Observed output

Both the gem and the app typecheck with `srb tc`, but when running `srb rbi {gems,hidden-definitions}` in either one I get an error

    Gem1::Sealed was declared sealed and can only be included in ...

<details><summary>Full output</summary>

```
% srb rbi gems
Running command: gems
Generating: sorbet/rbi/gems/
Traceback (most recent call last):
	23: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/bin/srb-rbi:237:in `<main>'
	22: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/bin/srb-rbi:224:in `main'
	21: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/bin/srb-rbi:204:in `block in main'
	20: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/bin/srb-rbi:232:in `block in make_step'
	19: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem-generator-tracepoint.rb:38:in `main'
	18: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem-generator-tracepoint/tracer.rb:70:in `trace'
	17: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem-generator-tracepoint.rb:39:in `block in main'
	16: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/require_everything.rb:19:in `require_everything'
	15: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/require_everything.rb:39:in `load_bundler'
	14: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem_loader.rb:583:in `require_all_gems'
	13: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem_loader.rb:583:in `each'
	12: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem_loader.rb:585:in `block in require_all_gems'
	11: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem_loader.rb:563:in `require_gem'
	10: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem_loader.rb:563:in `require'
	 9: from /Users/rob/dev/ruby/sorbet_monorepo/gems/gem_1/lib/gem_1.rb:4:in `<top (required)>'
	 8: from /Users/rob/dev/ruby/sorbet_monorepo/gems/gem_1/lib/gem_1.rb:4:in `require'
	 7: from /Users/rob/dev/ruby/sorbet_monorepo/gems/gem_1/lib/gem_1/sealed.rb:3:in `<top (required)>'
	 6: from /Users/rob/dev/ruby/sorbet_monorepo/gems/gem_1/lib/gem_1/sealed.rb:4:in `<module:Gem1>'
	 5: from /Users/rob/dev/ruby/sorbet_monorepo/gems/gem_1/lib/gem_1/sealed.rb:8:in `<module:Sealed>'
	 4: from /Users/rob/dev/ruby/sorbet_monorepo/gems/gem_1/lib/gem_1/sealed.rb:9:in `<class:Child1>'
	 3: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem-generator-tracepoint/tracer.rb:22:in `include'
	 2: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem-generator-tracepoint/tracer.rb:22:in `include'
	 1: from /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.5140/lib/types/private/sealed.rb:17:in `included'
/Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-runtime-0.4.5140/lib/types/private/sealed.rb:57:in `validate_inheritance': Gem1::Sealed was declared sealed and can only be included in /Users/rob/dev/ruby/sorbet_monorepo/gems/gem_1/lib/gem_1/sealed.rb, not /Users/rob/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.4.5140/lib/gem-generator-tracepoint/tracer.rb (RuntimeError)
```

</details>

**Comment by robertjlooby** [comment]
If anyone else is running in to this, since #2486 you can use

```ruby
T::Configuration.sealed_violation_whitelist = [/sorbet.*tracer.rb$/]
```

to keep the sorbet tracer from erroring on a module that's sealed in both the source and the rbi

**Comment by klardotsh** [comment]
any chance of this fix being blessed upstream in some way by default? this was pretty weird to run into when building the first real Sorbet example for my team and needing to add a gem to the project after having written a sealed module
