### ISSUE TITLE
runtime: SystemStackError when double-prepending modules

### ISSUE THREAD

**Issue by mdehoog** [sorbet/sorbet#2375]
#### Input

```ruby
require 'sorbet-runtime'

module PrependedModule
  extend T::Sig

  sig { void }
  def method1
    super
  end
end

class Superclass
  def method1
  end
end

class Subclass < Superclass
end

Superclass.prepend(PrependedModule)
Subclass.prepend(PrependedModule)

puts Superclass.new.method1
puts Subclass.new.method1
```

Note that `PrependedModule`, which has a method with a sigil, is prepended to both the `Superclass` and the `Subclass`.

#### Observed output

```
=> Superclass.new.method1
T::Private::Types::Void::VOID
=> Subclass.new.method1
stack level too deep (SystemStackError)
```

#### Expected behavior

 - Expected `Superclass.new.method1` to return `nil`
 - Expected `Subclass.new.method1` to return `nil`

- - -

Traceback:
```
Traceback (most recent call last):
	10920: from ./repro.rb:24:in `<main>'
	10919: from .../gems/sorbet-runtime-0.4.5163/lib/types/private/methods/call_validation.rb:780:in `block in create_validator_procedure_fast0'
	10918: from .../gems/sorbet-runtime-0.4.5163/lib/types/private/methods/call_validation.rb:780:in `call'
	10917: from ./repro.rb:8:in `method1'
	10916: from .../gems/sorbet-runtime-0.4.5163/lib/types/private/methods/call_validation.rb:780:in `block in create_validator_procedure_fast0'
	10915: from .../gems/sorbet-runtime-0.4.5163/lib/types/private/methods/call_validation.rb:780:in `call'
	10914: from ./repro.rb:8:in `method1'
	10913: from .../gems/sorbet-runtime-0.4.5163/lib/types/private/methods/call_validation.rb:780:in `block in create_validator_procedure_fast0'
	 ... 10908 levels...
	    4: from .../gems/sorbet-runtime-0.4.5163/lib/types/private/methods/call_validation.rb:780:in `call'
	    3: from ./repro.rb:8:in `method1'
	    2: from .../gems/sorbet-runtime-0.4.5163/lib/types/private/methods/call_validation.rb:780:in `block in create_validator_procedure_fast0'
	    1: from .../gems/sorbet-runtime-0.4.5163/lib/types/private/methods/call_validation.rb:780:in `call'
./repro.rb:8:in `method1': stack level too deep (SystemStackError)
```

**Comment by jez** [comment]
Thanks for reporting. Sorbet is not really set up to handle `prepend` and we've banned usage of `prepend` in Stripe's codebase. The team has looked into what it would take to support `prepend` in the past and decided that it would be prohibitively expensive in terms of time and sacrifices.

**Comment by mdehoog** [comment]
Makes sense, thanks for the response 🙏
