### ISSUE TITLE
Bundler::GemNotFound: Could not find sorbet-static-0.4.5144-universal-darwin-14 in any of the sources

### ISSUE THREAD

**Issue by OpakAlex** [sorbet/sorbet#2396]
Only have this issue into alpine docker image.

gem 'sorbet', '0.4.5144'
gem 'sorbet-static', '0.4.5144'
gem 'sorbet-rails'
gem 'sorbet-runtime'

ruby: 2.6.5

command:
  bundle exec rake assets:precompile

Output:
bundler: failed to load command: rake (/bundle/ruby/2.6.0/bin/rake)
Bundler::GemNotFound: Could not find sorbet-static-0.4.5144-universal-darwin-14 in any of the sources
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/spec_set.rb:86:in `block in materialize'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/spec_set.rb:80:in `map!'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/spec_set.rb:80:in `materialize'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/definition.rb:170:in `specs'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/definition.rb:237:in `specs_for'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/definition.rb:226:in `requested_specs'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/runtime.rb:101:in `block in definition_method'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/runtime.rb:20:in `setup'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler.rb:149:in `setup'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/setup.rb:20:in `block in <top (required)>'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/ui/shell.rb:136:in `with_level'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/ui/shell.rb:88:in `silence'
  /usr/local/bundle/gems/bundler-2.1.2/lib/bundler/setup.rb:20:in `<top (required)>'
The command '/bin/sh -c bundle exec rake assets:precompile' returned a non-zero code: 1

**Comment by OpakAlex** [comment]
changed by hand Gemfile.lock, replace darwin via: `x86_64-linux`. 
Then added bash to alpine image, and got one more error ;))))
