### ISSUE TITLE
Capybara causes invalid reflection.rbi

### ISSUE THREAD

**Issue by ajoneil** [sorbet/sorbet#2618]
We have capybara in our Gemfile for testing. When generating types, it creates an invalid reflection.rbi file.

Terminal:
```
Generating /tmp/d20200206-12-1v0jo8c/reflection.rbi with 12425 modules and 279 aliases
Printing your code's symbol table into /tmp/d20200206-12-1v0jo8c/from-source.json
Printing /tmp/d20200206-12-1v0jo8c/reflection.rbi's symbol table into /tmp/d20200206-12-1v0jo8c/reflection.json
Traceback (most recent call last):
	6: from /app/vendor/gems/ruby/2.7.0/gems/sorbet-0.5.5345/bin/srb-rbi:237:in `<main>'
	5: from /app/vendor/gems/ruby/2.7.0/gems/sorbet-0.5.5345/bin/srb-rbi:196:in `main'
	4: from /app/vendor/gems/ruby/2.7.0/gems/sorbet-0.5.5345/bin/srb-rbi:121:in `init'
	3: from /app/vendor/gems/ruby/2.7.0/gems/sorbet-0.5.5345/bin/srb-rbi:232:in `block in make_step'
	2: from /app/vendor/gems/ruby/2.7.0/gems/sorbet-0.5.5345/lib/hidden-definition-finder.rb:38:in `main'
	1: from /app/vendor/gems/ruby/2.7.0/gems/sorbet-0.5.5345/lib/hidden-definition-finder.rb:47:in `main'
/app/vendor/gems/ruby/2.7.0/gems/sorbet-0.5.5345/lib/hidden-definition-finder.rb:149:in `write_constants': /tmp/d20200206-12-1v0jo8c/reflection.rbi had unexpected errors. Check this file for a clue: /tmp/d20200206-12-1v0jo8c/reflection.json.err (RuntimeError)
```

reflection.json.err: (sample, there's more errors along the same lines)
```
/tmp/d20200206-12-1v0jo8c/reflection.rbi:185796: unexpected token tCOLON https://srb.help/2001
      185796 |      *: ::T.untyped,
                     ^

/tmp/d20200206-12-1v0jo8c/reflection.rbi:185801: unexpected token tAMPER https://srb.help/2001
      185801 |  def accept_alert(**, &&); end
                                      ^

/tmp/d20200206-12-1v0jo8c/reflection.rbi:185805: unexpected token tCOLON https://srb.help/2001
      185805 |      *: ::T.untyped,
                     ^

/tmp/d20200206-12-1v0jo8c/reflection.rbi:185806: unexpected token tAMPER https://srb.help/2001
      185806 |      &: ::T.untyped,
                    ^
```
reflection.rbi: (sample)
```
module Capybara::DSL
  # Skipping `extend Sorbet::Private::GemGeneratorTracepoint::Tracer::ModuleOverride` because it is an invalid name
  sig do
    params(
      *: ::T.untyped,
      &: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def accept_alert(**, &&); end

  sig do
    params(
      *: ::T.untyped,
      &: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def accept_confirm(**, &&); end
``

**Comment by elliottt** [comment]
I think this is just due to running with ruby-2.7. Could you try again with ruby-2.6.5?

**Comment by ajoneil** [comment]
You're right, this works fine with ruby 2.6.5. Is there more information on this 2.7 incompatibility anywhere? I'd like to give it a shot at fixing!

**Comment by connorshea** [comment]
I assume it has to do with the kwargs change, see #2388

**Comment by elliottt** [comment]
@connorshea is right, it's related to the change in syntax for args. Given that this will require changing the parser, it will likely be a non-trivial change.
