### ISSUE TITLE
undefined method `start_with?' for :out:Symbol (NoMethodError)

### ISSUE THREAD

**Issue by vascoosx** [sorbet/sorbet#2693]
#### Input
```
bin/srb init
```

#### Observed output

```
.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sorbet-0.5.5384/lib/hidden-definition-finder.rb:286:in `block in without_errors': undefined method `start_with?' for :out:Symbol (NoMethodError)
```

#### Expected behavior

It should have finished initialization with no issue. Seems like `lines` contains non-String objects.

**Comment by elliottt** [comment]
Can you give a bit more information about how your environment is setup? Are you running `bin/srb init` directly from a sorbet repository clone?

**Comment by vascoosx** [comment]
I installed sorbet with bundle and the version is `Sorbet typechecker 0.5.5384`. I used `bundle binstubs sorbet` to be able to execute with `bin/srb`. I am using Rails 5.2.1 .

**Comment by ptrippett** [comment]
```
Traceback (most recent call last):
        13: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/bin/srb-rbi:237:in `<main>'
        12: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/bin/srb-rbi:196:in `main'
        11: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/bin/srb-rbi:121:in `init'
        10: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/bin/srb-rbi:232:in `block in make_step'
         9: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:38:in `main'
         8: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:49:in `main'
         7: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:166:in `write_diff'
         6: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:197:in `serialize_constants'
         5: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:197:in `each'
         4: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:204:in `block in serialize_constants'
         3: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:261:in `serialize_class'
         2: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:286:in `without_errors'
         1: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:286:in `reject'
/home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5390/lib/hidden-definition-finder.rb:286:in `block in without_errors': undefined method `start_with?' for :out:Symbol (NoMethodError)
```

Seems to be an incompatibility when you include sorbet rails gem, removing the `sorbet-rails` gem "resolves" the issue.

**Comment by ptrippett** [comment]
After some trial and error:

Gemfile
```
gem 'sorbet-rails', github: 'chanzuckerberg/sorbet-rails', ref: '8c99bb3'
gem 'sorbet-runtime', '0.5.5334'

group :development do
  gem 'sorbet', '0.5.5334'
end

```

When you try 0.5.5345 you start getting errors:
````
Printing /tmp/d20200224-32217-20izpb/reflection.rbi's symbol table into /tmp/d20200224-32217-20izpb/reflection.json
Traceback (most recent call last):
        6: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5360/bin/srb-rbi:237:in `<main>'
        5: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5360/bin/srb-rbi:196:in `main'
        4: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5360/bin/srb-rbi:121:in `init'
        3: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5360/bin/srb-rbi:232:in `block in make_step'
        2: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5360/lib/hidden-definition-finder.rb:38:in `main'
        1: from /home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5360/lib/hidden-definition-finder.rb:47:in `main'
/home/paul/.rvm/gems/ruby-2.6.5@gemset/gems/sorbet-0.5.5360/lib/hidden-definition-finder.rb:149:in `write_constants': /tmp/d20200224-32217-20izpb/reflection.rbi had unexpected errors. Check this file for a clue: /tmp/d20200224-32217-20izpb/reflection.json.err (RuntimeError)

````
