### ISSUE TITLE
sorbet-runtime crashes in Ruby on Rails when changing `T::Configuration.default_checked_level`

### ISSUE THREAD

**Issue by povilasjurcys** [sorbet/sorbet#2717]
#### Input

Given almost fresh rails project
```bash
  rails new sorbet_bug_proof
  cd sorbet_bug_proof
  echo "gem 'sorbet', group: :development" >> Gemfile
  echo "gem 'sorbet-runtime'" >> Gemfile
  bundle
  srb init
```

Then we add sorbet initializer which changes default_checked_level to :tests
```
  touch config/initializers/sorbet.rb
  echo "T::Configuration.default_checked_level = :tests" >> config/initializers/sorbet.rb
```

final project code can be found here too: https://github.com/povilasjurcys/sorbet_bug_proof

#### Observed output

when I run
```bash
rails s
```

I get error:

```
/home/povilas/.rvm/gems/ruby-2.6.1/gems/sorbet-runtime-0.5.5400/lib/types/private/runtime_levels.rb:48:in `default_checked_level=': Set the default checked level earlier. There are already some methods whose sig blocks have evaluated which would not be affected by the new default. (RuntimeError)
```

#### Expected behavior

I would expect that my app does not crash. 

Maybe simple warning would be better then crash. 
Also steps how to make this error disappear would be helpful. As far as I know initializers are loaded first, so I have no idea where should I put this code then...

Also allowing to use ENV variable in https://github.com/sorbet/sorbet/blob/811f72dab8358332f779f17a7897714884cac5f4/gems/sorbet-runtime/lib/types/private/runtime_levels.rb#L21 might also help:
```ruby
@default_checked_level = ENV.fetch(SORBET_DEFAULT_CHECKED_LEVEL, :always).to_sym
```
But I hope that there is a less hacky solution

**Comment by jez** [comment]
We believe pretty strongly that this is better to keep as an error, not a warning. This being an error has caught many bugs with `default_checked_level` being used at the wrong place. Usually when people are trying to use `default_checked_level`, it's because they absolutely don't want signatures to every cause the code to raise, which is something we can't guarantee if the project is improperly configured.

I don't know what `rails s` does internally. You're going to have to figure out what code is loaded and when, and move the `default_checked_level` to something that's required earlier in your project's life cycle.

You'll probably have better luck asking about this on the Sorbet Slack (https://sorbet.org/slack), where people who are using Rails and also default_checked_level can help you.

**Comment by povilasjurcys** [comment]
@jez after some investigation and help from @manhhung741 we found that sorbet-runtime messes this up. This problem only exist in `0.5` version, but not in `0.4`. And to be precise it happens in https://github.com/sorbet/sorbet/blob/3ef4d9a73287f68ad1bd9a4d8eba3666d7a7c524/gems/sorbet-runtime/lib/types/private/methods/decl_builder.rb#L207 So it's a bug after all

**Comment by manhhung741** [comment]
Here is the full stack where it first load `default_checked_level`. It's caused by simply `require 'sorbet-runtime'`

```
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/private/methods/decl_builder.rb:207:in `finalize!'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/private/methods/_methods.rb:282:in `run_builder'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/private/methods/_methods.rb:260:in `run_sig'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/private/methods/_methods.rb:200:in `block in _on_method_added'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/private/methods/_methods.rb:363:in `run_sig_block_for_key'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/private/methods/_methods.rb:347:in `run_sig_block_for_method'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/private/methods/_methods.rb:224:in `block in _on_method_added'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/props/_props.rb:28:in `new'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/props/_props.rb:28:in `decorator'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/props/_props.rb:145:in `included'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/private/mixins/mixins.rb:9:in `included'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/props/optional.rb:5:in `include'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/props/optional.rb:5:in `<module:Optional>'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/types/props/optional.rb:4:in `<top (required)>'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/sorbet-runtime.rb:99:in `require_relative'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sorbet-runtime-0.5.5400/lib/sorbet-runtime.rb:99:in `<top (required)>'
/home/dev/forks/povilasjurcys/sorbet_bug_proof/config/application.rb:2:in `require'
/home/dev/forks/povilasjurcys/sorbet_bug_proof/config/application.rb:2:in `<top (required)>'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:92:in `require'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:92:in `preload'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/dev/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
-e:1:in <main>
```

**Comment by Morriar** [comment]
Confirmed in a one-file project:

```sh
$> cat test.rb
```
```ruby
# typed: true

require 'sorbet-runtime'

T::Configuration.default_checked_level = :tests
```
```sh
$> bundle exec ruby test.rb

Traceback (most recent call last):
	2: from test.rb:5:in `<main>'
	1: from .gem/ruby/2.5.5/gems/sorbet-runtime-0.5.5406/lib/types/configuration.rb:55:in `default_checked_level='
.gem/ruby/2.5.5/gems/sorbet-runtime-0.5.5406/lib/types/private/runtime_levels.rb:48:in `default_checked_level=': Set the default checked level earlier. There are already some methods whose sig blocks have evaluated which would not be affected by the new default. (RuntimeError)
```

@jez I think this one should be re-opened.

**Comment by Morriar** [comment]
It might be caused by this: https://github.com/sorbet/sorbet/blob/master/gems/sorbet-runtime/lib/types/props/decorator.rb#L23

The signature seems to be evaluated before the configuration is set, resulting in the error. Commenting this signature makes Sorbet behave correctly again.
