### ISSUE TITLE
Crash in LSP in web mode

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#2723]
#### Input

[→ View on sorbet.run](https://sorbet.run/#module%20Private%0A%20%20extend%20T%3A%3ASig%0A%20%20def%20secure_compare(a%2C%20b)%0A%20%20%20%20res%20%3D%200%0A%20%20%20%20res%20%3D%3D%200%0A%20%20end%0Aend)

```ruby
module Private
  extend T::Sig
  def secure_compare(a, b)
    res = 0
    res == 0 # hover on res
  end
end
```

#### Observed output
From chrome console
```
... stuff ...
Read: {"jsonrpc":"2.0","id":2,"method":"textDocument/hover","params":{"textDocument":{"uri":"inmemory://model/default"},"position":{"line":4,"character":4}}}
client.ts:138 Ignoring request on untyped file `inmemory://model/default`
client.ts:162 Uncaught TypeError: Cannot read property 'Pointer_stringify' of null
    at Array.<anonymous> (client.ts:162)
    at jsCall_vi (sorbet-wasm.js:8)
    at /wasm-function[11973]:0x204edf
    at /wasm-function[8494]:0x160914
    at sorbet-wasm.js:8
    at Object.ccall (sorbet-wasm.js:8)
    at WebSocket.<anonymous> (client.ts:169)
    at target.js:63
    at Array.forEach (<anonymous>)
    at WebSocket.dispatchEvent (target.js:61)
client.ts:75 Starting language server.
console-window.ts:34 Sample Language Client: [Info  - 3:52:39 PM] Connection to server got closed. Server will restart.
console-window.ts:34 Sample Language Client: [Error - 3:52:39 PM] Request textDocument/hover failed.
console-window.ts:34 Sample Language Client: Error: Connection got disposed.
    at Object.dispose (https://sorbet.run/monaco/lib/main.bundle.js:67795:25)
    at https://sorbet.run/monaco/lib/main.bundle.js:137001:56
    at CallbackList.invoke (https://sorbet.run/monaco/lib/main.bundle.js:29847:39)
    at Emitter.fire (https://sorbet.run/monaco/lib/main.bundle.js:29911:36)
    at closeHandler (https://sorbet.run/monaco/lib/main.bundle.js:67191:26)
    at CallbackList.invoke (https://sorbet.run/monaco/lib/main.bundle.js:29847:39)
    at Emitter.fire (https://sorbet.run/monaco/lib/main.bundle.js:29911:36)
    at WebSocketMessageReader.AbstractMessageReader.fireClose (https://sorbet.run/monaco/lib/main.bundle.js:35083:27)
    at WebSocketMessageReader.fireClose (https://sorbet.run/monaco/lib/main.bundle.js:68288:40)
    at https://sorbet.run/monaco/lib/main.bundle.js:68244:19
console-window.ts:34 Sample Language Client: [Error - 3:52:39 PM] Starting client failed
console-window.ts:34 Sample Language Client: Error: Connection is disposed.
    at new ConnectionError (https://sorbet.run/monaco/lib/main.bundle.js:67108:28)
    at throwIfClosedOrDisposed (https://sorbet.run/monaco/lib/main.bundle.js:67586:19)
    at Object.onNotification (https://sorbet.run/monaco/lib/main.bundle.js:67667:13)
    at Object.onLogMessage (https://sorbet.run/monaco/lib/main.bundle.js:133112:62)
    at https://sorbet.run/monaco/lib/main.bundle.js:27600:24
console-window.ts:11 Couldn't start client Sample Language Client
ConsoleWindow.showMessage @ console-window.ts:11
main.js:138 Uncaught (in promise) Error: Connection is disposed.
    at new ConnectionError (main.js:138)
    at throwIfClosedOrDisposed (main.js:616)
    at Object.sendRequest (main.js:715)
    at Object.shutdown (connection.ts:107)
    at client.js:2260
```
#### Expected behavior

- - -

**Comment by jez** [comment]
Does not reproduce anymore.
