### ISSUE TITLE
Defining a T::Struct causes runtime errors on Ruby 2.4

### ISSUE THREAD

**Issue by AaronC81** [sorbet/sorbet#2743]
#### Input

```ruby
require 'sorbet-runtime'
class X < T::Struct
  prop :hello, String
end
```

#### Observed output

```
NoMethodError: private method `define_method' called for X:Class
Did you mean?  define_singleton_method
        from /home/aaron/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/sorbet-runtime-0.5.5417/lib/types/props/has_lazily_specialized_methods.rb:66:in `enqueue_lazy_method_definition!'
        from /home/aaron/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/call_validation.rb:126:in `call'
        from /home/aaron/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/call_validation.rb:126:in `validate_call'
        from /home/aaron/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/_methods.rb:238:in `block in _on_method_added'
        from /home/aaron/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/sorbet-runtime-0.5.5417/lib/types/props/serializable.rb:168:in `add_prop_definition'
        from /home/aaron/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/sorbet-runtime-0.5.5417/lib/types/props/decorator.rb:424:in `prop_defined'
        from /home/aaron/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/_methods.rb:240:in `call'
        from /home/aaron/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/_methods.rb:240:in `block in _on_method_added'
        from /home/aaron/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/sorbet-runtime-0.5.5417/lib/types/props/_props.rb:109:in `prop'
        from (irb):3:in `<class:X>'
        from (irb):2
        from /home/aaron/.rbenv/versions/2.4.9/bin/irb:11:in `<main>'
```

#### Expected behavior

I would expect this to define a `T::Struct` and not cause a runtime error.

- - -

This seems to work fine on anything newer than Ruby 2.4.

This bug makes just requiring Parlour (and consequently any of its plugins) cause an exception: https://github.com/AaronC81/parlour/issues/66

**Comment by franciscoj** [comment]
I've seen the same issue with sorbet `0.5.5420` and `0.5.5427` and I can confirm I only have it on Ruby `2.4.x` and not with `2.6.5`
