### ISSUE TITLE
enforced condition begin <= INVALID_POS_LOC has failed: (no message provided)

### ISSUE THREAD

**Issue by mbajur** [sorbet/sorbet#2783]
#### Input

```
$ srb init
```

#### Observed output

```
Generating /var/folders/xs/wzbp_g3s2q54_mwq3pbrj4gc0000gn/T/d20200317-75684-1sknp18/reflection.rbi with 39624 modules and 274 aliases
Printing your code's symbol table into /var/folders/xs/wzbp_g3s2q54_mwq3pbrj4gc0000gn/T/d20200317-75684-1sknp18/from-source.json
Printing /var/folders/xs/wzbp_g3s2q54_mwq3pbrj4gc0000gn/T/d20200317-75684-1sknp18/reflection.rbi's symbol table into /var/folders/xs/wzbp_g3s2q54_mwq3pbrj4gc0000gn/T/d20200317-75684-1sknp18/reflection.json
Traceback (most recent call last):
        6: from /Users/mbajur/.rvm/gems/ruby-2.5.3/gems/sorbet-0.5.5449/bin/srb-rbi:237:in `<main>'
        5: from /Users/mbajur/.rvm/gems/ruby-2.5.3/gems/sorbet-0.5.5449/bin/srb-rbi:196:in `main'
        4: from /Users/mbajur/.rvm/gems/ruby-2.5.3/gems/sorbet-0.5.5449/bin/srb-rbi:121:in `init'
        3: from /Users/mbajur/.rvm/gems/ruby-2.5.3/gems/sorbet-0.5.5449/bin/srb-rbi:232:in `block in make_step'
        2: from /Users/mbajur/.rvm/gems/ruby-2.5.3/gems/sorbet-0.5.5449/lib/hidden-definition-finder.rb:38:in `main'
        1: from /Users/mbajur/.rvm/gems/ruby-2.5.3/gems/sorbet-0.5.5449/lib/hidden-definition-finder.rb:47:in `main'
/Users/mbajur/.rvm/gems/ruby-2.5.3/gems/sorbet-0.5.5449/lib/hidden-definition-finder.rb:149:in `write_constants': /var/folders/xs/wzbp_g3s2q54_mwq3pbrj4gc0000gn/T/d20200317-75684-1sknp18/reflection.rbi had unexpected errors. Check this file for a clue: /var/folders/xs/wzbp_g3s2q54_mwq3pbrj4gc0000gn/T/d20200317-75684-1sknp18/reflection.json.err (RuntimeError)
```

And the mentioned file:

```
Exception::raise(): ./core/Loc.h:74 enforced condition begin <= INVALID_POS_LOC has failed: (no message provided)

Backtrace:
sorbet::Exception::enforce_handler(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, int) (in sorbet) + 42
sorbet::core::Loc::Loc(sorbet::core::FileRef, unsigned int, unsigned int) (in sorbet) + 109
sorbet::parser::Builder::Impl::constGlobal(ruby_parser::token const*, ruby_parser::token const*) (in sorbet) + 84
(anonymous namespace)::constGlobal(void const*, ruby_parser::token const*, ruby_parser::token const*) (in sorbet) + 31
ruby_parser::bison::typedruby25::parser::parse() (in sorbet) + 27153
ruby_parser::typedruby25::parse(void const*) (in sorbet) + 40
sorbet::parser::Builder::build(ruby_parser::base_driver*) (in sorbet) + 32
sorbet::parser::Parser::run(sorbet::core::GlobalState&, sorbet::core::FileRef, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >) (in sorbet) + 807
sorbet::realmain::pipeline::runParser(sorbet::core::GlobalState&, sorbet::core::FileRef, sorbet::realmain::options::Printers const&) (in sorbet) + 433
sorbet::realmain::pipeline::indexOneWithPlugins(sorbet::realmain::options::Options const&, sorbet::core::GlobalState&, sorbet::core::FileRef, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in sorbet) + 1122
sorbet::realmain::pipeline::index(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::core::FileRef, std::__1::allocator<sorbet::core::FileRef> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, std::__1::unique_ptr<sorbet::OwnedKeyValueStore, std::__1::default_delete<sorbet::OwnedKeyValueStore> > const&) (in sorbet) + 332
sorbet::realmain::realmain(int, char**) (in sorbet) + 7157
main (in sorbet) + 11
start (in libdyld.dylib) + 1

/var/folders/xs/wzbp_g3s2q54_mwq3pbrj4gc0000gn/T/d20200317-75684-1sknp18/reflection.rbi: Exception parsing file: `/var/folders/xs/wzbp_g3s2q54_mwq3pbrj4gc0000gn/T/d20200317-75684-1sknp18/reflection.rbi` (backtrace is above) https://srb.help/1001

```

#### Expected behavior

Initialization should be finished

- - -

- Ruby 2.5.3

**Comment by elliottt** [comment]
Does this happen for an empty project with 2.5.3, or are you able to share a minimal case to reproduce it?

**Comment by mbajur** [comment]
Sadly, it happens on pretty big commercial closed-source project. Is there anything i can do to try to reproduce that? Backtrace of that is not telling me much

**Comment by wpride** [comment]
I am newly running into this issue as well. Unfortunately I also work on a large proprietary codebase.

**Comment by DarkDimius** [comment]
Do you have files of >8M of size?
This error could be triggered by this

**Comment by DarkDimius** [comment]
https://github.com/sorbet/sorbet/pull/2766 might help when it lands

**Comment by mbajur** [comment]
I'm not fully aware of how sorbet works, but if you're asking if i have ruby files larger than 8M - than i don't ;)

**Comment by wpride** [comment]
My `hidden.rbi` is 6.5MB but since that's deleted I assume that's not the problem?

**Comment by wpride** [comment]
Can someone offer guidance on how to fix, work around, or debug this issue?

**Comment by wpride** [comment]
@mbajur This is fixed for me on the latest release; you should update and give this a try when you have a chance.

**Comment by mbajur** [comment]
Perfect! Can confirm it now worked :) Thanks everyone
