### ISSUE TITLE
srb init crashes on 'superclass mismatch for class'

### ISSUE THREAD

**Issue by rex-remind101** [sorbet/sorbet#3255]
#### Input

```ruby
bundle exec srb init
```

#### Observed output

```
...
Traceback (most recent call last):
	35: from /usr/local/bundle/gems/sorbet-0.5.5795/bin/srb-rbi:237:in `<main>'
	34: from /usr/local/bundle/gems/sorbet-0.5.5795/bin/srb-rbi:196:in `main'
	33: from /usr/local/bundle/gems/sorbet-0.5.5795/bin/srb-rbi:118:in `init'
	32: from /usr/local/bundle/gems/sorbet-0.5.5795/bin/srb-rbi:232:in `block in make_step'
	31: from /usr/local/bundle/gems/sorbet-0.5.5795/lib/gem-generator-tracepoint.rb:38:in `main'
	30: from /usr/local/bundle/gems/sorbet-0.5.5795/lib/gem-generator-tracepoint/tracer.rb:70:in `trace'
	29: from /usr/local/bundle/gems/sorbet-0.5.5795/lib/gem-generator-tracepoint.rb:39:in `block in main'
	28: from /usr/local/bundle/gems/sorbet-0.5.5795/lib/require_everything.rb:18:in `require_everything'
	27: from /usr/local/bundle/gems/sorbet-0.5.5795/lib/require_everything.rb:28:in `load_rails'
	26: from /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/engine.rb:473:in `eager_load!'
	25: from /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/engine.rb:473:in `each'
	24: from /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/engine.rb:475:in `block in eager_load!'
	23: from /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/engine.rb:475:in `each'
	22: from /usr/local/bundle/gems/railties-5.0.7.2/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
	21: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:252:in `require_dependency'
	20: from /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:85:in `depend_on'
	19: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:336:in `depend_on'
	18: from /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:47:in `require_or_load'
	17: from /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	16: from /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `block in require_or_load'
	15: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:358:in `require_or_load'
	14: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:37:in `load_interlock'
	13: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
	12: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	11: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	10: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	 9: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:375:in `block in require_or_load'
	 8: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:477:in `load_file'
	 7: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:663:in `new_constants_in'
	 6: from /usr/local/bundle/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:478:in `block in load_file'
	 5: from /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	 4: from /usr/local/bundle/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	 3: from /home/app/services/<our_file_path>/<our_file_name>.rb:7:in `<main>'
	 2: from /home/app/services/<our_file_path>/<our_file_name>.rb:8:in `<module:Graph>'
	 1: from /home/app/services/<our_file_path>/<our_file_name>.rb:9:in `<module:Queries>'
/home/app/services/<our_file_path>/<our_file_name>.rb:96:in `<class:AClass>': superclass mismatch for class AClass (TypeError)
```

#### Expected behavior

Don't crash on init.

- - -

This is a large and complex codebase that runs in a production environment without any sort of problem like this. Not sure why this error would be happening other than possibly `srb init` is running through files twice, redundantly attempting to instantiate classes.

If I add something like this at the top of the file
```
puts "here1.1"
if Object.const_defined?('AClass')
  puts "here1.2", AClass
  return
end
```
it will print `here1.1` and later `here1.2` somewhat confirming my hypothesis. It henceforth succeeds to not crash on that file, but then crashes a few files later with the same error but on a different Class. Every attempt I make on any file to circumvent, there will inevitably be a new similar error thrown some arbitrary number of files later.

**Comment by rex-remind101** [comment]
Was poking around with a debugger on an init run and ran into this which looks odd
```
From: /usr/local/bundle/gems/hpricot-0.8.6/lib/hpricot/blankslate.rb @ line 58 Object.method_added:

    57: def method_added(name)
 => 58:   hpricot_slate_method_added(name)
    59:   return if self != Object
    60:   Hpricot::BlankSlate.hide(name)
    61: end
```

**Comment by rex-remind101** [comment]
Commenting out that code did not fix the issue.

**Comment by jez** [comment]
Cannot reproduce.
