### ISSUE TITLE
A better error message for invalid signatures, when using only sorbet-runtime

### ISSUE THREAD

**Issue by jaredbeck** [sorbet/sorbet#3328]
### Problem

The following signature is invalid, but it's easy to see how someone could make this mistake.

```
sig { params(Integer).void }
def f(i)
```

The correct signature, of course, is `params(i: Integer)`.

The error message produced by `sorbet-runtime` is quite poor:

```
undefined method `keys' for Integer:Class (NoMethodError)
```

### Proposed solution

The error message should instead say something like: "Invalid signature: params expects a Hash"

**Comment by jaredbeck** [comment]
If we put ourselves in the shoes of a junior engineer, I think it would be very difficult for them to interpret the current error message.

If we want junior engineers to succeed with sorbet, I think better error messages, generally, should be a priority.

I'm happy to make a PR if you can give me a hint of where in `sorbet-runtime` the improved error should be raised.

**Comment by jaredbeck** [comment]
To be clear, this is only an issue with `sorbet-runtime`. Here's a runtime-only reproduction:

```ruby
# issue3328.rb
# typed: true
require 'sorbet-runtime'

module M
  extend T::Sig

  sig { params(Integer).void }
  def self.f(i)
  end
end

M.f(13)
```

``` plain
Traceback (most recent call last):
	9: from issue3328.rb:11:in `<main>'
...
... methods/signature.rb:54:in `initialize': undefined method `keys' for Integer:Class (NoMethodError)
```

Static analysis, by comparison, has a helpful error message:

```plain
issue3328.rb:5: params expects keyword arguments https://srb.help/5003
     5 |  sig { params(Integer).void }
                ^^^^^^^^^^^^^^^
  All parameters must be given names in params even if they are positional
```
