### ISSUE TITLE
Duplicate values in enum definitions are only an error at runtime

### ISSUE THREAD

**Issue by ghiculescu** [sorbet/sorbet#3399]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Suit%20%3C%20T%3A%3AEnum%0A%20%20enums%20do%0A%20%20%20%20Spades%20%3D%20new(1)%0A%20%20%20%20Hearts%20%3D%20new(2)%0A%20%20%20%20Clubs%20%3D%20new(3)%0A%20%20%20%20Diamonds%20%3D%20new(3)%20%23%20runtime%20error%0A%20%20end%0Aend)

```ruby
# typed: true

class Suit < T::Enum
  enums do
    Spades = new(1)
    Hearts = new(2)
    Clubs = new(3)
    Diamonds = new(3) # runtime error
  end
end
```

#### Observed output

```
No errors! Great job.
```

#### Runtime output

```
% ruby /Users/alex/Desktop/test.rb
Traceback (most recent call last):
	7: from /Users/alex/Desktop/test.rb:4:in `<main>'
	6: from /Users/alex/Desktop/test.rb:5:in `<class:Suit>'
	5: from /Users/alex/.rvm/gems/ruby-2.6.6/gems/sorbet-runtime-0.5.5821/lib/types/private/methods/_methods.rb:238:in `block in _on_method_added'
	4: from /Users/alex/.rvm/gems/ruby-2.6.6/gems/sorbet-runtime-0.5.5821/lib/types/private/methods/call_validation.rb:126:in `validate_call'
	3: from /Users/alex/.rvm/gems/ruby-2.6.6/gems/sorbet-runtime-0.5.5821/lib/types/private/methods/call_validation.rb:126:in `call'
	2: from /Users/alex/.rvm/gems/ruby-2.6.6/gems/sorbet-runtime-0.5.5821/lib/types/enum.rb:318:in `enums'
	1: from /Users/alex/.rvm/gems/ruby-2.6.6/gems/sorbet-runtime-0.5.5821/lib/types/enum.rb:318:in `each'
/Users/alex/.rvm/gems/ruby-2.6.6/gems/sorbet-runtime-0.5.5821/lib/types/enum.rb:328:in `block in enums': Enum values must have unique serializations. Value '3' is repeated on Suit. (RuntimeError)
```

#### Expected behavior

It would be awesome if this errored statically, not just at runtime.

**Comment by jez** [comment]
I don't think this is in general possible to make into a static error. `T::Enum` currently allows arbitrary computation to be used to populate the serialized values, so you could do something like

```ruby
# typed: true

class Suit < T::Enum
  enums do
    Spades = new(arbitrary_computation(1))
    Hearts = new(arbitrary_computation(2))
    Clubs = new(arbitrary_computation(3))
    Diamonds = new(arbitrary_computation(3))
end
```

and there would be no way to tell whether `arbitrary_computation(3) == `arbitrary_computation(3)`.

**Comment by jez** [comment]
Maybe something could be done for simple literals, but this feels like a missing feature not a bug to me.

**Comment by ghiculescu** [comment]
Yeah good point. That feels like a pretty bad practice, I don't see how you could prevent it. Given the need to support that, I agree this is a feature request.
