### ISSUE TITLE
srb init error

### ISSUE THREAD

**Issue by spartan218** [sorbet/sorbet#3495]
Hello,

I've been trying to just get `bundle exec srb init` and it continues to stop on this error.
Unfortunately this error only tells me information about something happening inside the gem itself.

Any help would be appreciated.

```
Exception::raise(): Should never happen

Backtrace:
sorbet::realmain::pipeline::typecheck(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >, sorbet::realmain::options::Options const&, sorbet::WorkerPool&, bool, std::__1::optional<std::__1::shared_ptr<sorbet::core::lsp::PreemptionTaskManager> >, bool) (in sorbet) + 6065
sorbet::realmain::realmain(int, char**) (in sorbet) + 9102
main (in sorbet) + 11
start (in libdyld.dylib) + 1
0x00000009 (in sorbet)

Traceback (most recent call last):
        13: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/bin/srb-rbi:237:in `<main>'
        12: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/bin/srb-rbi:196:in `main'
        11: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/bin/srb-rbi:118:in `init'
        10: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/bin/srb-rbi:232:in `block in make_step'
         9: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/lib/gem-generator-tracepoint.rb:38:in `main'
         8: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/lib/gem-generator-tracepoint/tracer.rb:70:in `trace'
         7: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/lib/gem-generator-tracepoint.rb:39:in `block in main'
         6: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/lib/require_everything.rb:20:in `require_everything'
         5: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/lib/require_everything.rb:46:in `require_all_files'
         4: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/lib/require_everything.rb:134:in `rb_file_paths'
         3: from ~/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
         2: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
         1: from ~/vendor/bundle/ruby/2.5.0/gems/sorbet-0.5.5937/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
~/vendorbundle/ruby/2.5.0/gems/sorbet-0.5.5937/lib/gem-generator-tracepoint/tracer.rb:40:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
```

**Comment by jez** [comment]
You've found a bug in Sorbet, but it's impossible to tell what the problem is without a way to reproduce it on our end.

If possible, please either share a concrete set of steps we can take to reproduce the problem. Otherwise, there's not much help we can provide.

**Comment by spartan218** [comment]
Sure so I have a codebase I am working on and here are the steps I took get where I am.

Following the instructions [here](https://sorbet.org/docs/adopting) of course:
- successfully installed the gem (with bundle) and was able to run the test cmds
- Initially had errors with protobuffs getting errors like
```
`add_file': Unable to add defs to DescriptorPool: out of memory (Google::Protobuf::TypeError)
```

- removed all protobuff files and commented out references to them 
- upgraded from ruby version `2.3.8` to `2.5.3` after [reading](https://sorbet.org/docs/faq#how-do-i-upgrade-sorbet)  
- attempted to run `bundle exec srb init` again

**Comment by jez** [comment]
I can't reproduce this error. If you can provide a list of concrete steps that we can take to reproduce, including source files that I must have on my machine and the exact command line & arguments that I have to run to reproduce the issue, please open another ticket and include that information.
