### ISSUE TITLE
hidden-definition-finder.rb  `write_constants': Your source can't be read by Sorbet. (RuntimeError)

### ISSUE THREAD

**Issue by silva96** [sorbet/sorbet#3623]
disclaimer: occurs in a kind of legacy project.

Gem versions:

sorbet (0.5.5784)
sorbet-rails (0.7.0)

#### Input

```ruby
srb rbi update
```

#### Observed output

```
Generating /var/folders/v_/xmfm5zgd58j5l108ftb89s9r0000gn/T/d20201106-75025-ok2ri/reflection.rbi with 16579 modules and 264 aliases
Printing your code's symbol table into /var/folders/v_/xmfm5zgd58j5l108ftb89s9r0000gn/T/d20201106-75025-ok2ri/from-source.json
/Users/benja/.rvm/gems/ruby-2.4.10/gems/sorbet-0.5.5784/lib/hidden-definition-finder.rb:119:in `write_constants': Your source can't be read by Sorbet. (RuntimeError)
You can try `find . -type f | xargs -L 1 -t bundle exec srb tc --no-config --error-white-list 1000` and hopefully the last file it is processing before it dies is the culprit.
If not, maybe the errors in this file will help: /var/folders/v_/xmfm5zgd58j5l108ftb89s9r0000gn/T/d20201106-75025-ok2ri/from-source.json.err
        from /Users/benja/.rvm/gems/ruby-2.4.10/gems/sorbet-0.5.5784/lib/hidden-definition-finder.rb:47:in `main'
        from /Users/benja/.rvm/gems/ruby-2.4.10/gems/sorbet-0.5.5784/lib/hidden-definition-finder.rb:38:in `main'
        from /Users/benja/.rvm/gems/ruby-2.4.10/gems/sorbet-0.5.5784/bin/srb-rbi:232:in `block in make_step'
        from /Users/benja/.rvm/gems/ruby-2.4.10/gems/sorbet-0.5.5784/bin/srb-rbi:121:in `init'
        from /Users/benja/.rvm/gems/ruby-2.4.10/gems/sorbet-0.5.5784/bin/srb-rbi:196:in `main'
        from /Users/benja/.rvm/gems/ruby-2.4.10/gems/sorbet-0.5.5784/bin/srb-rbi:237:in `<main>'

```

#### Expected behavior

I expect the command finishes without breaking.

I was able to run this a few weeks ago, the only difference is I updated a few gems, but sorbet remained the same.

**Comment by silva96** [comment]
the error file has this content:

/Users/benja/.rvm/gems/ruby-2.4.10/gems/sorbet-0.5.5939/bin/srb: line 46: 42467 Segmentation fault: 11  "${sorbet}" "${args[@]}"

**Comment by silva96** [comment]
upgrading sorbet solved it
