### ISSUE TITLE
`bundle exec srb init` crashes in Ruby 3.0.0

### ISSUE THREAD

**Issue by dee-see** [sorbet/sorbet#3849]
#### Input

`.ruby-version`

```text
3.0.0
```

`Gemfile`

```ruby
source 'https://rubygems.org'

gem 'sorbet
```

`test.rb`

```ruby
class A
end
```

#### Observed output

Run `bundle install` and then

```shell
$ bundle exec srb init

Hey there!

This script will get this project ready to use with Sorbet by creating a
sorbet/ folder for your project. It will contain:

- a config file
- a bunch of 'RBI files'

RBI stands for 'Ruby Interface'; these files define classes, methods, and
constants that exist, but which Sorbet doesn't always know about.

Heads up:

To set up your project, this script will take two potentially destructive
actions:

1.  It will require every file in your project. Specifically, every script in
    your project will be run, unless that script checks if __FILE__ == $PROGRAM_NAME
    before running any code, or has the magic comment # typed: ignore in it.

2.  It will add a comment to the top of every file (like # typed: false or
    # typed: true, depending on how many errors were found in that file.)

Would you like to continue? [Y/n] 
Generating: sorbet/config
Reusing existing config file: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static
/home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6111/lib/gem-generator-tracepoint/tracepoint_serializer.rb:35:in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes) (ArgumentError)
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6111/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6111/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6111/lib/gem-generator-tracepoint.rb:43:in `main'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6111/bin/srb-rbi:232:in `block in make_step'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6111/bin/srb-rbi:118:in `init'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6111/bin/srb-rbi:196:in `main'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6111/bin/srb-rbi:237:in `<main>'
```

#### Expected behavior

It shouldn't crash :)

- - -

It works as expected in 2.7.2

I really expected this issue to exist and I looked for duplicates but couldn't find any. Sorry if this is known!

**Comment by dee-see** [comment]
I faced that issue when trying to reproduce a similar error I get on my actual ruby project

```
/home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast/node_pattern/compiler/node_pattern_subcompiler.rb:16:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast/node_pattern/compiler.rb:47:in `compile_as_node_pattern'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast/node_pattern.rb:65:in `initialize'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast/node_pattern.rb:37:in `def_node_matcher'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast/node.rb:275:in `<class:Node>'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast/node.rb:21:in `<module:AST>'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast/node.rb:4:in `<module:RuboCop>'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast/node.rb:3:in `<top (required)>'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast.rb:26:in `require_relative'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop/ast.rb:26:in `<top (required)>'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop-ast.rb:3:in `require_relative'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-ast-1.3.0/lib/rubocop-ast.rb:3:in `<top (required)>'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.7.0/lib/rubocop.rb:14:in `require'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rubocop-1.7.0/lib/rubocop.rb:14:in `<top (required)>'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem_loader.rb:1206:in `require'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem_loader.rb:1206:in `require_gem'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem_loader.rb:1235:in `block in require_all_gems'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem_loader.rb:1233:in `each'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem_loader.rb:1233:in `require_all_gems'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/require_everything.rb:39:in `load_bundler'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/require_everything.rb:19:in `require_everything'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem-generator-tracepoint.rb:39:in `block in main'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem-generator-tracepoint/tracer.rb:70:in `trace'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/lib/gem-generator-tracepoint.rb:38:in `main'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/bin/srb-rbi:232:in `block in make_step'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/bin/srb-rbi:118:in `init'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/bin/srb-rbi:196:in `main'
        from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6188/bin/srb-rbi:237:in `<main>'
```

**Comment by connorshea** [comment]
This is because of the kwargs change I believe, because if you run it on 2.7 with deprecation warnings enabled it will warn you about the same lines.

**Comment by connorshea** [comment]
The current code that has the deprecation warning looks like this:

```ruby
def new(*)
  result = super
  Sorbet::Private::GemGeneratorTracepoint::Tracer.on_module_created(result)
  result
end
```

As far as I can tell, the `new(*)` is fully equivalent to `new(*args)`.

The problem is that we're trying to do method delegation in a way that Ruby 3 doesn't like.

The best fix I can come up with is to use `ruby2_keywords`:

```ruby
# Add ruby2_keywords (will need a method defined on Ruby versions
# before 2.7 that stubs ruby2_keywords so it'll work). See the
# "compatible delegation" section in this blog post:
# https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
ruby2_keywords def new(*args)
  result = super
  Sorbet::Private::GemGeneratorTracepoint::Tracer.on_module_created(result)
  result
end
```

Eventually this can be updated to `new(...)` once we support only Ruby 2.7+.

**Comment by connorshea** [comment]
I've opened a PR to fix this, but unfortunately it still won't work on Ruby 3 since there's another issue with sorted_set raising an error when trying to run it 😒 

It does make it further into the hidden definitions generation process, though!

**Comment by dee-see** [comment]
Heh that's a step forward! Do you have a general "support ruby 3.0" issue I can follow or should I report new issues at each problem I hit?

**Comment by connorshea** [comment]
I'll open a generic 'support ruby 3.0' ticket :)

**Comment by connorshea** [comment]
I've opened #3851

**Comment by dee-see** [comment]
Hi @jez :wave:

Are the changes supposed to be included in https://github.com/sorbet/sorbet/releases/tag/0.5.6249.20210126165344-49e284886 ?

It didn't solve the problem for me, running the same steps as the original issue

```
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static
/home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/lib/gem-generator-tracepoint/tracepoint_serializer.rb:35:in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes) (ArgumentError)
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/lib/gem-generator-tracepoint.rb:43:in `main'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/bin/srb-rbi:232:in `block in make_step'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/bin/srb-rbi:118:in `init'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/bin/srb-rbi:196:in `main'
	from /home/dee-see/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/bin/srb-rbi:237:in `<main>'
```

**Comment by connorshea** [comment]
Odd, that works for me when I run `bundle exec srb rbi hidden-definitions` (well, it works until I hit an issue with sorted_set, but that's a separate thing), but I seem to run into a different error when running `srb init`:

```
Connors-MacBook-Pro-2:vglist connorshea$ CI=true bundle exec srb init

👋 Hey there!

This script will get this project ready to use with Sorbet by creating a
sorbet/ folder for your project. It will contain:

- a config file
- a bunch of 'RBI files'

RBI stands for 'Ruby Interface'; these files define classes, methods, and
constants that exist, but which Sorbet doesn't always know about.

⚠️  Heads up:

To set up your project, this script will take two potentially destructive
actions:

1.  It will require every file in your project. Specifically, every script in
    your project will be run, unless that script checks if __FILE__ == $PROGRAM_NAME
    before running any code, or has the magic comment # typed: ignore in it.

2.  It will add a comment to the top of every file (like # typed: false or
    # typed: true, depending on how many errors were found in that file.)

❔ Would you like to continue? [Y/n] y
Generating: sorbet/config
Reusing existing config file: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
/Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/binding_of_caller-1.0.0/lib/binding_of_caller/mri.rb:21: [BUG] Segmentation fault at 0xfffffffffffffff0
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0063 p:---- s:0342 e:000341 CFUNC  :open
c:0062 p:0020 s:0338 E:000d48 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/binding_of_caller-1.0.0/lib/binding_of_caller/mri.rb:21
c:0061 p:0025 s:0333 E:000118 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/better_errors-2.9.1/lib/better_errors/exception_extension.rb:7 [FINISH]
c:0060 p:---- s:0328 e:000327 CFUNC  :raise
c:0059 p:0084 s:0321 E:000558 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/cache.rb:92
c:0058 p:0053 s:0316 E:0005a0 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0057 p:0007 s:0308 E:0005f0 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0056 p:0068 s:0305 E:0010d8 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299
c:0055 p:0010 s:0298 E:0005d0 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0054 p:0005 s:0292 E:000640 TOP    /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/addressable-2.7.0/lib/addressable/idna/native.rb:21 [FINISH]
c:0053 p:---- s:0289 e:000288 CFUNC  :require
c:0052 p:0012 s:0284 E:001130 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0051 p:0070 s:0281 E:000760 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_in
c:0050 p:0025 s:0269 E:001110 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0049 p:0065 s:0263 E:0011a0 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0048 p:0007 s:0255 E:0007b0 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0047 p:0068 s:0252 E:000818 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299
c:0046 p:0010 s:0245 E:000790 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0045 p:0005 s:0239 E:000840 TOP    /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/addressable-2.7.0/lib/addressable/idna.rb:22 [FINISH]
c:0044 p:---- s:0236 e:000235 CFUNC  :require
c:0043 p:0012 s:0231 E:000890 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0042 p:0070 s:0228 E:000920 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_in
c:0041 p:0025 s:0216 E:000870 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0040 p:0065 s:0210 E:000960 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0039 p:0007 s:0202 E:0009b0 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0038 p:0068 s:0199 E:000a18 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299
c:0037 p:0010 s:0192 E:000990 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0036 p:0011 s:0186 E:000a40 TOP    /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/addressable-2.7.0/lib/addressable/uri.rb:22 [FINISH]
c:0035 p:---- s:0183 e:000182 CFUNC  :require
c:0034 p:0012 s:0178 E:000a90 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0033 p:0070 s:0175 E:000b20 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_in
c:0032 p:0025 s:0163 E:000a70 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0031 p:0065 s:0157 E:000b60 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0030 p:0007 s:0149 E:000bb0 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0029 p:0068 s:0146 E:000c18 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299
c:0028 p:0010 s:0139 E:000b90 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0027 p:0005 s:0133 E:000d70 TOP    /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/launchy-2.5.0/lib/launchy.rb:1 [FINISH]
c:0026 p:---- s:0130 e:000129 CFUNC  :require
c:0025 p:0012 s:0125 E:000dc0 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0024 p:0070 s:0122 E:000e50 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_in
c:0023 p:0025 s:0110 E:000da0 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0022 p:0065 s:0104 E:000e90 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_re
c:0021 p:0032 s:0096 E:000f30 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:66 [FINISH]
c:0020 p:---- s:0091 e:000090 CFUNC  :each
c:0019 p:0042 s:0087 E:000f00 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:61 [FINISH]
c:0018 p:---- s:0080 e:000079 CFUNC  :each
c:0017 p:0026 s:0076 E:000eb8 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:50
c:0016 p:0013 s:0071 E:000f58 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/3.0.0/bundler.rb:174
c:0015 p:0090 s:0066 E:000f80 TOP    /Users/connorshea/Programming/vglist/config/application.rb:21 [FINISH]
c:0014 p:---- s:0063 e:000062 CFUNC  :require
c:0013 p:0007 s:0058 E:000fd0 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0012 p:0068 s:0055 E:001038 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299
c:0011 p:0010 s:0048 E:000fb0 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332
c:0010 p:0012 s:0042 E:001068 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/lib/require_everything.rb:25
c:0009 p:0019 s:0037 E:001090 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/lib/require_everything.rb:18
c:0008 p:0020 s:0033 E:0010e0 BLOCK  /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/lib/gem-generator-tracepoint.rb:39
c:0007 p:0006 s:0030 E:001130 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/lib/gem-generator-tracepoint/tracer.rb:80
c:0006 p:0023 s:0026 E:0010c0 METHOD /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6249/lib/gem-generator-tracepoint.rb:38
```

**Comment by krschacht** [comment]
I'm having this same issue as well. Ruby 3.0.0, Sorbet 0.5.6292. Is there a workaround or do I switch to Tapioca?

**Comment by burlesona** [comment]
Same issue here, Ruby 3.0.1p64. Literally just started a new ruby project with one ruby file and `bundle exec srb init` fails with same error message @dee-see described.

**Comment by evsasse** [comment]
Getting the same problem as @dee-see , on `0.5.9318`, also `ruby 3.0.1p64`.

**Comment by mbast100** [comment]
Getting same problem with `ruby 3.1`

**Comment by adrian-gomez** [comment]
I'm facing the same issue using sorbet `0.5.9553` and ruby `3.0.1p64` I was able to fix it locally by changing `TracepointSerializer.new(*trace_results).serialize(output_dir)` to `TracepointSerializer.new(**trace_results).serialize(output_dir)` on `lib/gem-generator-tracepoint.rb` not sure if thats the a actual fix or it just works for me.
I'm running `bundle exec srb rbi gems`
