### ISSUE TITLE
Support Ruby 3.0

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#3851]
This is an issue for tracking Ruby 3.0 support for Sorbet. I'd like to use this issue just for getting Sorbet working on Ruby 3 in the first place, we can create a separate issue for adding new method definitions, etc.

The main problem is currently just with the hidden definitions generation, everything else seems to work correctly.

#### Observed output

(This is _with_ the changes from my PR #3850. With current master, it'll run into the error described in #3849)

Rails app on Ruby 3.0, run `bundle exec srb rbi hidden-definitions`:

```
Connors-MacBook-Pro-2:vglist connorshea$ CI=true bundle exec srb rbi hidden-definitions
Running command: hidden-definitions
Generating: sorbet/rbi/hidden-definitions/
Requiring all of your code
NameError: uninitialized constant ActionController::Middleware
Did you mean?  ActionController::MiddlewareStack
NameError: uninitialized constant ActiveStorage::Transformers::MiniMagickTransformer
LoadError: cannot load such file -- aws-sdk
LoadError: cannot load such file -- webrick/httputils
LoadError: cannot load such file -- graphql-rails_logger
LoadError: cannot load such file -- net-http-persistent
Did you mean?  net/http/response
LoadError: cannot load such file -- webrobots
LoadError: cannot load such file -- pundit-matchers
LoadError: cannot load such file -- rack/session/dalli
LoadError: cannot load such file -- rack-cors
LoadError: cannot load such file -- railties
LoadError: Function 'inotify_init' not found in [libc.dylib]
LoadError: cannot load such file -- rdf-aggregate-repo
LoadError: cannot load such file -- rdf-xsd
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static
LoadError: cannot load such file -- spring
Did you mean?  stringio
LoadError: cannot load such file -- spring-watcher-listen
LoadError: cannot load such file -- sprockets-rails
LoadError: cannot load such file -- turbolinks-source
[250/391] require_relative './db/seeds.rb'Cleaning out database...
[251/391] require_relative './db/seeds/admin.rb'Creating admin...
[252/391] require_relative './db/seeds/advanced_users.rb'Creating Advanced Users...
[253/391] require_relative './db/seeds/companies.rb'Creating Companies...
[254/391] require_relative './db/seeds/engines.rb'Creating Engines...
[255/391] require_relative './db/seeds/game_purchases.rb'Creating Game Purchases...
[256/391] require_relative './db/seeds/games.rb'Creating Games...
[257/391] require_relative './db/seeds/genres.rb'Creating Genres...
[258/391] require_relative './db/seeds/platforms.rb'Creating Platforms...
[259/391] require_relative './db/seeds/series.rb'Creating Series...
[260/391] require_relative './db/seeds/stores.rb'Creating Stores...
[261/391] require_relative './db/seeds/users.rb'Creating Users...
[1/28] require_relative './db/seeds.rb'Cleaning out database...
[2/28] require_relative './db/seeds/games.rb'Creating Games...
Naming all Modules
Naming Object/Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:1:in `<top (required)>'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/real_stdlib.rb:77:in `const_get'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/real_stdlib.rb:77:in `call'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/real_stdlib.rb:77:in `real_const_get'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/constant_cache.rb:157:in `block in dfs_module'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/constant_cache.rb:145:in `each'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/constant_cache.rb:145:in `dfs_module'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/constant_cache.rb:70:in `initialize'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/gem-generator-tracepoint/tracer.rb:54:in `new'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/gem-generator-tracepoint/tracer.rb:54:in `new'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/hidden-definition-finder.rb:68:in `constant_cache'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/hidden-definition-finder.rb:75:in `all_modules_and_aliases'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/hidden-definition-finder.rb:44:in `main'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/hidden-definition-finder.rb:38:in `main'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/bin/srb-rbi:232:in `block in make_step'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/bin/srb-rbi:224:in `main'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/bin/srb-rbi:237:in `<main>'
/Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- sorted_set (LoadError)
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:2:in `<top (required)>'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/real_stdlib.rb:77:in `const_get'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/real_stdlib.rb:77:in `call'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/real_stdlib.rb:77:in `real_const_get'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/constant_cache.rb:157:in `block in dfs_module'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/constant_cache.rb:145:in `each'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/constant_cache.rb:145:in `dfs_module'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/constant_cache.rb:70:in `initialize'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/gem-generator-tracepoint/tracer.rb:54:in `new'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/gem-generator-tracepoint/tracer.rb:54:in `new'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/hidden-definition-finder.rb:68:in `constant_cache'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/hidden-definition-finder.rb:75:in `all_modules_and_aliases'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/hidden-definition-finder.rb:44:in `main'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/hidden-definition-finder.rb:38:in `main'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/bin/srb-rbi:232:in `block in make_step'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/bin/srb-rbi:224:in `main'
	from /Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/bin/srb-rbi:237:in `<main>'
```

This error is being triggered by this file in Ruby: https://github.com/ruby/ruby/blob/be9b5553a3ae3a90c73d4c11786cb1a813e915f6/lib/set/sorted_set.rb

#### Expected behavior

I'd expect the hidden definitions generation not to error or quit part-way through.

- - -

If I add sorted_set to my Gemfile, the error does go away, but 1) adding the gem shouldn't be necessary, and 2) it errors again later about webrick 😒 

```
Naming RDocwebrick is not found. You may need to `gem install webrick` to install webrick.
```

Really, it seems to actually just abort entirely without webrick, which isn't great. I'm not sure if we need to ask the upstream Ruby core team to change [this code](https://github.com/ruby/ruby/blob/d5dfc3f2c833d62e4e0fb3145ed729f48b8e2a66/lib/rdoc/servlet.rb#L7-L11), or if we have an allowlist/denylist system somewhere for files in Ruby core we don't want to try running?

**Comment by connorshea** [comment]
After applying the change from my PR, and then adding the `sorted_set` and `webrick` gems, I now run into a new issue when generating the hidden definitions on Ruby 3:

```
/Users/connorshea/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6164/lib/hidden-definition-finder.rb:151:in `write_constants': /var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20201226-41912-fdk2xa/reflection.rbi had unexpected errors. Check this file for a clue: /var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20201226-41912-fdk2xa/reflection.json.err (RuntimeError)
```

The contents of that file are:

```
/var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20201226-41912-fdk2xa/reflection.rbi:375562: Parent of class `Random` redefined from `Object` to `Random::Base` https://srb.help/5012
      375562 |class Random < Random::Base
                             ^^^^^^^^^^^^
```

So it looks like the parent class of Random changed in this commit: https://github.com/ruby/ruby/commit/f4d5273989ae8d6569a62b126b2774706b86fbf5#diff-32cd45cbdc2d400fa3c2d0f7889e737f7837404a0bf31692c9e7ef014cfba568

I'm not sure how we should resolve this in the random.rbi stdlib file, I assume we had some similar changes in Ruby 2.6 or 2.7 but I can't remember off the top of my head how those were fixed.

**Comment by michaljanocko** [comment]
Hi, what will Sorbet look like now that Ruby has its own typing option?

**Comment by DanielGilchrist** [comment]
> Hi, what will Sorbet look like now that Ruby has its own typing option?

Hi! This section in the docs should answer your question https://sorbet.org/docs/faq#when-ruby-3-gets-types-what-will-the-migration-plan-look-like

If you have any more questions there is a slack group that can be found here https://sorbet.org/slack

**Comment by cguess** [comment]
Is there any movement on Ruby 3.0 support? I'm currently getting errors while (it seems) trying to generate signatures for Sorbet itself. I've attached it below:
```
Generating: sorbet/config
Reusing existing config file: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static
/Users/christopher/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6346/lib/gem-generator-tracepoint/tracepoint_serializer.rb:35:in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes) (ArgumentError)
	from /Users/christopher/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6346/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /Users/christopher/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6346/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /Users/christopher/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6346/lib/gem-generator-tracepoint.rb:43:in `main'
	from /Users/christopher/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6346/bin/srb-rbi:232:in `block in make_step'
	from /Users/christopher/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6346/bin/srb-rbi:118:in `init'
	from /Users/christopher/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6346/bin/srb-rbi:196:in `main'
	from /Users/christopher/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6346/bin/srb-rbi:237:in `<main>'
```

**Comment by TSMMark** [comment]
Sorbet also crashes on some new Ruby 3.0.0 syntax like hash destructuring, e.g.

```ruby
my_hash = { foo:, bar: }
puts foo
puts bar
```

**Comment by demurgos** [comment]
Ruby 3.0 is now the default version on Arch Linux. What is the current state of support of sorbet?

**Comment by anujbiyani** [comment]
Any progress on this? I'd love Ruby 3 support!

**Comment by Morriar** [comment]
I'm not from the core team but I can give an update on what we do at Shopify:

* We use Sorbet in our monolith which runs on Ruby 3.0 since a few months ago and everything is smooth 👍 
* We've been pushing changes to Sorbet to support most of the Ruby 3.0 features and will be continuing to do so for the missing ones
* One difference with this issue is that we do not use the `srb rbi` tooling: all RBI generation is done thanks to [Tapioca](https://github.com/Shopify/tapioca) for gem as well as for DSLs
* Sorbet is the de facto solution for Ruby Typing at Shopify and all our projects (regardless of the Ruby version used) are encouraged to use it
* We do not plan to migrate to Ruby RBS for the time being as it does not cover our needs

You can find more info about our plans for Ruby typing and Sorbet on our engineering blog:
* https://shopify.engineering/static-typing-ruby
* https://shopify.engineering/adopting-sorbet
* https://shopify.engineering/the-state-of-ruby-static-typing-at-shopify

Hope that helps!

**Comment by connorshea** [comment]
My Rails app is much much much smaller than Shopify's, but I wrote a blog post about how I use Sorbet. I haven't tested it in a while (still on 2.7) but I'm fairly certain the setup I have will work in Ruby 3 since it avoids the srb rbi tooling: https://connorshea.gitlab.io/blog/how-i-write-and-maintain-type-sigs-in-my-rails-app-with-sorbet.html

I think my setup is somewhat similar to Shopify's, albeit with sorbet-rails instead of the Tapioca DSL generators :)

**Comment by soberstadt** [comment]
I have moved two smaller rails apps to using a rake task like @connorshea and Ruby 3 and it's working great! Thanks for sharing!

**Comment by jez** [comment]
This issue seems stale, and is too wide ranging. If there are specific problems using Sorbet with Ruby 3.0, feel free to open new, individual issues, and we'll work through them as needed.
