### ISSUE TITLE
Bad error message when using self.class in a module

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#397]
[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20BadModule%0A%20%20def%20foo%3B%20self.class%3B%20end%0Aend%0A%0Amodule%20OkModule%0A%20%20include%20Kernel%0A%20%20def%20foo%3B%20self.class%3B%20end%0Aend%0A%0Aclass%20BadClass%20%3C%20BasicObject%0A%20%20include%20%3A%3ABadModule%0Aend%0A%0Aclass%20OkClass%20%3C%20BasicObject%0A%20%20include%20%3A%3AOkModule%0Aend%0A%0Aputs%20OkClass.new.foo%20%23%20unexpected%20missing%20method%20error%0Aputs%20BadClass.new.foo%20%23%20expected%20missing%20method%20error
)

Input:

```ruby
# typed: true

module BadModule
  def foo; self.class; end
end

module OkModule
  include Kernel
  def foo; self.class; end
end

class BadClass < BasicObject
  include ::BadModule
end

class OkClass < BasicObject
  include ::OkModule
end

puts OkClass.new.foo # unexpected missing method error
puts BadClass.new.foo # expected missing method error
```

Observed output:

```
editor.rb:4: Method class does not exist on BadModule https://sorbet.org/docs/error-reference#7003
     4 |  def foo; self.class; end
                   ^^^^^^^^^^
  Did you mean to `include Object` in this module?
    ???: Did you mean: Object#class?

editor.rb:9: Method class does not exist on OkModule https://sorbet.org/docs/error-reference#7003
     9 |  def foo; self.class; end
                   ^^^^^^^^^^
  Did you mean to `include Object` in this module?
    ???: Did you mean: Object#class?
Errors: 2
```

Observed runtime behavior:

```
❯ ruby foo.rb
OkClass
editor.rb:4:in `foo': undefined method `class' for #<BadClass:0x00007f91a50965f8> (NoMethodError)
        from editor.rb:21:in `<main>'
```

Expected behavior:

The static system should match the runtime; we should only emit a missing method error for the class that does not `include Kernel`.

- - -

This is potentially a number of bugs. The other is that we suggest `include Object`, when `Object` is a class, not a module and thus can't be included.

Also, we suggest that the owner for `#class` is `Object`. While it's true that the documentation for `#class` lives on `Object`, merely including `Kernel` is sufficient to get access to the method, so I think Sorbet should define `#class` on `Kernel`. Right now, `class` only exists in our symbol table because we enter it as an intrinsic method; we don't actually mention it in an RBI file.

**Comment by jez** [comment]
Looks like this is fixed. Not sure when.
