### ISSUE TITLE
Runtime rejects sig on method_added and singleton_method_added but srb complains about missing signature

### ISSUE THREAD

**Issue by jochenseeber** [sorbet/sorbet#4059]
Issue cannot be reproduced on sorbet.run since it involves running srb

#### Input

Given a module where `method_added` and `singleton_method_added` have a signature:

```ruby
# typed: strict
# frozen_string_literal: true

require "sorbet-runtime"

module WithSig
  extend T::Sig

  sig { params(name: Symbol).void }
  def singleton_method_added(name)
    super
  end

  sig { params(name: Symbol).void }
  def method_added(name)
    super
  end
end
```

#### Observed output

The runtime complains about the signatures:

```
$ ruby test_sig.rb  
Traceback (most recent call last):
	3: from test_sig.rb:6:in `<main>'
	2: from test_sig.rb:10:in `<module:WithSig>'
	1: from /Users/jochen/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6322/lib/types/private/methods/_methods.rb:447:in `method_added'
/Users/jochen/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6322/lib/types/private/methods/_methods.rb:183:in `_on_method_added': Putting a `sig` on `singleton_method_added` is not supported (sorbet-runtime uses this method internally to perform `sig` validation logic) (RuntimeError)
```

#### Input

Given the same code without signatures:

```ruby
# typed: strict
# frozen_string_literal: true

require "sorbet-runtime"

module WithoutSig
  extend T::Sig

  def singleton_method_added(name)
    super
  end

  def method_added(name)
    super
  end
end
```

#### Observed output

Running `srb tc` complains about missing signatures

```
$ bin/srb tc      
test_nosig.rb:9: This function does not have a sig https://srb.help/7017
     9 |  def singleton_method_added(name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

test_nosig.rb:13: This function does not have a sig https://srb.help/7017
    13 |  def method_added(name)
          ^^^^^^^^^^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

Running `srb tc` should not complain about the missing signatures

Complete code is attached here: [sorbet.zip](https://github.com/sorbet/sorbet/files/6093902/sorbet.zip)

**Comment by paracycle** [comment]
I think the fix is to use the `T::Sig::WithoutRuntime.sig` instead of `sig` as in:
```ruby
# typed: strict
# frozen_string_literal: true

require "sorbet-runtime"

module WithSig
  T::Sig::WithoutRuntime.sig { params(name: Symbol).void }
  def singleton_method_added(name)
    super
  end

  T::Sig::WithoutRuntime.sig { params(name: Symbol).void }
  def method_added(name)
    super
  end
end
```

That should get processed by the static checker as normal but would be ignored by the runtime checker.

**Comment by jochenseeber** [comment]
Thanks, that solved it
