### ISSUE TITLE
Module#< comparison against module with mixes_in_class_methods could be smarter

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#4127]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20MyInterface%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20def%20self.my_interface_self%3B%20end%0A%20%20def%20my_interface_instance%3B%20end%0A%0A%20%20module%20ClassMethods%0A%20%20%20%20def%20my_interface_class_method%3B%20end%0A%20%20end%0A%20%20mixes_in_class_methods(ClassMethods)%0Aend%0Aclass%20Parent%3B%20end%0Aclass%20Child%20%3C%20Parent%0A%20%20include%20MyInterface%0Aend%0A%0Asig%20%7Bparams(x%3A%20T.class_of(Parent)).void%7D%0Adef%20example(x)%0A%20%20if%20x%20%3C%20MyInterface%0A%20%20%20%20%23%20Should%20be%20allowed.%0A%20%20%20%20%23%20x%20%3C%20MyInterface%20should%20imply%20that%0A%20%20%20%20%23%20%20%20T.let(x%2C%20MyInterface%3A%3AClassMethods)%0A%20%20%20%20%23%20holds%2C%20like%20how%20x%20%3C%20MyClass%20implies%20that%0A%20%20%20%20%23%20%20%20T.let(x%2C%20T.class_of(MyClass))%0A%20%20%20%20%23%20holds.%20Importantly%2C%20it%20should%20not%20imply%20that%0A%20%20%20%20%23%20%20%20T.let(x%2C%20T.class_of(MyInterface))%0A%20%20%20%20%23%20holds%2C%20because%20the%20singleton%20class%20of%20a%20module%0A%20%20%20%20%23%20can%20never%20be%20mixed%20into%20a%20child%20class%20(neither%0A%20%20%20%20%23%20include%20nor%20extend%20does%20this).%0A%20%20%20%20x.my_interface_class_method%0A%0A%20%20%20%20%23%20Based%20on%20%5E%2C%20should%20show%0A%20%20%20%20%23%20%20%20T.all(T.class_of(Parent)%2C%20MyInterface%3A%3AClassMethods)%0A%20%20%20%20T.reveal_type(x)%0A%0A%20%20%20%20%23%20Should%20be%20rejected.%0A%20%20%20%20%23%20(%60self.%60%20methods%20on%20modules%20are%20never%20mixed%20into%20children)%0A%20%20%20%20x.my_interface_self%0A%0A%20%20%20%20%23%20Should%20be%20rejected.%0A%20%20%20%20%23%20(x%20is%20a%20singleton%20class%20object%2C%20not%20an%20instance%20of%20the%20class)%0A%20%20%20%20x.my_interface_instance%0A%20%20end%0Aend)

```ruby
# typed: true
extend T::Sig

module MyInterface
  extend T::Helpers

  def self.my_interface_self; end
  def my_interface_instance; end

  module ClassMethods
    def my_interface_class_method; end
  end
  mixes_in_class_methods(ClassMethods)
end
class Parent; end
class Child < Parent
  include MyInterface
end

sig {params(x: T.class_of(Parent)).void}
def example(x)
  if x < MyInterface
    # Should be allowed.
    # x < MyInterface should imply that
    #   T.let(x, MyInterface::ClassMethods)
    # holds, like how x < MyClass implies that
    #   T.let(x, T.class_of(MyClass))
    # holds. Importantly, it should not imply that
    #   T.let(x, T.class_of(MyInterface))
    # holds, because the singleton class of a module
    # can never be mixed into a child class (neither
    # include nor extend does this).
    x.my_interface_class_method

    # Based on ^, should show
    #   T.all(T.class_of(Parent), MyInterface::ClassMethods)
    T.reveal_type(x)

    # Should be rejected.
    # (`self.` methods on modules are never mixed into children)
    x.my_interface_self

    # Should be rejected.
    # (x is a singleton class object, not an instance of the class)
    x.my_interface_instance
  end
end
```

#### Observed output

```
editor.rb:33: Method my_interface_class_method does not exist on T.class_of(Parent) https://srb.help/7003
    33 |    x.my_interface_class_method
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got T.class_of(Parent) originating from:
    editor.rb:21:
    21 |def example(x)
                    ^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:33: Replace with private_class_method
    33 |    x.my_interface_class_method
              ^^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:37: Revealed type: T.class_of(Parent) https://srb.help/7014
    37 |    T.reveal_type(x)
            ^^^^^^^^^^^^^^^^
  Got T.class_of(Parent) originating from:
    editor.rb:21:
    21 |def example(x)
                    ^

editor.rb:41: Method my_interface_self does not exist on T.class_of(Parent) https://srb.help/7003
    41 |    x.my_interface_self
            ^^^^^^^^^^^^^^^^^^^
  Got T.class_of(Parent) originating from:
    editor.rb:21:
    21 |def example(x)
                    ^

editor.rb:45: Method my_interface_instance does not exist on T.class_of(Parent) https://srb.help/7003
    45 |    x.my_interface_instance
            ^^^^^^^^^^^^^^^^^^^^^^^
  Got T.class_of(Parent) originating from:
    editor.rb:21:
    21 |def example(x)
                    ^
Errors: 4
```

#### Expected behavior

First error above is gone, type revealed in is now a `T.all(...)`

```
editor.rb:37: Revealed type: T.all(T.class_of(Parent), MyInterface::ClassMethods) https://srb.help/7014
    37 |    T.reveal_type(x)
            ^^^^^^^^^^^^^^^^
  Got T.class_of(Parent) originating from:
    editor.rb:21:
    21 |def example(x)
                    ^

editor.rb:41: Method my_interface_self does not exist on T.class_of(Parent) https://srb.help/7003
    41 |    x.my_interface_self
            ^^^^^^^^^^^^^^^^^^^
  Got T.class_of(Parent) originating from:
    editor.rb:21:
    21 |def example(x)
                    ^

editor.rb:45: Method my_interface_instance does not exist on T.class_of(Parent) https://srb.help/7003
    45 |    x.my_interface_instance
            ^^^^^^^^^^^^^^^^^^^^^^^
  Got T.class_of(Parent) originating from:
    editor.rb:21:
    21 |def example(x)
                    ^
Errors: 3
```

Reasoning why is explained in comments.

- - -

While reasoning through that this is sensible, I assembled this example, to help drive home how these things work.

<details>

<summary> <strong>→ Click to expand more context<strong> 🔍 </summary>

```ruby
# typed: true
extend T::Sig

module Sharding
  extend T::Helpers

  module ClassMethods
    def almost_class_method; end
  end

  def instance_method; end
  def self.real_class_method; end

  mixes_in_class_methods(ClassMethods)
end

class MyModel
  include Sharding
end

# -- standard stuff, not surprising at all --
my_model = MyModel.new
my_model.instance_method              # yep, ok
my_model.real_class_method            # nope, correctly rejected
my_model.almost_class_method          # nope, correctly rejected
T.let(my_model, Sharding)             # yep, ok
T.let(MyModel, Sharding)              # nope, correctly rejected

# -- mind bending stuff starts here --

# mixes_in_class_methods DOESN'T actually mix into itself
# (only on inclusion):
Sharding.real_class_method            # yep, ok
Sharding.almost_class_method          # nope, correctly rejected

# ... but including/extending a module never brings that module's
# `self.` methods:
MyModel.real_class_method             # nope, correctly rejected
MyModel.almost_class_method           # yep, ok

# :say-what: So now what? 🤔
# Well, clearly:
T.let(MyModel, T.class_of(MyModel))   # yep, ok
T.let(Sharding, T.class_of(Sharding)) # yep, ok

# But then what about...
T.let(MyModel, T.class_of(Sharding))
# well, no, because that would imply that it's ok to call
# MyModel.real_class_method, but in fact it's not

# Or what about...
T.let(Sharding, T.class_of(MyModel))
# well, again no, because that would imply that it's ok to call
# Sharding.almost_class_method, but in fact it's not. (why? because
# mixes_in_class_methods(Sharding) is almost like having written
# `extend Sharding::ClassMethods` in the child class, which means
# that `T.class_of(MyModel)` is a subtype of `Sharding::ClassMethods`,
# and values of this type should the `almost_class_method` method,
# But the `Sharding` class object doesn't)

# -------------------------------------------------------------------
# So this is clearly all very confusing.
#
# Maybe one way forward would be to bite the bullet and make
# mixes_in_class_methods also put the methods on the top? (that is,
# on the `Sharding` object)
#
# Because then I think it would be ok for `klass < Sharding` to imply
#   T.let(klass, Sharding::ClassModules)
# but I think we would still not want to say
#   T.let(klass, T.class_of(Sharding))
# Or maybe it's enough to ONLY do this for `<`, NOT for `<=` (and
# not make any changes to how mixes_in_classes_works at runtime)

sig {params(mod: Module).void}
def example1(mod)
  if mod < Integer
    # https://github.com/sorbet/sorbet/issues/1910
    # This is a bug, it should show `T.class_of(Integer)`
    # (I'm 90% sure)
    T.reveal_type(mod)                # => Module
  end
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20Sharding%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20module%20ClassMethods%0A%20%20%20%20def%20almost_class_method%3B%20end%0A%20%20end%0A%0A%20%20def%20instance_method%3B%20end%0A%20%20def%20self.real_class_method%3B%20end%0A%0A%20%20mixes_in_class_methods(ClassMethods)%0Aend%0A%0Aclass%20MyModel%0A%20%20include%20Sharding%0Aend%0A%0A%23%20--%20standard%20stuff%2C%20not%20surprising%20at%20all%20--%0Amy_model%20%3D%20MyModel.new%0Amy_model.instance_method%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20yep%2C%20ok%0Amy_model.real_class_method%20%20%20%20%20%20%20%20%20%20%20%20%23%20nope%2C%20correctly%20rejected%0Amy_model.almost_class_method%20%20%20%20%20%20%20%20%20%20%23%20nope%2C%20correctly%20rejected%0AT.let(my_model%2C%20Sharding)%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20yep%2C%20ok%0AT.let(MyModel%2C%20Sharding)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20nope%2C%20correctly%20rejected%0A%0A%23%20--%20mind%20bending%20stuff%20starts%20here%20--%0A%0A%23%20mixes_in_class_methods%20DOESN'T%20actually%20mix%20into%20itself%0A%23%20(only%20on%20inclusion)%3A%0ASharding.real_class_method%20%20%20%20%20%20%20%20%20%20%20%20%23%20yep%2C%20ok%0ASharding.almost_class_method%20%20%20%20%20%20%20%20%20%20%23%20nope%2C%20correctly%20rejected%0A%0A%23%20...%20but%20including%2Fextending%20a%20module%20never%20brings%20that%20module's%0A%23%20%60self.%60%20methods%3A%0AMyModel.real_class_method%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20nope%2C%20correctly%20rejected%0AMyModel.almost_class_method%20%20%20%20%20%20%20%20%20%20%20%23%20yep%2C%20ok%0A%0A%23%20%3Asay-what%3A%20So%20now%20what%3F%20%F0%9F%A4%94%0A%23%20Well%2C%20clearly%3A%0AT.let(MyModel%2C%20T.class_of(MyModel))%20%20%20%23%20yep%2C%20ok%0AT.let(Sharding%2C%20T.class_of(Sharding))%20%23%20yep%2C%20ok%0A%0A%23%20But%20then%20what%20about...%0AT.let(MyModel%2C%20T.class_of(Sharding))%0A%23%20well%2C%20no%2C%20because%20that%20would%20imply%20that%20it's%20ok%20to%20call%0A%23%20MyModel.real_class_method%2C%20but%20in%20fact%20it's%20not%0A%0A%23%20Or%20what%20about...%0AT.let(Sharding%2C%20T.class_of(MyModel))%0A%23%20well%2C%20again%20no%2C%20because%20that%20would%20imply%20that%20it's%20ok%20to%20call%0A%23%20Sharding.almost_class_method%2C%20but%20in%20fact%20it's%20not.%20(why%3F%20because%0A%23%20mixes_in_class_methods(Sharding)%20is%20almost%20like%20having%20written%0A%23%20%60extend%20Sharding%3A%3AClassMethods%60%20in%20the%20child%20class%2C%20which%20means%0A%23%20that%20%60T.class_of(MyModel)%60%20is%20a%20subtype%20of%20%60Sharding%3A%3AClassMethods%60%2C%0A%23%20and%20values%20of%20this%20type%20should%20the%20%60almost_class_method%60%20method%2C%0A%23%20But%20the%20%60Sharding%60%20class%20object%20doesn't)%0A%0A%23%20-------------------------------------------------------------------%0A%23%20So%20this%20is%20clearly%20all%20very%20confusing.%0A%23%0A%23%20Maybe%20one%20way%20forward%20would%20be%20to%20bite%20the%20bullet%20and%20make%0A%23%20mixes_in_class_methods%20also%20put%20the%20methods%20on%20the%20top%3F%20(that%20is%2C%0A%23%20on%20the%20%60Sharding%60%20object)%0A%23%0A%23%20Because%20then%20I%20think%20it%20would%20be%20ok%20for%20%60klass%20%3C%20Sharding%60%20to%20imply%0A%23%20%20%20T.let(klass%2C%20Sharding%3A%3AClassModules)%0A%23%20but%20I%20think%20we%20would%20still%20not%20want%20to%20say%0A%23%20%20%20T.let(klass%2C%20T.class_of(Sharding))%0A%23%20Or%20maybe%20it's%20enough%20to%20ONLY%20do%20this%20for%20%60%3C%60%2C%20NOT%20for%20%60%3C%3D%60%20(and%0A%23%20not%20make%20any%20changes%20to%20how%20mixes_in_classes_works%20at%20runtime)%0A%0Asig%20%7Bparams(mod%3A%20Module).void%7D%0Adef%20example1(mod)%0A%20%20if%20mod%20%3C%20Integer%0A%20%20%20%20%23%20https%3A%2F%2Fgithub.com%2Fsorbet%2Fsorbet%2Fissues%2F1910%0A%20%20%20%20%23%20This%20is%20a%20bug%2C%20it%20should%20show%20%60T.class_of(Integer)%60%0A%20%20%20%20%23%20(I'm%2090%25%20sure)%0A%20%20%20%20T.reveal_type(mod)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20%3D%3E%20Module%0A%20%20end%0Aend)

</details>

**Comment by paracycle** [comment]
For your initial example with `Parent` and `Child` classes, if a module evaluates `mod < MyInterface` to `true` then it should evaluate `mod.singleton_class < MyInterface::ClassMethods` to `true` as well. And you are correct that the same implication does not hold for `<=`, since `MyInterface` fulfills the equality for the first check but `MyInterface.singleton_class <= MyInterface::ClassMethods` is `false`.

So, in the cases where you can make sure that the RHS of `Module#<` is a `mixes_in_class_methods` module, then you should be able to refine `mod` inside the block to an intersection of its original type with the type(s) of the mixed in module(s).

In summary, fully agreed and this would be the expected behaviour.

**Comment by jez** [comment]
This does not actually work like I first thought it would. Here's a counter example

```ruby
# typed: true
extend T::Sig

module MyInterface
  extend T::Helpers

  def self.my_interface_self; end
  def my_interface_instance; end

  module ClassMethods
    def my_interface_class_method; end
  end
  mixes_in_class_methods(ClassMethods)
end

module MyInterfaceChild
  include MyInterface
end

class Parent
  include MyInterfaceChild
end

sig {params(x: T.class_of(Parent)).void}
def example(x)
  if x < MyInterface
    T.reveal_type(x)
    x.my_interface_class_method
  end
end

example(Parent)
```

When run, this is the output:

```
❯ ruby -r./gems/sorbet-runtime/lib/sorbet-runtime issues_4127.rb
issues_4127.rb:28:in `example': undefined method `my_interface_class_method' for Parent:Class (NoMethodError)

    x.my_interface_class_method
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from issues_4127.rb:32:in `<main>'
```

The problem is outlined in [this blog post](https://blog.jez.io/inheritance-in-ruby/#the-mixes_in_class_methods-annotation), namely:

> The `mixes_in_class_methods` annotation is kind of dumb: it doesn’t pay attention to whether the `include` happens into a class, or into another module. And if it happens into another module, it will still act like the `extend` was written right there

There are a handful of ways forward:

- Change this fact about how `mixes_in_class_methods` works. This would be a breaking change, but might not be that disruptive in practice, because my hunch is that no one actually wants this behavior, they're just forced to deal with it.

- Implement first-class support for `ActiveSupport::Concern`, possibly alongside something like `T::Concern` for codebases that don't want to take a dependency on `ActiveSupport` but want the same functionality. (Another [blog post](https://blog.jez.io/concern-inheritance/) which explains this).) I have no great idea for how to model this in Sorbet, but I don't yet think that Sorbet's current architecture prevents building such a feature (e.g. I'm optimistic)

- Introduce some new Sorbet feature like `mixes_in_class_methods_NEW` which works better here. This would only be a last-resort sort of situation—I think that first-class `Concern` support would make adoption easier in existing Ruby codebases, vs learning another Sorbet-specific concept.

- Limit support to only simple cases. In particular, if:

    1. the LHS is a subtype of `Class`, and
    2. the LHS does not already a subtype of the RHS
    
  then I think that Sorbet can know that if some child of the LHS were to have the RHS included into it, then it must necessarily be the case that the RHS was included into a class context, where the RHS::ClassMethods would then always be inherited, no matter the type.
  
  Apart from the fact that it's a partial solution, I don't think this feature has any drawbacks, so I am likely to take a stab at it.
  
- - - - - -

This is similar but different from this ticket:

#8027

which is a limitation of `Module#<` which is blocked on #7027 for full support.
