### ISSUE TITLE
`srb init` segmentation fault on `rails new` app

### ISSUE THREAD

**Issue by v-n-suadicani** [sorbet/sorbet#4176]
#### Reproduction

Run `rails new example`. Add the following to the Gemfile:
```
gem 'sorbet', group: :development
gem 'sorbet-runtime'
gem 'sorbet-rails'
```
Run `bundle install` (I get these versions)
```
$ ruby --version
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
$ rails --version
Rails 6.0.3.6
$ srb --version
Sorbet typechecker 0.5.6389 git 0c54dbfaf97ed30999f8e6b49ff20a8aa082840a debug_symbols=true clean=0
```

Now run `srb init`

#### Observed output

```
$ srb init

Hey there!

This script will get this project ready to use with Sorbet by creating a
sorbet/ folder for your project. It will contain:

- a config file
- a bunch of 'RBI files'

RBI stands for 'Ruby Interface'; these files define classes, methods, and
constants that exist, but which Sorbet doesn't always know about.

Heads up:

To set up your project, this script will take two potentially destructive
actions:

1.  It will require every file in your project. Specifically, every script in
    your project will be run, unless that script checks if __FILE__ == $PROGRAM_NAME
    before running any code, or has the magic comment # typed: ignore in it.

2.  It will add a comment to the top of every file (like # typed: false or
    # typed: true, depending on how many errors were found in that file.)

Would you like to continue? [Y/n] y
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
LoadError: cannot load such file -- action_controller/middleware
LoadError: cannot load such file -- image_processing
LoadError: cannot load such file -- webrobots
LoadError: cannot load such file -- rack/session/dalli
LoadError: cannot load such file -- railties
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static
LoadError: cannot load such file -- spring
LoadError: cannot load such file -- spring-watcher-listen
LoadError: cannot load such file -- sprockets-rails
LoadError: cannot load such file -- turbolinks-source
Generating: sorbet/rbi/hidden-definitions/
Requiring all of your code
Naming all Modules
Naming ActionCable::ServerGot NameError when trying to get nested name ActionCable::Server::ActiveRecordConnectionManagement_
Naming ActionControllerGot LoadError when trying to get nested name ActionController::Middleware
Naming ActionDispatch::SessionYou don't have dalli installed in your application. Please add it to your Gemfile and run bundle install
Got LoadError when trying to get nested name ActionDispatch::Session::MemCacheStore
Naming ActiveJob::QueueAdaptersGot LoadError when trying to get nested name ActiveJob::QueueAdapters::BackburnerAdapter
Got LoadError when trying to get nested name ActiveJob::QueueAdapters::DelayedJobAdapter
Got LoadError when trying to get nested name ActiveJob::QueueAdapters::QueAdapter
Got LoadError when trying to get nested name ActiveJob::QueueAdapters::QueueClassicAdapter
Got LoadError when trying to get nested name ActiveJob::QueueAdapters::ResqueAdapter
Got LoadError when trying to get nested name ActiveJob::QueueAdapters::SidekiqAdapter
Got LoadError when trying to get nested name ActiveJob::QueueAdapters::SneakersAdapter
Got LoadError when trying to get nested name ActiveJob::QueueAdapters::SuckerPunchAdapter
Naming ActiveRecordGot NameError when trying to get nested name ActiveRecord::DatabaseSelector_
Naming ActiveStorage::TransformersGot LoadError when trying to get nested name ActiveStorage::Transformers::ImageProcessingTransformer
Got LoadError when trying to get nested name ActiveStorage::Transformers::MiniMagickTransformer
Naming ActiveSupport::CacheThe Redis cache store requires the redis gem, version 4.0.1 or later. Please add it to your Gemfile: `gem "redis", "~> 4.0"`
Got Gem::LoadError when trying to get nested name ActiveSupport::Cache::RedisCacheStore
You don't have dalli installed in your application. Please add it to your Gemfile and run bundle install
Got LoadError when trying to get nested name ActiveSupport::Cache::MemCacheStore
Naming I18n::TestsGot ArgumentError when trying to get nested name I18n::Tests::Basics_
Got ArgumentError when trying to get nested name I18n::Tests::Defaults_
Got ArgumentError when trying to get nested name I18n::Tests::Interpolation_
Got ArgumentError when trying to get nested name I18n::Tests::Link_
Got ArgumentError when trying to get nested name I18n::Tests::Lookup_
Got ArgumentError when trying to get nested name I18n::Tests::Procs_
Got ArgumentError when trying to get nested name I18n::Tests::Pluralization_
Naming I18n::Tests::LocalizationGot ArgumentError when trying to get nested name I18n::Tests::Localization::Date_
Got ArgumentError when trying to get nested name I18n::Tests::Localization::DateTime_
Got ArgumentError when trying to get nested name I18n::Tests::Localization::Procs_
Got ArgumentError when trying to get nested name I18n::Tests::Localization::Time_
Naming Rack::HandlerGot LoadError when trying to get nested name Rack::Handler::LSWS
Got LoadError when trying to get nested name Rack::Handler::SCGI
Got LoadError when trying to get nested name Rack::Handler::Thin
Got LoadError when trying to get nested name Rack::Handler::FastCGI
Naming Rack::SessionGot LoadError when trying to get nested name Rack::Session::Memcache
Naming Selenium::WebDriverGot LoadError when trying to get nested name Selenium::WebDriver::PhantomJS
Naming Sprockets::AutoloadGot LoadError when trying to get nested name Sprockets::Autoload::Closure
Got LoadError when trying to get nested name Sprockets::Autoload::Babel
Got LoadError when trying to get nested name Sprockets::Autoload::CoffeeScript
Got LoadError when trying to get nested name Sprockets::Autoload::Eco
Got LoadError when trying to get nested name Sprockets::Autoload::EJS
Got LoadError when trying to get nested name Sprockets::Autoload::JSMinC
Got LoadError when trying to get nested name Sprockets::Autoload::Sass
Got LoadError when trying to get nested name Sprockets::Autoload::Uglifier
Got LoadError when trying to get nested name Sprockets::Autoload::YUI
Got LoadError when trying to get nested name Sprockets::Autoload::Zopfli
Naming ThreadSafeGot LoadError when trying to get nested name ThreadSafe::JRubyCacheBackend
Naming TiltGot LoadError when trying to get nested name Tilt::ErubisTemplate
Got LoadError when trying to get nested name Tilt::MarukuTemplate
Got LoadError when trying to get nested name Tilt::KramdownTemplate
Got LoadError when trying to get nested name Tilt::BlueClothTemplate
Got LoadError when trying to get nested name Tilt::RDiscountTemplate
Got LoadError when trying to get nested name Tilt::RedcarpetTemplate
Got LoadError when trying to get nested name Tilt::PandocTemplate
Got LoadError when trying to get nested name Tilt::AsciidoctorTemplate
Got LoadError when trying to get nested name Tilt::BabelTemplate
Got LoadError when trying to get nested name Tilt::CommonMarkerTemplate
Got LoadError when trying to get nested name Tilt::CoffeeScriptTemplate
Got LoadError when trying to get nested name Tilt::CreoleTemplate
Got LoadError when trying to get nested name Tilt::CoffeeScriptLiterateTemplate
Got LoadError when trying to get nested name Tilt::HamlTemplate
Got LoadError when trying to get nested name Tilt::LiquidTemplate
Got LoadError when trying to get nested name Tilt::LiveScriptTemplate
Got LoadError when trying to get nested name Tilt::LessTemplate
Got LoadError when trying to get nested name Tilt::MarkabyTemplate
Got LoadError when trying to get nested name Tilt::PrawnTemplate
Got LoadError when trying to get nested name Tilt::RedClothTemplate
Got LoadError when trying to get nested name Tilt::RstPandocTemplate
Got LoadError when trying to get nested name Tilt::RadiusTemplate
Got LoadError when trying to get nested name Tilt::TypeScriptTemplate
Got LoadError when trying to get nested name Tilt::WikiClothTemplate
Got LoadError when trying to get nested name Tilt::YajlTemplate
Naming WebConsoleGot NameError when trying to get nested name WebConsole::SourceLocation_
Generating /tmp/d20210426-2373768-9v8xb9/reflection.rbi with 5378 modules and 150 aliases
Printing your code's symbol table into /tmp/d20210426-2373768-9v8xb9/from-source.json
Printing /tmp/d20210426-2373768-9v8xb9/reflection.rbi's symbol table into /tmp/d20210426-2373768-9v8xb9/reflection.json
Reading /tmp/d20210426-2373768-9v8xb9/from-source.json
Reading /tmp/d20210426-2373768-9v8xb9/reflection.json
Building rbi id to symbol map
Building source id to symbol map
Writing /tmp/d20210426-2373768-9v8xb9/hidden.rbi.tmp
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:375: [BUG] Segmentation fault at 0x0000000000000010
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0020 p:---- s:0167 e:000166 CFUNC  :super_method
c:0019 p:0109 s:0163 e:000162 BLOCK  /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:375 [FINISH]
c:0018 p:---- s:0154 e:000153 CFUNC  :each
c:0017 p:0043 s:0150 e:000149 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:356
c:0016 p:0357 s:0139 e:000138 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:260
c:0015 p:0086 s:0112 e:000110 BLOCK  /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:207 [FINISH]
c:0014 p:---- s:0106 e:000105 CFUNC  :each
c:0013 p:0019 s:0102 E:0016b0 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:200
c:0012 p:0638 s:0090 E:001648 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:281
c:0011 p:0086 s:0063 E:001680 BLOCK  /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:207 [FINISH]
c:0010 p:---- s:0057 e:000056 CFUNC  :each
c:0009 p:0019 s:0053 E:001ce0 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:200
c:0008 p:0092 s:0041 E:001d78 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:169
c:0007 p:0051 s:0032 E:0022c0 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:49
c:0006 p:0005 s:0024 E:002620 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:38
c:0005 p:0032 s:0020 E:000c00 BLOCK  /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb-rbi:232
c:0004 p:0397 s:0017 E:000ea8 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb-rbi:121
c:0003 p:0363 s:0012 E:002590 METHOD /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb-rbi:196
c:0002 p:0124 s:0006 E:001940 EVAL   /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb-rbi:237 [FINISH]
c:0001 p:0000 s:0003 E:0013e0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb-rbi:237:in `<main>'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb-rbi:196:in `main'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb-rbi:121:in `init'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb-rbi:232:in `block in make_step'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:38:in `main'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:49:in `main'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:169:in `write_diff'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:200:in `serialize_constants'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:200:in `each'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:207:in `block in serialize_constants'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:281:in `serialize_class'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:200:in `serialize_constants'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:200:in `each'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:207:in `block in serialize_constants'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:260:in `serialize_class'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:356:in `serialize_methods'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:356:in `each'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:375:in `block in serialize_methods'
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:375:in `super_method'

-- Machine register context ------------------------------------------------
 RIP: 0x00007ff7b5af0bc4 RBP: 0x00007ff7b4fe3be8 RSP: 0x00007ffcc4fd1d50
 RAX: 0x0000000000000000 RBX: 0x000055984ead3140 RCX: 0x0000000000000000
 RDX: 0x0000000000000006 RDI: 0x0000000000000000 RSI: 0x0000559849c1d3b0
  R8: 0x0000559849c1d3b0  R9: 0x0000000000000023 R10: 0x0000000055550083
 R11: 0x0000000000000007 R12: 0x0000559851843778 R13: 0x0000000000000000
 R14: 0x0000559851843778 R15: 0x00005598459243a0 EFL: 0x0000000000010246

-- C level backtrace information -------------------------------------------
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(rb_vm_bugreport+0x573) [0x7ff7b5beb143] vm_dump.c:755
[0x7ff7b5a0e3ab]
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(sigsegv+0x4d) [0x7ff7b5b477dd] signal.c:946
/lib/x86_64-linux-gnu/libc.so.6(0x7ff7b5779210) [0x7ff7b5779210]
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(RCLASS_SUPER+0x0) [0x7ff7b5af0bc4] proc.c:3049
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(method_super_method) proc.c:3049
[0x7ff7b5bc2da0]
[0x7ff7b5bd075b]
[0x7ff7b5bd68c4]
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(rb_yield+0x29b) [0x7ff7b5bdaecb] vm.c:1044
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(rb_ary_each+0x3c) [0x7ff7b597808c] array.c:2135
[0x7ff7b5bc2da0]
[0x7ff7b5bd0821]
[0x7ff7b5bd68c4]
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(rb_yield+0x29b) [0x7ff7b5bdaecb] vm.c:1044
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(rb_ary_each+0x3c) [0x7ff7b597808c] array.c:2135
[0x7ff7b5bc2da0]
[0x7ff7b5bd0821]
[0x7ff7b5bd68c4]
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(rb_yield+0x29b) [0x7ff7b5bdaecb] vm.c:1044
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(rb_ary_each+0x3c) [0x7ff7b597808c] array.c:2135
[0x7ff7b5bc2da0]
[0x7ff7b5bd854b]
[0x7ff7b5bd0821]
[0x7ff7b5bd68c4]
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(rb_ec_exec_node+0xc1) [0x7ff7b5a12ee1] eval.c:278
/home/victor/.rvm/rubies/ruby-2.7.3/bin/../lib/libruby.so.2.7(ruby_run_node+0x4e) [0x7ff7b5a185ee] eval.c:336
/home/victor/.rvm/rubies/ruby-2.7.3/bin/ruby(main+0x5f) [0x559843eb717f] ./main.c:50

-- Other runtime information -----------------------------------------------

* Loaded script: /home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb-rbi

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 ruby2_keywords.rb
    5 /home/victor/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
[...snip...]
 3431 /home/victor/.rvm/gems/ruby-2.7.3/gems/thor-1.1.0/lib/thor/shell/html.rb

* Process memory map:

559843eb6000-559843eb7000 r--p 00000000 103:05 2647754                   /home/victor/.rvm/rubies/ruby-2.7.3/bin/ruby
559843eb7000-559843eb8000 r-xp 00001000 103:05 2647754                   /home/victor/.rvm/rubies/ruby-2.7.3/bin/ruby
559843eb8000-559843eb9000 r--p 00002000 103:05 2647754                   /home/victor/.rvm/rubies/ruby-2.7.3/bin/ruby
559843eb9000-559843eba000 r--p 00002000 103:05 2647754                   /home/victor/.rvm/rubies/ruby-2.7.3/bin/ruby
559843eba000-559843ebb000 rw-p 00003000 103:05 2647754                   /home/victor/.rvm/rubies/ruby-2.7.3/bin/ruby
559845814000-55985acbc000 rw-p 00000000 00:00 0                          [heap]
7ff794000000-7ff794021000 rw-p 00000000 00:00 0 
[...snip...]
7ff7b5d41000-7ff7b5d42000 r--p 0002c000 103:05 1968238                   /usr/lib/x86_64-linux-gnu/ld-2.31.so
7ff7b5d42000-7ff7b5d43000 rw-p 0002d000 103:05 1968238                   /usr/lib/x86_64-linux-gnu/ld-2.31.so
7ff7b5d43000-7ff7b5d44000 rw-p 00000000 00:00 0 
7ffcc47d7000-7ffcc4fd6000 rw-p 00000000 00:00 0                          [stack]
7ffcc4fdb000-7ffcc4fdf000 r--p 00000000 00:00 0                          [vvar]
7ffcc4fdf000-7ffcc4fe1000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]


/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb: line 120: 2373768 Aborted                 (core dumped) "$srb_rbi_path" "init"
```

These lines perhaps being key:
```
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/lib/hidden-definition-finder.rb:375: [BUG] Segmentation fault at 0x0000000000000010
[...]
/home/victor/.rvm/gems/ruby-2.7.3/gems/sorbet-0.5.6389/bin/srb: line 120: 2373768 Aborted                 (core dumped) "$srb_rbi_path" "init"
```

#### Expected behavior
No segmentation fault.

---

Interestingly, this seems to work perfectly fine with Ruby 2.7.2.

**Comment by paracycle** [comment]
This is a Ruby bug which exists on 2.6.7, 2.7.3, 3.0.1 and master: https://bugs.ruby-lang.org/issues/17780
