### ISSUE TITLE
hidden-definitions crashes with "too many open files"

### ISSUE THREAD

**Issue by bmulholland** [sorbet/sorbet#4211]
#### Input

`﻿﻿ulimit -n 8192 && bundle exec srb rbi hidden-definitions`

#### Observed output

```
Printing your code's symbol table into /var/folders/vz/wfs0t4g55xn0sjpnmf6d9jfc0000gn/T/d20210514-46292-agq1we/from-source.json
Traceback (most recent call last):
	6: from /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/sorbet-0.5.6403/bin/srb-rbi:237:in `<main>'
	5: from /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/sorbet-0.5.6403/bin/srb-rbi:224:in `main'
	4: from /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/sorbet-0.5.6403/bin/srb-rbi:232:in `block in make_step'
	3: from /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/sorbet-0.5.6403/lib/hidden-definition-finder.rb:38:in `main'
	2: from /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/sorbet-0.5.6403/lib/hidden-definition-finder.rb:47:in `main'
	1: from /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/sorbet-0.5.6403/lib/hidden-definition-finder.rb:104:in `write_constants'
/Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/sorbet-0.5.6403/lib/hidden-definition-finder.rb:104:in `popen': Too many open files - /var/folders/vz/wfs0t4g55xn0sjpnmf6d9jfc0000gn/T/d20210514-46292-agq1we/from-source.json.err (Errno::EMFILE)
```

#### Expected behavior

hidden definitions runs without crashing

- - -

Is there anything else I can try to debug this? Things to investigate? I can try cutting out code/gems/config to find the culprit - but what? Obviously this is only reproducible on my full project right now, and I don't know how to get to a minimal repro from here.

**Comment by bmulholland** [comment]
I changed ulimit to 20k and it worked - but that seems high, especially considering my project is very small. Any way to debug?

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
