### ISSUE TITLE
final attr_accessor with final class error

### ISSUE THREAD

**Issue by ippachi** [sorbet/sorbet#4240]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20User%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20final!%0A%0A%20%20sig(%3Afinal)%20%7B%20returns(Integer)%20%7D%0A%20%20attr_accessor%20%3Aid%0A%0A%20%20sig(%3Afinal)%20%7B%20params(id%3A%20Integer).void%20%7D%0A%20%20def%20initialize(id)%0A%20%20%20%20%40id%20%3D%20id%0A%20%20end%0Aend)

```ruby
# typed: strict

class User
  extend T::Sig
  extend T::Helpers

  final!

  sig(:final) { returns(Integer) }
  attr_accessor :id

  sig(:final) { params(id: Integer).void }
  def initialize(id)
    @id = id
  end
end
```

#### Observed output

```
No errors! Great job.
```

```
# runtime output

/Users/ippachi/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.6427/lib/types/private/methods/_methods.rb:193:in `_on_method_added': User was declared as final but its method `id=` was not declared as final (RuntimeError)
	from /Users/ippachi/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.6427/lib/types/private/methods/_methods.rb:488:in `method_added'
	from /Users/ippachi/playground/asdf.rb:12:in `attr_accessor'
	from /Users/ippachi/playground/asdf.rb:12:in `<class:User>'
	from /Users/ippachi/playground/asdf.rb:5:in `<main>'
```

#### Expected behavior

No error

- - -

Below code is working well

```ruby
# typed: strict

class User
  extend T::Sig
  extend T::Helpers

  final!

  sig(:final) { returns(Integer) }
  attr_reader :id

  sig(:final) { params(id: Integer).returns(Integer) }
  attr_writer :id

  sig(:final) { params(id: Integer).void }
  def initialize(id)
    @id = id
  end
end
```

**Comment by jez** [comment]
Thanks for the report.

This is somewhat tricky to properly fix. The `sig` DSL is stateful. The state is reset on the first subsequent method definition. `attr_accessor` defines two methods in one call, which will be tricky to support.

Thanks for posting a workaround as well (splitting the `attr_accessor` into `attr_reader` and `attr_writer`, which involves more typing but at least works with Sorbet).

If someone has a clever idea for how to implement a fix for this, please let me know.
