### ISSUE TITLE
Running `srb init` throws ArgumentError

### ISSUE THREAD

**Issue by benediktms** [sorbet/sorbet#4328]
#### Input

After initializing a new ruby project with a simple class:

```ruby
class Person
  def initialize(name, age, hobbies)
    @name = name
  end

  def introduce
    puts "Hi, my name is #{@name}."
  end
end
```
Gemfile:
```ruby
group :development do
  gem 'sorbet', '~> 0.5.6482'
  gem 'sorbet-runtime'
end
```

running the initialization command: 

```shell
srb init
```

#### Observed output

```
Hey there!

This script will get this project ready to use with Sorbet by creating a
sorbet/ folder for your project. It will contain:

- a config file
- a bunch of 'RBI files'

RBI stands for 'Ruby Interface'; these files define classes, methods, and
constants that exist, but which Sorbet doesn't always know about.

Heads up:

To set up your project, this script will take two potentially destructive
actions:

1.  It will require every file in your project. Specifically, every script in
    your project will be run, unless that script checks if __FILE__ == $PROGRAM_NAME
    before running any code, or has the magic comment # typed: ignore in it.

2.  It will add a comment to the top of every file (like # typed: false or
    # typed: true, depending on how many errors were found in that file.)

Would you like to continue? [Y/n] y
Generating: sorbet/config
Reusing existing config file: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
/home/benedikt/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6482/lib/gem-generator-tracepoint/tracepoint_serializer.rb:35:in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes) (ArgumentError)
        from /home/benedikt/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6482/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/benedikt/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6482/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/benedikt/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6482/lib/gem-generator-tracepoint.rb:43:in `main'
        from /home/benedikt/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6482/bin/srb-rbi:232:in `block in make_step'
        from /home/benedikt/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6482/bin/srb-rbi:118:in `init'
        from /home/benedikt/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6482/bin/srb-rbi:196:in `main'
        from /home/benedikt/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/sorbet-0.5.6482/bin/srb-rbi:237:in `<main>'
```

#### Expected behavior

For sorbet to set up the project.

Running on Ruby 3.0.0

**Comment by benediktms** [comment]
Apologies, I did not know Ruby 3 was not supported. This works for 2.7.3, so I'll close this,
