### ISSUE TITLE
Stack level too deep (SystemStackError) when calling String.to_json after T::Utils.run_all_sig_blocks

### ISSUE THREAD

**Issue by RyanBrushett** [sorbet/sorbet#4391]
#### Input

Can be reproduced with the following:
On a rails app w/ Sorbet Runtime, open a rails console, call `T::Utils.run_all_sig_blocks`, followed by `String.to_json`

```ruby
irb(main):001:0> T::Utils.run_all_sig_blocks
=> nil
irb(main):002:0> String.to_json
/Users/ryanbrushett/.gem/ruby/3.0.1/gems/activesupport-6.1.4/lib/active_support/core_ext/object/instance_variables.rb:15:in `instance_values': stack level too deep (SystemStackError)
```

#### Observed output

```
/Users/ryanbrushett/.gem/ruby/3.0.1/gems/activesupport-6.1.4/lib/active_support/core_ext/object/instance_variables.rb:15:in `instance_values': stack level too deep (SystemStackError)
```

#### Expected behavior

Something like this:

```ruby
irb(main):001:0> String.to_json
=> "{}"
```

## Troubleshooting

The exception shows that the problem gets thrown from `activesupport-6.1.4/lib/active_support/core_ext/object/instance_variables.rb:15` so, if we add a breakpoint there:

```ruby
  def instance_values
    require 'pry'
    binding.pry
    Hash[instance_variables.map { |name| [name[1..-1], instance_variable_get(name)] }]
  end
```

We can see that `instance_variables` will be `[:@__as_sorbet_type]`

```ruby
[1] pry(String)> instance_variables
=> [:@__as_sorbet_type]
```

Letting execution continue, we immediately hit the breakpoint again. `instance_variables` is now `[:@raw_type, :@name, :@nilable]`

```ruby
[1] pry(#<T::Types::Simple>)> instance_variables
=> [:@raw_type, :@name, :@nilable]
```

If you do `instance_variable_get(:@raw_type)`, the result is `String` and there's our recursion.

It looks like it's an issue with storing things on the type itself. Interesting.

cc @paracycle 

```ruby
[3] pry(#<T::Types::Simple>)> instance_variable_get(:@raw_type)
=> String
```

<details>
  <summary><b>Click to see my full shell Output</b></summary>

```ruby
Running via Spring preloader in process 57947
Loading development environment (Rails 6.1.4)
irb(main):001:0> T::Utils.run_all_sig_blocks
=> nil
irb(main):002:0> String.to_json

From: /Users/ryanbrushett/.gem/ruby/3.0.1/gems/activesupport-6.1.4/lib/active_support/core_ext/object/instance_variables.rb:16 Object#instance_values:

    14: def instance_values
    15:   require 'pry'
 => 16:   binding.pry
    17:   Hash[instance_variables.map { |name| [name[1..-1], instance_variable_get(name)] }]
    18: end

[1] pry(String)> instance_variables
=> [:@__as_sorbet_type]
[2] pry(String)> exit

From: /Users/ryanbrushett/.gem/ruby/3.0.1/gems/activesupport-6.1.4/lib/active_support/core_ext/object/instance_variables.rb:16 Object#instance_values:

    14: def instance_values
    15:   require 'pry'
 => 16:   binding.pry
    17:   Hash[instance_variables.map { |name| [name[1..-1], instance_variable_get(name)] }]
    18: end

[1] pry(#<T::Types::Simple>)> instance_variables
=> [:@raw_type, :@name, :@nilable]
[2] pry(#<T::Types::Simple>)> exit

From: /Users/ryanbrushett/.gem/ruby/3.0.1/gems/activesupport-6.1.4/lib/active_support/core_ext/object/instance_variables.rb:16 Object#instance_values:

    14: def instance_values
    15:   require 'pry'
 => 16:   binding.pry
    17:   Hash[instance_variables.map { |name| [name[1..-1], instance_variable_get(name)] }]
    18: end

[1] pry(String)> instance_variables
=> [:@__as_sorbet_type]
[2] pry(String)> exit

From: /Users/ryanbrushett/.gem/ruby/3.0.1/gems/activesupport-6.1.4/lib/active_support/core_ext/object/instance_variables.rb:16 Object#instance_values:

    14: def instance_values
    15:   require 'pry'
 => 16:   binding.pry
    17:   Hash[instance_variables.map { |name| [name[1..-1], instance_variable_get(name)] }]
    18: end

[1] pry(#<T::Types::Simple>)> instance_variables
=> [:@raw_type, :@name, :@nilable]
[2] pry(#<T::Types::Simple>)> instance_variable_get(:@name)
=> "String"
[3] pry(#<T::Types::Simple>)> instance_variable_get(:@raw_type)
=> String
[4] pry(#<T::Types::Simple>)>

```

</details>

**Comment by paracycle** [comment]
Btw, this doesn't need to be a Rails app, either. Anything that uses Active Support JSON serialization would hit the same problem after a call to `T::Utils.coerce` for the type in question.

**Comment by paracycle** [comment]
So a simpler repo is the following:
```ruby
$ pry
[1] pry(main)> require 'sorbet-runtime'
=> true
[2] pry(main)> require 'active_support/json'
=> true
[3] pry(main)> String.to_json
=> "{}"
[4] pry(main)> T::Utils.coerce(String)
=> #<T::Types::Simple:0x00007f9b13940880 @raw_type=String>
[5] pry(main)> String.to_json
SystemStackError: stack level too deep
from /Users/ufuk/.gem/ruby/2.7.2/gems/activesupport-6.1.4/lib/active_support/core_ext/object/instance_variables.rb:15:in `block in instance_values'
```
