### ISSUE TITLE
tracepoint_serializer.rb in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes)

### ISSUE THREAD

**Issue by bbugh** [sorbet/sorbet#5204]
#### Input

There is no sorbet.run this is problem in `srb init`. This installs Rails for reproduction steps, but it doesn't appear to be a rails-specific thing.

```
asdf install ruby 3.1.0
asdf local ruby 3.1.0
gem install rails -v7.0.1
gem install bundler -v2.3.6 # arm64 fix, probably not required
rails new project_name -T -c w
cd project_name
bundle add sorbet-static-and-runtime --version 0.5.9588
bundle exec srb init
```

#### Observed output

```
❔ Would you like to continue? [Y/n] Y
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
NameError: uninitialized constant ActionController::Middleware

        ActionController::Middleware,
                        ^^^^^^^^^^^^
Did you mean?  ActionController::MiddlewareStack
LoadError: Generating image variants require the image_processing gem. Please add `gem 'image_processing', '~> 1.2'` to your Gemfile.
LoadError: cannot load such file -- listen
LoadError: cannot load such file -- webrobots
LoadError: cannot load such file -- rack/session/dalli
LoadError: cannot load such file -- railties
NameError: uninitialized constant Selenium::WebDriver::Chrome::Bridge

        Selenium::WebDriver::Chrome::Bridge,
                                   ^^^^^^^^
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static-and-runtime
LoadError: cannot load such file -- sprockets-rails
/Users/bbugh/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/sorbet-0.5.9588/lib/gem-generator-tracepoint/tracepoint_serializer.rb:35:in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes) (ArgumentError)
	from /Users/bbugh/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/sorbet-0.5.9588/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /Users/bbugh/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/sorbet-0.5.9588/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
	from /Users/bbugh/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/sorbet-0.5.9588/lib/gem-generator-tracepoint.rb:43:in `main'
	from /Users/bbugh/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/sorbet-0.5.9588/bin/srb-rbi:232:in `block in make_step'
	from /Users/bbugh/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/sorbet-0.5.9588/bin/srb-rbi:118:in `init'
	from /Users/bbugh/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/sorbet-0.5.9588/bin/srb-rbi:196:in `main'
	from /Users/bbugh/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/sorbet-0.5.9588/bin/srb-rbi:237:in `<main>'
```

#### Expected behavior

No error is raised

- - -

**Comment by matssigge** [comment]
I'm getting the exact same result with Ruby 3.1.0 and similar with 3.0.2 (fails on the same error, but slightly different log before that). Ruby 2.7.5 works, however. 

I'm on an M1 MacBook Pro, which I suspect @bbugh is as well, because of the "arm64 fix" comment. However, I also tested this on x86 Linux and got the same result.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
