### ISSUE TITLE
`T::Struct` initializer enforces types at runtime even when default checked level is `:tests`

### ISSUE THREAD

**Issue by richardxia** [sorbet/sorbet#5226]
#### Input

Sorry for not submitting a sorbet.run link, but I couldn't figure out how to meaningfully set `T::Configuration.default_checked_level = :tests` in sorbet.run. I'm happy to update this with a link to sorbet.run if there is a way to configure things like that there.

```ruby
require 'sorbet-runtime'

T::Configuration.default_checked_level = :tests

class Foo < T::Struct
  const :bar, String
end

Foo.new(bar: :not_a_string)
```

#### Observed output

```
Traceback (most recent call last):
       16: from (irb):9:in `new'
       15: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
       14: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/private/methods/_methods.rb:272:in `bind_call'
       13: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/props/weak_constructor.rb:14:in `initialize'
       12: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
       11: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/private/methods/_methods.rb:272:in `bind_call'
       10: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/props/constructor.rb:23:in `construct_props_without_defaults'
        9: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/props/constructor.rb:23:in `each_pair'
        8: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/props/constructor.rb:26:in `block in construct_props_without_defaults'
        7: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/props/constructor.rb:26:in `instance_exec'
        6: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/props/private/setter_factory.rb:63:in `block in simple_non_nil_proc'
        5: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
        4: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/private/methods/_methods.rb:272:in `bind_call'
        3: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/props/private/setter_factory.rb:184:in `raise_pretty_error'
        2: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/configuration.rb:298:in `call_validation_error_handler'
        1: from /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/configuration.rb:291:in `call_validation_error_handler_default'
TypeError (Parameter 'bar': Can't set Foo.bar to :not_a_string (instance of Symbol) - need a String)
Caller: /home/rxia/proj-gems/ruby/2.7.0/gems/sorbet-runtime-0.5.9589/lib/types/private/methods/_methods.rb:272
```

#### Expected behavior

That as long as `default_checked_level` is set to `:tests`, and that we have not called `T::Configuration.enable_checking_for_sigs_marked_checked_tests`, that the above example would run successfully, despite the type error.

- - -

Just to provide a motivating example for why I consider this to be a bug, we're in the process of gradually migrating a large codebase to use Sorbet, and we do not have type signatures everywhere. In many cases, we are a bit loose with types, but in ways that would not normally cause errors due to duck typing or other implicit type coercions. Using the example above, we previously had a plain old Ruby `Struct`, as opposed to a `T::Struct`, and that `bar` field was apparently being initialized with either a String or a Symbol, and in our codebase, the passing a Symbol still "works" because we always coerce it to a String later.

We _do_ like the idea of catching cases like this, and we understand the right fix to our code here is to change the type to `T.any(String, Symbol)` or to coerce to string before initializing `Foo`. However, we'd like more granular control over runtime type checking in production, since not all of our call sites have static type information yet, and we don't want production to raise an error due to a Sorbet runtime type check failure for something that would have actually worked fine before.

**Comment by amanda-mitchell** [comment]
I just ran across this behavior and created a repo that illustrates the behavior before discovering that this issue already exists: https://github.com/amanda-mitchell/sorbet-bug-repro

This is one of the factors underlying the Tapioca issue that I reported here: https://github.com/Shopify/tapioca/issues/2130
