### ISSUE TITLE
`srb init` has failed in Ruby 3.1.1

### ISSUE THREAD

**Issue by mihyaeru21** [sorbet/sorbet#5332]
#### Input
Run `srb init` on an [empty repository](https://github.com/mihyaeru21/sorbet-init-error), I got the following errors.

env
- Sorbet 0.5.9663
- Ruby 3.1.1
- Ubuntu 20.04.3

##### Error 1

```
$ bundle exec srb init
...
Would you like to continue? [Y/n] y
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static
/home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/gem-generator-tracepoint/tracepoint_serializer.rb:35:in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes) (ArgumentError)
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/gem-generator-tracepoint.rb:43:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:232:in `block in make_step'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:118:in `init'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:196:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:237:in `<main>'
```

This is reported by #5204.
In Ruby 3, `Hash` is not automatically converted to keyword arguments.

Make the following changes to `vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/gem-generator-tracepoint.rb` and move on next error.

```diff
- TracepointSerializer.new(trace_results).serialize(output_dir)
+ TracepointSerializer.new(**trace_results).serialize(output_dir)
```

##### Error 2

```
$ bundle exec srb init
...
Would you like to continue? [Y/n] y
Generating: sorbet/config
Reusing existing config file: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static
Generating: sorbet/rbi/hidden-definitions/
Requiring all of your code
Naming all Modules
Naming Object/home/mihyaeru/.anyenv/envs/rbenv/versions/3.1.1/lib/ruby/3.1.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library. You must use the `sorted_set` gem or other alternatives. (RuntimeError)
        from /home/mihyaeru/.anyenv/envs/rbenv/versions/3.1.1/lib/ruby/3.1.0/set/sorted_set.rb:1:in `<top (required)>'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/real_stdlib.rb:77:in `require'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/real_stdlib.rb:77:in `const_get'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/real_stdlib.rb:77:in `call'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/real_stdlib.rb:77:in `real_const_get'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/constant_cache.rb:157:in `block in dfs_module'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/constant_cache.rb:145:in `each'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/constant_cache.rb:145:in `dfs_module'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/constant_cache.rb:70:in `initialize'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:68:in `constant_cache'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:75:in `all_modules_and_aliases'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:44:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:38:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:232:in `block in make_step'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:121:in `init'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:196:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:237:in `<main>'
/home/mihyaeru/.anyenv/envs/rbenv/versions/3.1.1/lib/ruby/3.1.0/set/sorted_set.rb:2:in `require': cannot load such file -- sorted_set (LoadError)
        from /home/mihyaeru/.anyenv/envs/rbenv/versions/3.1.1/lib/ruby/3.1.0/set/sorted_set.rb:2:in `<top (required)>'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/real_stdlib.rb:77:in `require'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/real_stdlib.rb:77:in `const_get'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/real_stdlib.rb:77:in `call'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/real_stdlib.rb:77:in `real_const_get'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/constant_cache.rb:157:in `block in dfs_module'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/constant_cache.rb:145:in `each'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/constant_cache.rb:145:in `dfs_module'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/constant_cache.rb:70:in `initialize'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:68:in `constant_cache'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:75:in `all_modules_and_aliases'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:44:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:38:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:232:in `block in make_step'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:121:in `init'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:196:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:237:in `<main>'
```

In Ruby 3, `SortedSet` is now excluded from `set`.
It needs to explicitly add `sorted_set` to the dependency.
Add the following to `Gemfile` and move on next error.

```
gem 'sorted_set'
```

##### Error 3

```
$ bundle exec srb init
...
Would you like to continue? [Y/n] y
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static
Generating: sorbet/rbi/hidden-definitions/
Requiring all of your code
Naming all Modules
Naming Bundler::ThorGot LoadError when trying to get nested name Bundler::Thor::RakeCompat
Naming PathnameGot NameError when trying to get nested name Pathname::FileUtils_
Generating /tmp/d20220219-31099-6vnju8/reflection.rbi with 863 modules and 37 aliases
/home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:401:in `capture_stderr': uninitialized constant Sorbet::Private::HiddenMethodFinder::StringIO (NameError)

    $stderr = StringIO.new
              ^^^^^^^^
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:89:in `gen_source_rbi'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:45:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:38:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:232:in `block in make_step'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:121:in `init'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:196:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:237:in `<main>'
```

Add the following to `vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb` and move on next error.

```
require 'stringio'
```

##### Error 4

```
$ bundle exec srb init
...
Would you like to continue? [Y/n] y
Generating: sorbet/config
Reusing existing config file: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
LoadError: cannot load such file -- sorbet
LoadError: cannot load such file -- sorbet-static
Generating: sorbet/rbi/hidden-definitions/
Requiring all of your code
Naming all Modules
Naming Bundler::ThorGot LoadError when trying to get nested name Bundler::Thor::RakeCompat
Naming PathnameGot NameError when trying to get nested name Pathname::FileUtils_
Generating /tmp/d20220219-2706-9me751/reflection.rbi with 866 modules and 37 aliases
Printing your code's symbol table into /tmp/d20220219-2706-9me751/from-source.json
Printing /tmp/d20220219-2706-9me751/reflection.rbi's symbol table into /tmp/d20220219-2706-9me751/reflection.json
/home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:153:in `write_constants': /tmp/d20220219-2706-9me751/reflection.rbi had unexpected errors. Check this file for a clue: /tmp/d20220219-2706-9me751/reflection.json.err (RuntimeError)
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:48:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/lib/hidden-definition-finder.rb:39:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:232:in `block in make_step'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:121:in `init'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:196:in `main'
        from /home/mihyaeru/ghq/github.com/mihyaeru21/sorbet-init-error/vendor/ruby/3.1.0/gems/sorbet-0.5.9663/bin/srb-rbi:237:in `<main>'

$ cat /tmp/d20220219-2706-9me751/reflection.json.err
/tmp/d20220219-2706-9me751/reflection.rbi:14763: Parent of class `Random` redefined from `Object` to `Random::Base` https://srb.help/5012
       14763 |class Random < Random::Base
                             ^^^^^^^^^^^^
```

This is reported by https://github.com/sorbet/sorbet/issues/3851#issuecomment-751403792.
In Ruby 3, `Random` inherits from `Random::Base`.
In Ruby 2.7, it inherits from `Object`.
[Sorbet's rbi](https://github.com/sorbet/sorbet/blob/d2c97f0e57238ddee8aab61fd176d99651e7b76d/rbi/core/random.rbi#L31) is Ruby 2.7 compliant and inherits from `Object`.

I couldn't figure out how to fix this.

#### Expected behavior
No error has raised and `srb init` has completed.

**Comment by swiknaba** [comment]
Sorbet worked perfectly fine on Ruby 2.7.5 on my project. Upgrading to Ruby 3, the app boots and works normally. However, re-running `srb init` errors out for me as well with the same issue as OP describes (seeing the `unconfirmed` label I can confirm this issue).

"Same issue" meaning, it starts deteriorating with the same error message:

```
.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sorbet-0.5.9668/lib/gem-generator-tracepoint/tracepoint_serializer.rb:35:in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes) (ArgumentError)
```

**Comment by mohamed-said** [comment]
I'm using `ruby 3.0.3` and I have the same error while running sorbet.
```
sorbet-0.5.9623/lib/gem-generator-tracepoint/tracepoint_serializer.rb:35:in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes) (ArgumentError)
```

**Comment by mrdev023** [comment]
Same

`ruby 3.0.3`
`sorbet-0.5.9623`

```
/home/$USER/.rvm/gems/ruby-3.0.3/gems/sorbet-0.5.9749/lib/gem-generator-tracepoint/tracepoint_serializer.rb:35:in `initialize': wrong number of arguments (given 1, expected 0; required keywords: files, delegate_classes) (ArgumentError)
        from /home/$USER/.rvm/gems/ruby-3.0.3/gems/sorbet-0.5.9749/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/$USER/.rvm/gems/ruby-3.0.3/gems/sorbet-0.5.9749/lib/gem-generator-tracepoint/tracer.rb:40:in `new'
        from /home/$USER/.rvm/gems/ruby-3.0.3/gems/sorbet-0.5.9749/lib/gem-generator-tracepoint.rb:43:in `main'
        from /home/$USER/.rvm/gems/ruby-3.0.3/gems/sorbet-0.5.9749/bin/srb-rbi:232:in `block in make_step'
        from /home/$USER/.rvm/gems/ruby-3.0.3/gems/sorbet-0.5.9749/bin/srb-rbi:118:in `init'
        from /home/$USER/.rvm/gems/ruby-3.0.3/gems/sorbet-0.5.9749/bin/srb-rbi:196:in `main'
        from /home/$USER/.rvm/gems/ruby-3.0.3/gems/sorbet-0.5.9749/bin/srb-rbi:237:in `<main>'
```

**Comment by andi-dev** [comment]
I am running in a similar set of errors when trying to init sorbet with a fresh rails 7 / ruby 3 app.
It is quite disappointing, as I believe it would make a lot of sense to set up a fresh app with sorbet.

Are there any plans on fixing the rbi tooling for ruby 3?

**Comment by Lasvad** [comment]
Also running into the same issues here with fresh rails project. This has to get to a point where it "just work" for it to be adopted more.

Rails API - Rails 7.0.2.3 
Ruby - ruby 3.1.1p18 
Sorbet typechecker 0.5.9775

**Comment by Morriar** [comment]
Not a direct answer to your questions but I would recommend switching to [Tapioca](https://github.com/Shopify/tapioca) for RBI generation. It also support RBI generation for [Rails and a few other DSLs](https://github.com/Shopify/tapioca/blob/main/manual/compilers.md). Here's a [migration guide](https://github.com/Shopify/tapioca/wiki/Migrating-to-Tapioca).

**Comment by i7an** [comment]
@Morriar I tried and it did not go smooth because of [this issue](https://github.com/Shopify/tapioca/issues/655) you created a while ago :)
I guess with enough time it is solvable. But adding sorbet to a new project is harder than I thought it would be.
