### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by sobrinho** [sorbet/sorbet#5733]
#### Input

bundle exec sorbet init

Initializing a project using legacy ruby, maybe the issue?

ruby 2.5.9p229 (2021-04-05 revision 67939) [-darwin20]

#### Observed output

```
Traceback (most recent call last):
        9631: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/bin/srb-rbi:237:in `<main>'
        9630: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/bin/srb-rbi:196:in `main'
        9629: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/bin/srb-rbi:118:in `init'
        9628: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/bin/srb-rbi:232:in `block in make_step'
        9627: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/lib/gem-generator-tracepoint.rb:43:in `main'
        9626: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/lib/gem-generator-tracepoint/tracepoint_serializer.rb:45:in `serialize'
        9625: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/lib/gem-generator-tracepoint/tracepoint_serializer.rb:100:in `preprocess'
        9624: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/lib/gem-generator-tracepoint/tracepoint_serializer.rb:133:in `filter_unused'
         ... 9619 levels...
           4: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/lib/gem-generator-tracepoint/tracepoint_serializer.rb:173:in `block in used?'
           3: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/lib/gem-generator-tracepoint/tracepoint_serializer.rb:173:in `used?'
           2: from /Users/sobrinho/.gem/ruby/2.5.9/gems/sorbet-0.5.9959/lib/gem-generator-tracepoint/tracepoint_serializer.rb:173:in `any?'
           1: from /Users/sobrinho/.rubies/ruby-2.5.9/lib/ruby/2.5.0/set.rb:338:in `each'
/Users/sobrinho/.rubies/ruby-2.5.9/lib/ruby/2.5.0/set.rb:338:in `each_key': stack level too deep (SystemStackError)
```

#### Expected behavior

No error, of course.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
