### ISSUE TITLE
Compilation database fails to build on master on M1 Macs

### ISSUE THREAD

**Issue by varungandhi-src** [sorbet/sorbet#5832]
In particular, OpenSSL fails to build:

```
openssl:
        Could not be configured. It will not be installed.
        /private/var/folders/tr/gylnxkts3bn0gyhhlrv8z9_m0000gn/T/tmp.SVqWepxg/ext/openssl/extconf.rb:97: OpenSSL library could not be found. You might want to use --with-openssl-dir=<dir> option to specify the prefix where OpenSSL is installed.
        Check ext/openssl/mkmf.log for more details.

<lots of stuff>

/private/var/folders/tr/gylnxkts3bn0gyhhlrv8z9_m0000gn/T/tmp.SVqWepxg/lib/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- openssl (LoadError)
        from /private/var/folders/tr/gylnxkts3bn0gyhhlrv8z9_m0000gn/T/tmp.SVqWepxg/lib/rubygems/core_ext/kernel_require.rb:92:in `require'
```

The OpenSSL build log in `ext/openssl/mkmf.log` says:

```
\{\"DYLD_FALLBACK_LIBRARY_PATH\"\=\>\".:../..\"\} /private/var/tmp/_bazel_varun/0eec049f96822615c65f9acc22fdf113/external/llvm_toolchain_12_0_0/bin/cc_wrapper.sh\ -fvisibility\=default\ -oconftest\ -I../../.ext/include/x86_64-darwin21\ -I../.././include\ -I../.././ext/openssl\ -isysroot\ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\ \ -isystem\ /private/var/tmp/_bazel_varun/0eec049f96822615c65f9acc22fdf113/execroot/com_stripe_ruby_typer/external/system_ssl_darwin/include\ -isystem\ /private/var/tmp/_bazel_varun/0eec049f96822615c65f9acc22fdf113/execroot/com_stripe_ruby_typer/bazel-out/darwin-dbg/bin/external/system_ssl_darwin/include\ -Wdate-time\ -D_FORTIFY_SOURCE\=2\ -D_XOPEN_SOURCE\ -D_DARWIN_C_SOURCE\ -D_DARWIN_UNLIMITED_SELECT\ -D_REENTRANT\ \ \ -g\ -fstack-protector-strong\ -Wformat\ -Werror\=format-security\ -Wno-compound-token-split-by-macro\ -fno-common\ -pipe\ conftest.c\ \ -L.\ -L../..\ -L.\ -isysroot\ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\ \ -L/private/var/tmp/_bazel_varun/0eec049f96822615c65f9acc22fdf113/execroot/com_stripe_ruby_typer/bazel-out/darwin-dbg/bin/_solib_darwin/_U@system_Ussl_Udarwin_S_S_Cssl-import___Ulib\ -L/private/var/tmp/_bazel_varun/0eec049f96822615c65f9acc22fdf113/execroot/com_stripe_ruby_typer/bazel-out/darwin-dbg/bin/_solib_darwin/_U@system_Ussl_Udarwin_S_S_Ccrypto-import___Ulib\ -mlinker-version\=400\ -fstack-protector-strong\ -L/private/var/tmp/_bazel_varun/0eec049f96822615c65f9acc22fdf113/external/llvm_toolchain_12_0_0/lib/clang/12.0.0/lib\ \ \ \ \ -lruby.2.7-static\ -framework\ Security\ -framework\ Foundation\ -lpthread\ -ldl\ -lobjc\ -lcrypto\ \ \
ld: warning: ignoring file /private/var/tmp/_bazel_varun/0eec049f96822615c65f9acc22fdf113/execroot/com_stripe_ruby_typer/bazel-out/darwin-dbg/bin/_solib_darwin/_U@system_Ussl_Udarwin_S_S_Ccrypto-import___Ulib/libcrypto.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_CRYPTO_malloc", referenced from:
      _t in conftest-d91e56.o
ld: symbol(s) not found for architecture x86_64
clang-12: error: linker command failed with exit code 1

<snip>

=== Checking for required stuff failed. ===
Makefile wasn't created. Fix the errors above.
```

It is mixing architectures incorrectly, instead of building everything for x86_64/Rosetta, leading to the symbol not being found. It looks like [CRYPTO_malloc is required](https://github.com/ruby/ruby/blob/master/ext/openssl/extconf.rb#L53), so its absence makes the build fail.

On my machine, this problem is fixed by the following PR:
- https://github.com/sorbet/sorbet/pull/5228 (tested with a5c40e0f91b7ece25124b62e1d8b37f238ff8807, which is the latest commit at the time of writing this)

I've mainly created this issue so that it is helpful to anyone else who runs into this same problem. I think this can be closed after the linked PR above is merged.

**Comment by varungandhi-src** [comment]
Hmm, looks like I was wrong about this. The problem isn't _fixed_ by the LLVM 13 upgrade PR, it is the case that it diverged from master at an older commit which was able to build the compilation database successfully on an M1.

Oddly enough, based on bisection, the commit which introduced a regression seems to be https://github.com/sorbet/sorbet/pull/5480, but that is not modifying the Ruby build. 😕 

```
# bad: [134f68928c4044149c4be506692dbd05fbe3296e] ResolutionItem -> ConstantResolutionItem (#5830)
# good: [8019922f0308e99c6106c0f82dde3877bb45f3a1] No-op changes in service of indentation-aware parser (#5261)
# bad: [df7457ad4226dca17e255f11e8eec10fa69ddc53] Add T::Enumerator::Lazy (requires static and runtime bump!) (#5552)
# good: [66162a36d7d459d6ffe236ce1bcbf50fa63c77bf] Decouple rename.cc (#5401)
# bad: [f30c52479e8db22532a71fc6e608c9bc5e7d0bc3] Potentially delete some dead namer code (#5485)
# good: [eec259e33676a69b7a00ef20de710f01d2c03618] avoid making `Resolver::sanityCheck` look like it mutates things (#5433)
# good: [e61de7fb64a6a5c502098aeeb3dae52de77cff81] be smarter about completing on `self.` (#5461)
# good: [2af90c8db84b0f86e7c62f4fabc5955beedcdf54] Remove mentions of #dev-productivity channel (#5478)
# bad: [c6b223eccfb18233268d4b1f5758ec75165ef264] Bump compdb version to fix header-only cc_library assumed as C (#5480)
# good: [f72aeb0a7620af828918fc1e37587548c6b41f30] [RFC] Do not error on `**kwargs` parameters name mismatch (#5142)
# first bad commit: [c6b223eccfb18233268d4b1f5758ec75165ef264] Bump compdb version to fix header-only cc_library assumed as C (#5480)
```

**Comment by jez** [comment]
Does not seem to reproduce anymore. Not sure if it was fixed or not, but note that support for Apple Silicon universal binaries landed in #8183, and now the version of Bazel used to build Sorbet on Apple Silicon Macs is the arm64 version of Bazel, not the x86_64 version of Bazel running under Rosetta, which could have changed things.
