### ISSUE TITLE
T::Class[T.anything] vs Class incompatible override signature

### ISSUE THREAD

**Issue by dcecile** [sorbet/sorbet#7265]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Arequire%20'sorbet-runtime'%0A%0Aclass%20Alpha%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20overridable.returns%28T.nilable%28T%3A%3AClass%5BT.anything%5D%29%29%20%7D%0A%20%20def%20run%0A%20%20end%0Aend%0A%0Aclass%20Beta%20%3C%20Alpha%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20%7B%20override.returns%28Class%29%20%7D%0A%20%20def%20run%0A%20%20%20%20Integer%0A%20%20end%0Aend%0A%0Aclass%20Gamma%20%3C%20Alpha%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20%7B%20override.returns%28T%3A%3AClass%5BT.anything%5D%29%20%7D%0A%20%20def%20run%0A%20%20%20%20String%0A%20%20end%0Aend%0A%0Abegin%0A%20%20puts%20%22Beta%20%23%7BBeta.new.run%7D%22%0Arescue%20StandardError%20%3D%3E%20e%0A%20%20puts%20%22%23%7Be%7D%22%0A%20%20puts%20%22%23%7B%28e.backtrace%20%7C%7C%20%5B%5D%29.join%20%24%2F%7D%22%0Aend%0A%0Abegin%0A%20%20puts%20%22Gamma%20%23%7BGamma.new.run%7D%22%0Arescue%20StandardError%20%3D%3E%20e%0A%20%20puts%20%22%23%7Be%7D%22%0A%20%20puts%20%22%23%7B%28e.backtrace%20%7C%7C%20%5B%5D%29.join%20%24%2F%7D%22%0Aend%0A)

```ruby
# typed: true
require 'sorbet-runtime'

class Alpha
  extend T::Sig

  sig { overridable.returns(T.nilable(T::Class[T.anything])) }
  def run
  end
end

class Beta < Alpha
  extend T::Sig
  
  sig { override.returns(Class) }
  def run
    Integer
  end
end

class Gamma < Alpha
  extend T::Sig
  
  sig { override.returns(T::Class[T.anything]) }
  def run
    String
  end
end

begin
  puts "Beta #{Beta.new.run}"
rescue StandardError => e
  puts "#{e}"
  puts "#{(e.backtrace || []).join $/}"
end

begin
  puts "Gamma #{Gamma.new.run}"
rescue StandardError => e
  puts "#{e}"
  puts "#{(e.backtrace || []).join $/}"
end
```

#### Observed output

```
No errors! Great job.
```

Runtime output:

```
Incompatible return type in signature for override of method `run`:
* Base: `T.nilable(T::Class[T.anything])` (in Alpha at tmp/override.rb:8)
* Override: `Class` (in Beta at tmp/override.rb:16)
(The types must be covariant.)
/nix/store/zrsb6sn4sdxf14qa6gglfipnkqwxrx5b-ruby3.0.5-sorbet-runtime-0.5.10958/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.10958/lib/types/private/methods/signature_validation.rb:266:in `validate_override_types'
/nix/store/zrsb6sn4sdxf14qa6gglfipnkqwxrx5b-ruby3.0.5-sorbet-runtime-0.5.10958/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.10958/lib/types/private/methods/signature_validation.rb:92:in `validate'
/nix/store/zrsb6sn4sdxf14qa6gglfipnkqwxrx5b-ruby3.0.5-sorbet-runtime-0.5.10958/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.10958/lib/types/private/methods/_methods.rb:390:in `build_sig'
/nix/store/zrsb6sn4sdxf14qa6gglfipnkqwxrx5b-ruby3.0.5-sorbet-runtime-0.5.10958/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.10958/lib/types/private/methods/_methods.rb:346:in `run_sig'
/nix/store/zrsb6sn4sdxf14qa6gglfipnkqwxrx5b-ruby3.0.5-sorbet-runtime-0.5.10958/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.10958/lib/types/private/methods/_methods.rb:246:in `block in _on_method_added'
/nix/store/zrsb6sn4sdxf14qa6gglfipnkqwxrx5b-ruby3.0.5-sorbet-runtime-0.5.10958/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.10958/lib/types/private/methods/_methods.rb:447:in `run_sig_block_for_key'
/nix/store/zrsb6sn4sdxf14qa6gglfipnkqwxrx5b-ruby3.0.5-sorbet-runtime-0.5.10958/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.10958/lib/types/private/methods/_methods.rb:427:in `maybe_run_sig_block_for_key'
/nix/store/zrsb6sn4sdxf14qa6gglfipnkqwxrx5b-ruby3.0.5-sorbet-runtime-0.5.10958/lib/ruby/gems/3.0.0/gems/sorbet-runtime-0.5.10958/lib/types/private/methods/_methods.rb:256:in `block in _on_method_added'
tmp/override.rb:31:in `<main>'
Gamma String
```

#### Expected behavior

`sorbet-runtime` shouldn't raise an error because `Class` and `T::Class[T.anything]` are essentially the same.

- - -

We tried upgrading from 0.5.10568 to 0.5.10958, and `srb tc` prompted us to change the non-generic `Class` usages in our `typed: strict` superclass (e.g. `Alpha`), but not in our `typed: true` subclass (e.g. `Beta`).

`srb tc` didn't raise any errors after updating the `typed: strict` file, and we only got the incompatible override error at runtime.

This roughly lines up with the [docs](https://sorbet.org/docs/class-of#tclass-vs-class) that say...

> This error is only reported at [# typed: strict or higher](https://sorbet.org/docs/static). At lower levels, Sorbet implicitly assumes that a bare type annotation like Class is the same as T::Class[T.anything].

...but if Sorbet assumes they're the same for type checking, maybe it should assume they're the same for override runtime compatilibity checks too?

**Comment by dcecile** [comment]
Thanks so much @jez! Upgraded to yesterday's build and the fix works perfect!
