### ISSUE TITLE
Sorbet forces block variables to have the exact signature of expected block argument

### ISSUE THREAD

**Issue by ipvalverde** [sorbet/sorbet#7871]
Sorbet forces a proc variable to have the same amount of arguments as of the expected proc argument with a signature. [The documentation](https://sorbet.org/docs/procs) states that:

> At present, all parameters are assumed to be required positional parameters—T.proc types cannot declare optional nor keyword parameters.

But this is not the behaviour for inline procs. They should be consistent, ideally, allowing for a parameterless proc to be sent as an argument to a method that expects a proc with arguments (since the languages allows for that).

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20params%28%0A%20%20%20%20block%3A%20T.proc.params%28current_time%3A%20Time%29.void%0A%20%20%29.void%0Aend%0Adef%20with_current_time%28%26block%29%0A%20%20block.call%28Time.now%29%0Aend%0A%0A%0A%23%20Procs%20with%20an%20argument%0Awith_current_time%20do%20%7Ctime%7C%0A%20%20puts%20%22Hey%20there!%22%0Aend%0A%0Aproc_with_untyped_paramater%20%3D%20proc%20do%20%7Ctime%7C%0A%20%20puts%20%22Hey%20there!%22%0Aend%0Awith_current_time%28%26proc_with_untyped_paramater%29%0A%0A%23%20Procs%20without%20an%20argument%0Awith_current_time%20do%0A%20%20puts%20%22Hello%20again!%22%0Aend%0A%0Aparameterless_proc%20%3D%20proc%20do%0A%20%20puts%20%22Hello%20again!%22%0Aend%0A%0A%23%20Sorbet%20prevents%20me%20from%20using%20the%20proc%2C%20even%20though%0A%23%20it's%20a%20valid%20code%2C%20and%20I%20can%20also%20use%20it%20if%20the%20block%20is%20%22inline%22.%0Awith_current_time%28%26parameterless_proc%29)

```ruby
# typed: true
extend T::Sig

sig do
  params(
    block: T.proc.params(current_time: Time).void
  ).void
end
def with_current_time(&block)
  block.call(Time.now)
end


# Procs without an argument
with_current_time do
  puts "Hello again!"
end

parameterless_proc = proc do
  puts "Hello again!"
end

# Sorbet prevents me from using the proc, even though
# it's a valid code, and I can also use it if the block is "inline".
with_current_time(&parameterless_proc)
```

#### Observed output

```
editor.rb:35: Expected T.proc.params(arg0: Time).void but found T.proc.returns(T.untyped) for block argument https://srb.help/7002
    35 |with_current_time(&parameterless_proc)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Expected T.proc.params(arg0: Time).void for block argument block of method Object#with_current_time:
    editor.rb:6:
     6 |    block: T.proc.params(current_time: Time).void
            ^^^^^
  Detailed explanation:
    Proc0 does not derive from Proc1
Errors: 1
```

#### Expected behavior

I would expect the that a variable containing a proc would behave the same as having an inline proc.

- - -

**Comment by jez** [comment]
The underlying issue here is that Sorbet doesn't have separate types for lambdas and procs. Sorbet tries to get around this by sometimes choosing to back `T.proc` types by behavior from procs and sometimes back them with behavior from lambdas. In this case, Sorbet has chosen the functionality that would be required for checking lambdas correctly:

```ruby
# typed: true
require_relative './gems/sorbet-runtime/lib/sorbet-runtime'
extend T::Sig

sig do
  params(
    block: T.proc.params(current_time: Time).void
  ).void
end
def with_current_time(&block)
  block.call(Time.now)
end


# Procs without an argument
with_current_time do
  puts "Hello again!"
end

parameterless_proc = proc do
  puts "Hello again!"
end
with_current_time(&parameterless_proc)

parameterless_lambda = lambda do
  puts "Hello again!"
end
with_current_time(&parameterless_lambda)
```

```
❯ ruby foo.rb
Hello again!
Hello again!
foo.rb:25:in `block in <main>': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from foo.rb:11:in `with_current_time'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/call_validation.rb:191:in `block in create_validator_slow'
        from foo.rb:28:in `<main>'
```

To drive home the point: Sorbet's inferred type for the two callable variables in the above snippet are the same: `T.proc.returns(T.untyped)`.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Arequire_relative%20'.%2Fgems%2Fsorbet-runtime%2Flib%2Fsorbet-runtime'%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20params%28%0A%20%20%20%20block%3A%20T.proc.params%28current_time%3A%20Time%29.void%0A%20%20%29.void%0Aend%0Adef%20with_current_time%28%26block%29%0A%20%20block.call%28Time.now%29%0Aend%0A%0A%0A%23%20Procs%20without%20an%20argument%0Awith_current_time%20do%0A%20%20puts%20%22Hello%20again!%22%0Aend%0A%0Aparameterless_proc%20%3D%20proc%20do%0A%20%20puts%20%22Hello%20again!%22%0Aend%0AT.reveal_type%28parameterless_proc%29%0A%0Aparameterless_lambda%20%3D%20lambda%20do%0A%20%20puts%20%22Hello%20again!%22%0Aend%0AT.reveal_type%28parameterless_lambda%29%0A)
