### ISSUE TITLE
BasicObject not supported by sorbet-runtime

### ISSUE THREAD

**Issue by XrXr** [sorbet/sorbet#908]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Arequire%20'sorbet-runtime'%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(BasicObject)%7D%0A%20%20def%20self.foo%0A%20%20%20%20BasicObject.new%0A%20%20end%0Aend%0A%0AFoo.foo%0A)

```ruby
# typed: true
require 'sorbet-runtime'

class Foo
  extend T::Sig

  sig {returns(BasicObject)}
  def self.foo
    BasicObject.new
  end
end

Foo.foo
```

#### Observed output

```
alanwu ~/tmp> ruby crash-sorbet-runtime.rb
Traceback (most recent call last):
	4: from crash-sorbet-runtime.rb:13:in `<main>'
	3: from /Users/alanwu/.gem/ruby/2.6.3/gems/sorbet-runtime-0.4.4237/lib/types/private/methods/_methods.rb:157:in `block in _on_method_added'
	2: from /Users/alanwu/.gem/ruby/2.6.3/gems/sorbet-runtime-0.4.4237/lib/types/private/methods/call_validation.rb:136:in `validate_call'
	1: from /Users/alanwu/.gem/ruby/2.6.3/gems/sorbet-runtime-0.4.4237/lib/types/types/base.rb:117:in `error_message_for_obj'
/Users/alanwu/.gem/ruby/2.6.3/gems/sorbet-runtime-0.4.4237/lib/types/types/simple.rb:20:in `valid?': undefined method `is_a?' for #<BasicObject:0x00007f84140bb270> (NoMethodError)
```

#### Expected behavior

It shouldn't crash. I suppose in general this happens with any object that do not respond to `is_a?`.

**Comment by XrXr** [comment]
I ran some benchmarks on 2.4.6 and it looks like rescuing when an exception is not thrown is free, but it is very costly when an exception is thrown:

`plain` is an instance of a plain object. `basic` is a BasicObject.

```
Warming up --------------------------------------
without rescue plain   277.222k i/100ms
   with rescue plain   274.130k i/100ms
   with rescue basic    52.081k i/100ms
ask for permission plain
                       245.585k i/100ms
ask for permission basic
                       262.886k i/100ms
Calculating -------------------------------------
without rescue plain      6.150M (± 1.8%) i/s -     30.772M in   5.005583s
   with rescue plain      6.275M (± 1.0%) i/s -     31.525M in   5.024058s
   with rescue basic    590.892k (± 1.4%) i/s -      2.969M in   5.024898s
ask for permission plain
                          4.643M (± 4.9%) i/s -     23.331M in   5.036801s
ask for permission basic
                          5.329M (± 1.2%) i/s -     26.814M in   5.032223s

Comparison:
   with rescue plain:  6275423.7 i/s
without rescue plain:  6149542.9 i/s - same-ish: difference falls within error
ask for permission basic:  5329366.0 i/s - 1.18x  slower
ask for permission plain:  4643257.8 i/s - 1.35x  slower
   with rescue basic:   590892.2 i/s - 10.62x  slower
```

the option that gives the most predictable performance is
```ruby
def ask_for_permission(obj)
  if defined?(obj.is_a?)
    obj.is_a?(Plain)
  else
    Plain === obj
  end
end
```
But this is slower than the baseline that just calls `is_a?` (15%)

https://gist.github.com/XrXr/da60c59199ea279e61e37c7b9baf9bef

**Comment by DarkDimius** [comment]
Yeah, 15% seems like a lot. We run it in production all the time and thus 15% regression will be hard to motivate.
I actually think we should bite the bullet and at some point move to using `===`, it's just it's going to be an unpleasant migration.
