### ISSUE TITLE
Getting "can't modify frozen Module" during initial setup

### ISSUE THREAD

**Issue by jasnow** [sorbet/sorbet#938]
Using the https://sorbet.org/docs/adopting to add to existing Rails repo.

After adding the two gems to Gemfile and running "bundle" (successful).

1. I ran 
```
bundle exec ruby -e 'puts(require "sorbet-runtime")'
```
and get on Mac OS 10.12.6
```
Traceback (most recent call last):
	5: from -e:1:in `<main>'
	4: from -e:1:in `require'
	3: from /Users/USER/.rvm/gems/ruby-2.7.0-preview1@ruby2.7-rails6.0/gems/sorbet-runtime-0.4.4259/lib/sorbet-runtime.rb:55:in `<top (required)>'
	2: from /Users/USER/.rvm/gems/ruby-2.7.0-preview1@ruby2.7-rails6.0/gems/sorbet-runtime-0.4.4259/lib/sorbet-runtime.rb:55:in `require_relative'
	1: from /Users/USER/.rvm/gems/ruby-2.7.0-preview1@ruby2.7-rails6.0/gems/sorbet-runtime-0.4.4259/lib/types/private/types/void.rb:6:in `<top (required)>'
/Users/USER/.rvm/gems/ruby-2.7.0-preview1@ruby2.7-rails6.0/gems/sorbet-runtime-0.4.4259/lib/types/private/types/void.rb:17:in `<class:Void>': can't modify frozen Module (FrozenError)
```

**Comment by DarkDimius** [comment]
From looks of it, you're running an pre-release version of Ruby. It doesn't work yet.

**Comment by jasnow** [comment]
OK

**Comment by jasnow** [comment]
Downgraded a repo of  mine and got as far as step 2 in https://sorbet.org/docs/adopting .
When I ran step 3 in above document, "srb init" failed (LOTS OF OUTPUTS) so I tried "srb", I got:
```
dyld: Symbol not found: __ZTISt18bad_variant_access
  Referenced from: /Users/macbookpro/.rvm/gems/ruby-2.6.3@ruby2.6-rails6.0/gems/sorbet-static-0.4.4271-universal-darwin-16/libexec/sorbet
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/macbookpro/.rvm/gems/ruby-2.6.3@ruby2.6-rails6.0/gems/sorbet-static-0.4.4271-universal-darwin-16/libexec/sorbet
/Users/macbookpro/.rvm/gems/ruby-2.6.3@ruby2.6-rails6.0/gems/sorbet-0.4.4271/bin/srb: line 43: 77252 Abort trap: 6           "${sorbet[0]}" "${args[@]}"
```
Then I googled and found hints that my version of 
MAC OS (10.12.6) is not supported by this software.

**Comment by jasnow** [comment]
Moving future comments to #946
