### ISSUE TITLE
srb init fails with load: wrong number of arguments

### ISSUE THREAD

**Issue by thomasdziedzic-pd** [sorbet/sorbet#949]
```
$ bundle exec srb init

👋 Hey there!

This script will get this project ready to use with Sorbet by creating a
sorbet/ folder for your project. It will contain:

- a config file
- a bunch of 'RBI files'

RBI stands for 'Ruby Interface'; these files define classes, methods, and
constants that exist, but which Sorbet doesn't always know about.

⚠️  Heads up:

To set up your project, this script will take two potentially destructive
actions:

1.  It will require every file in your project. Specifically, every script in
    your project will be run, unless that script checks if __FILE__ == $PROGRAM_NAME
    before running any code, or has the magic comment # typed: ignore in it.

2.  It will add a comment to the top of every file (like # typed: false or
    # typed: true, depending on how many errors were found in that file.)

❔ Would you like to continue? [Y/n]
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
/Users/thomas/work/web/app/models/billing/common.rb:2: warning: already initialized constant Billing::ZERO_MONEY
/Users/thomas/work/web/app/models/billing/common.rb:2: warning: previous definition of ZERO_MONEY was here
/Users/thomas/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:243:in `load': wrong number of arguments (given 0, expected 1..2) (ArgumentError)
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/capistrano-shared-file-1.2.0/lib/capistrano/shared_file/tasks.rb:7:in `<top (required)>'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/capistrano-shared-file-1.2.0/lib/capistrano-shared-file.rb:2:in `<top (required)>'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/lib/gem_loader.rb:553:in `require_gem'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/lib/gem_loader.rb:572:in `block in require_all_gems'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/lib/gem_loader.rb:570:in `each'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/lib/gem_loader.rb:570:in `require_all_gems'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/lib/require_everything.rb:39:in `load_bundler'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/lib/require_everything.rb:19:in `require_everything'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/lib/gem-generator-tracepoint.rb:39:in `block in main'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/lib/gem-generator-tracepoint/tracer.rb:70:in `trace'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/lib/gem-generator-tracepoint.rb:38:in `main'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/bin/srb-rbi:227:in `block in make_step'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/bin/srb-rbi:98:in `main'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4263/bin/srb-rbi:232:in `<main>'
```

**Comment by azdavis** [comment]
Thanks for the bug report.

It's difficult to help debugging if we can't see what you're running `srb init` over. Is your project open-source? Could you direct us to your project's source, or a minimal example that reproduces this error?

**Comment by thomasdziedzic-pd** [comment]
I tried to create a minimal test case:

Using ruby 2.3.3 and creating a single file called `Gemfile` with the contents:

```
source 'https://rubygems.org'

gem 'rails', '3.2.22.4'
gem 'capistrano-shared-file', '1.2.0'
gem 'sorbet'
gem 'sorbet-runtime'
```

Gives me the following error with `bundle exec srb init`:

```
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
/Users/thomas/.rvm/gems/ruby-2.3.3/gems/capistrano-shared-file-1.2.0/lib/capistrano/shared_file/tasks.rb:3:in `<top (required)>': uninitialized constant Capistrano::Configuration (NameError)
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/capistrano-shared-file-1.2.0/lib/capistrano-shared-file.rb:2:in `require'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/capistrano-shared-file-1.2.0/lib/capistrano-shared-file.rb:2:in `<top (required)>'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/gem_loader.rb:553:in `require'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/gem_loader.rb:553:in `require_gem'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/gem_loader.rb:572:in `block in require_all_gems'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/gem_loader.rb:570:in `each'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/gem_loader.rb:570:in `require_all_gems'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/require_everything.rb:39:in `load_bundler'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/require_everything.rb:19:in `require_everything'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/gem-generator-tracepoint.rb:39:in `block in main'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/gem-generator-tracepoint/tracer.rb:70:in `trace'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/lib/gem-generator-tracepoint.rb:38:in `main'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/bin/srb-rbi:227:in `block in make_step'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/bin/srb-rbi:98:in `main'
	from /Users/thomas/.rvm/gems/ruby-2.3.3/gems/sorbet-0.4.4271/bin/srb-rbi:232:in `<main>'
```

**Comment by nadnoslen** [comment]
I too just got this error trying out Sorbet in my Rails *6* application.  Mine died over on rail's `engine.rb`:

```
Generating: sorbet/config
Generating: sorbet/rbi/sorbet-typed/
Generating: sorbet/rbi/gems/
Traceback (most recent call last):
...
... .asdf/installs/Ruby/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/rails-40ca7fadc918/railties/lib/rails/engine.rb:711:in `_all_load_paths': wrong number of arguments (given 0, expected 1) (ArgumentError)
```

**Comment by ptarjan** [comment]
This feels like someone is making a `.load` method which is shadowing `Kernel#load`. You're going to have to bisect your `Gemfile` to find which gem is the offender and get them to fix their load order (or get them to stop monkeypatching `.load`).

**Comment by astrocket** [comment]
For those who might google this page.
This issue is related with the latest Rails 6 version's update on requiring parameter for `_all_load_paths` method that sorbet uses to load everything before `srb init`

https://github.com/rails/rails/commit/b6e17b6a4b67ccc9fac5fe16741c3db720f00959#diff-1073ed8063cdf047e123bfdefa114422

It has been fixed with today's sorbet version so just update your Gemfile with later than below version

https://github.com/sorbet/sorbet/releases/tag/0.4.4563.20190802005658-21b05b401

@thomasdziedzic-pd
